### ISSUE TITLE
PANIC: invalid or out-of-range date

### ISSUE THREAD

**Issue by passionkind** [prisma/prisma-client-js#717] opened 2020-06-05 08:12 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.16.2           | 
| OS       | darwin             |
| Prisma   | 2.0.0-beta.8       |

## Logs
```
  prisma-client Client Version 2.0.0-beta.8  +0ms
  prisma-client Engine Version ff6959d77f8880ec037ed8201fff4a92f3aabaa0  +1ms
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/Users/bastian/development/ehrlgroup/pollywog/api-legacy-website/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/Users/bastian/development/ehrlgroup/pollywog/api-legacy-website/node_modules/.prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/Users/bastian/development/ehrlgroup/pollywog/api-legacy-website/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.0.0-beta.8'
  prisma-client   }
  prisma-client }  +0ms
  prisma-client Prisma Client call:  +81ms
  prisma-client prisma.hg_objects.findMany(undefined)  +0ms
  prisma-client Generated request:  +0ms
  prisma-client query {
  prisma-client   findManyhg_objects {
  prisma-client     obj_add
  prisma-client     obj_artist_add
  prisma-client     obj_artist_id
  prisma-client     obj_artno
  prisma-client     obj_auc
  prisma-client     obj_auction_link
  prisma-client     obj_auction_title
  prisma-client     obj_c
  prisma-client     obj_changed
  prisma-client     obj_cms_user
  prisma-client     obj_comment_de
  prisma-client     obj_comment_en
  prisma-client     obj_d
  prisma-client     obj_date_de
  prisma-client     obj_date_en
  prisma-client     obj_depth
  prisma-client     obj_desc_de
  prisma-client     obj_desc_en
  prisma-client     obj_diameter
  prisma-client     obj_dimension
  prisma-client     obj_d_copy
  prisma-client     obj_end_date
  prisma-client     obj_head_de
  prisma-client     obj_head_en
  prisma-client     obj_height
  prisma-client     obj_id
  prisma-client     obj_img
  prisma-client     obj_marks
  prisma-client     obj_material_de
  prisma-client     obj_material_en
  prisma-client     obj_newend_date
  prisma-client     obj_newstart_date
  prisma-client     obj_norm_taxed
  prisma-client     obj_onoff
  prisma-client     obj_ordered
  prisma-client     obj_origin_de
  prisma-client     obj_origin_en
  prisma-client     obj_price
  prisma-client     obj_price_raw
  prisma-client     obj_s
  prisma-client     obj_select
  prisma-client     obj_select_show
  prisma-client     obj_sheight
  prisma-client     obj_show_top
  prisma-client     obj_sort_dep
  prisma-client     obj_sort_highlight
  prisma-client     obj_sort_select
  prisma-client     obj_vg_taxed
  prisma-client     obj_weight
  prisma-client     obj_width
  prisma-client   }
  prisma-client }
  prisma-client   +0ms
  plusX Execution permissions of /Users/bastian/development/ehrlgroup/pollywog/api-legacy-website/node_modules/.prisma/client/query-engine-darwin are fine  +0ms
```

**Comment by passionkind** [comment] 2020-06-05 08:16
I'm also receiving many of the following errors when querying different tables:

`Value '1' not found in enum 'InternalEnum { name: "hg_fairs_onoff", values: [] }'`
`Value '6' not found in enum 'InternalEnum { name: "hg_cms_user_cms_group_id", values: [] }'`

**Comment by pantharshit00** [comment] 2020-06-05 09:05
@passionkind Can you please share your schema? If you can share a reproduction inside of a git repo , that would be better.

**Comment by passionkind** [comment] 2020-06-05 12:43
@pantharshit00 

following is the original schema that was generated. Have turned some @unique fields into @id fields meanwhile but removed such changes here

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model analytics_consent {
  consent     String?
  date        DateTime?
  domain      String?
  expire      DateTime?
  id          Int       @default(autoincrement()) @id
  ip          String
  journey     String?
  landingpage String?
  lastvisit   DateTime?
  pagecount   Int?
  referrer    String?
  script      String?
  uid         String?
  user_agent  String?

  @@index([script], name: "cookie")
  @@index([ip], name: "hash")
  @@index([date], name: "session")
}

model hg_artists {
  art_add_date    Int                  @default(0)
  art_birth       String
  art_birth_loc   String
  art_change_date DateTime             @default(dbgenerated())
  art_cms_user    Int                  @default(0)
  art_death       String
  art_death_loc   String
  art_id          Int                  @default(0) @id
  art_onoff       hg_artists_art_onoff @default(dbgenerated())
  art_pre         String
  art_pseudo      String
  art_school      String
  art_sur         String
}

model hg_cms_dependies {
  dependies_change_date DateTime @default(now())
  dependies_cms_user    Int
  dependies_desc        String
  dependies_id          Int      @default(autoincrement()) @id
  dependies_key         String
  dependies_value       Float
}

model hg_cms_group {
  cms_group_hidden        hg_cms_group_cms_group_hidden
  cms_group_id            Int                                  @id
  cms_group_name          String
  cms_group_read          hg_cms_group_cms_group_read
  cms_group_read_limited  hg_cms_group_cms_group_read_limited
  cms_group_write         hg_cms_group_cms_group_write
  cms_group_write_limited hg_cms_group_cms_group_write_limited
}

model hg_cms_user {
  cms_group_id         hg_cms_user_cms_group_id
  cms_user             String                       @unique
  cms_user_contact     hg_cms_user_cms_user_contact @default(dbgenerated())
  cms_user_contract    String
  cms_user_id          Int                          @default(autoincrement()) @id
  // This type is currently not supported.
  // cms_user_password binary?
}

model hg_currency {
  currency_change_date DateTime @default(now())
  currency_cms_user    Int
  currency_from        String   @default("")
  currency_id          Int      @default(0) @unique
  currency_rate        Float    @default(0)
  currency_to          String   @default("")
}

model hg_delivery_address {
  user_add_date    DateTime @default(now())
  user_area_code   String?
  user_change_date DateTime @default(dbgenerated())
  user_city        String?
  user_company     String?
  user_country     String?
  user_country_abr String?
  user_dev         Int      @default(autoincrement()) @id
  user_email       String?
  user_fax         String?
  user_firstname   String?
  user_id          Int      @default(0)
  user_lastname    String?
  user_street      String?
  user_tax         String   @default("")
  user_tel1        String?
  user_tel2        String?
  user_title       String?
  user_to          String?

  @@index([user_id], name: "user_id")
  @@index([user_lastname], name: "user_lastname")
}

model hg_departments {
  dep_add_date    DateTime                 @default(dbgenerated())
  dep_c           Int                      @default(0)
  dep_change_date DateTime                 @default(dbgenerated())
  dep_cms_user    Int
  dep_code        String
  dep_id          Int                      @default(autoincrement()) @id
  dep_id_parent   Int                      @default(0)
  dep_img         String
  dep_key_de      String
  dep_key_en      String
  dep_level       Int                      @default(0)
  dep_link        String
  dep_name_de     String
  dep_name_en     String
  dep_onoff       hg_departments_dep_onoff @default(dbgenerated())
  dep_sorting     Int
  dep_text_de     String
  dep_text_en     String
  dep_title_de    String
  dep_title_en    String
}

model hg_departments_alt {
  dep_add_date    DateTime                     @default(dbgenerated())
  dep_c           Int                          @default(0)
  dep_change_date DateTime                     @default(dbgenerated())
  dep_cms_user    Int
  dep_code        String
  dep_id          Int                          @default(autoincrement()) @id
  dep_id_parent   Int                          @default(0)
  dep_img         String
  dep_key_de      String
  dep_key_en      String
  dep_level       Int                          @default(0)
  dep_link        String
  dep_name_de     String
  dep_name_en     String
  dep_onoff       hg_departments_alt_dep_onoff @default(dbgenerated())
  dep_sorting     Int
  dep_text_de     String
  dep_text_en     String
}

model hg_departments_copy1 {
  dep_add_date    DateTime                       @default(dbgenerated())
  dep_c           Int                            @default(0)
  dep_change_date DateTime                       @default(dbgenerated())
  dep_cms_user    Int
  dep_code        String
  dep_id          Int                            @default(autoincrement()) @id
  dep_id_parent   Int                            @default(0)
  dep_img         String
  dep_key_de      String
  dep_key_en      String
  dep_level       Int                            @default(0)
  dep_link        String
  dep_name_de     String
  dep_name_en     String
  dep_onoff       hg_departments_copy1_dep_onoff @default(dbgenerated())
  dep_sorting     Int
  dep_text_de     String
  dep_text_en     String
}

model hg_departments_org {
  dep_add_date    DateTime                     @default(dbgenerated())
  dep_c           Int                          @default(0)
  dep_change_date DateTime                     @default(dbgenerated())
  dep_cms_user    Int
  dep_code        String
  dep_id          Int                          @default(autoincrement()) @id
  dep_id_parent   Int                          @default(0)
  dep_img         String
  dep_key_de      String
  dep_key_en      String
  dep_level       Int                          @default(0)
  dep_link        String
  dep_name_de     String
  dep_name_en     String
  dep_onoff       hg_departments_org_dep_onoff @default(dbgenerated())
  dep_sorting     Int
  dep_text_de     String
  dep_text_en     String
}

model hg_events {
  change_date DateTime        @default(dbgenerated())
  cms_user    Int
  date_de     String
  date_en     String
  desc_de     String
  desc_en     String
  enddate     DateTime        @default(dbgenerated())
  head_de     String
  head_en     String
  href        String
  id          Int             @default(autoincrement()) @id
  image       String
  onoff       hg_events_onoff @default(dbgenerated())
}

model hg_fairs {
  change_date DateTime       @default(dbgenerated())
  cms_user    Int
  date_de     String
  date_en     String
  desc_de     String
  desc_en     String
  enddate     DateTime       @default(dbgenerated())
  href        String
  id          Int            @default(autoincrement()) @id
  onoff       hg_fairs_onoff @default(dbgenerated())
}

// The underlying table does not contain a unique identifier and can therefore currently not be handled.
// model hg_instagram {
  // company String
  // url     String
// }

model hg_keywords {
  c    Int     @default(0)
  id   Int     @default(autoincrement()) @id
  word String?
}

model hg_legalinfo {
  legalinfo_change_date DateTime @default(now())
  legalinfo_cms_user    Int
  legalinfo_desc        String
  legalinfo_id          Int      @default(autoincrement()) @id
  legalinfo_lng_code    String
  legalinfo_menu        Int
  legalinfo_mpoint      String
  legalinfo_submenu     Int
  legalinfo_subpoint    String
}

model hg_newsletter {
  news_artno       String   @default("")
  news_change_date DateTime @default(now())
  news_cms_user    Int      @default(0)
  news_file        String   @default("")
  news_href        String   @default("")
  news_href_name   String   @default("")
  news_id          Int      @default(autoincrement()) @id
  news_name        String
  news_objects     String
  news_subtitle    String
  news_text        String
  news_title       String
  news_type        Int      @default(0)
}

model hg_notes {
  notes_account_id      Int?
  notes_add_date        Int?
  notes_cart_date       Int?
  notes_id              Int     @default(autoincrement()) @id
  notes_object_bid      Float?
  notes_object_id       Int?
  notes_order_date      Int?
  notes_sended          Boolean @default(false)
  notes_session         String  @default("")
  notes_writtenbid_date Int?
}

model hg_objects {
  obj_add            Int                        @default(0)
  obj_artist_add     String
  obj_artist_id      Int                        @default(0)
  obj_artno          String                     @default("0")
  obj_auc            Int                        @default(0)
  obj_auction_link   String
  obj_auction_title  String
  obj_c              Int
  obj_changed        DateTime                   @default(dbgenerated())
  obj_cms_user       Int                        @default(0)
  obj_comment_de     String
  obj_comment_en     String
  obj_d              Int                        @default(0)
  obj_date_de        String
  obj_date_en        String
  obj_depth          Float
  obj_desc_de        String
  obj_desc_en        String
  obj_diameter       Float
  obj_dimension      String
  obj_d_copy         Int
  obj_end_date       DateTime                   @default(dbgenerated())
  obj_head_de        String
  obj_head_en        String
  obj_height         Float
  obj_id             Int                        @default(autoincrement()) @id
  obj_img            String
  obj_marks          String
  obj_material_de    String
  obj_material_en    String?
  obj_newend_date    DateTime                   @default(dbgenerated())
  obj_newstart_date  DateTime                   @default(dbgenerated())
  obj_norm_taxed     hg_objects_obj_norm_taxed  @default(dbgenerated())
  obj_onoff          hg_objects_obj_onoff       @default(dbgenerated())
  obj_ordered        hg_objects_obj_ordered     @default(dbgenerated())
  obj_origin_de      String
  obj_origin_en      String
  obj_price          Float
  obj_price_raw      Float
  obj_s              Int
  obj_select         hg_objects_obj_select      @default(dbgenerated())
  obj_select_show    hg_objects_obj_select_show @default(dbgenerated())
  obj_sheight        Float
  obj_show_top       hg_objects_obj_show_top    @default(dbgenerated())
  obj_sort_dep       Int                        @default(0)
  obj_sort_highlight Int                        @default(0)
  obj_sort_select    Int                        @default(0)
  obj_vg_taxed       hg_objects_obj_vg_taxed    @default(dbgenerated())
  obj_weight         String
  obj_width          Float

  @@index([obj_head_de], name: "obj_head_de")
  @@index([obj_head_en], name: "obj_head_en")
  @@index([obj_onoff], name: "obj_onoff")
}

model hg_objects_alt {
  obj_add           Int                           @default(0)
  obj_artist_add    String
  obj_artist_id     Int                           @default(0)
  obj_artno         String                        @default("0")
  obj_auc           Int                           @default(0)
  obj_c             Int                           @default(0)
  obj_changed       DateTime                      @default(dbgenerated())
  obj_cms_user      Int                           @default(0)
  obj_comment_de    String
  obj_comment_en    String
  obj_d             Int                           @default(0)
  obj_date_de       String
  obj_date_en       String
  obj_desc_de       String
  obj_desc_en       String
  obj_dimension     String
  obj_end_date      DateTime                      @default(dbgenerated())
  obj_head_de       String
  obj_head_en       String
  obj_id            Int                           @default(autoincrement()) @id
  obj_img           String
  obj_marks         String
  obj_material_de   String
  obj_material_en   String?
  obj_newend_date   DateTime                      @default(dbgenerated())
  obj_newstart_date DateTime                      @default(dbgenerated())
  obj_norm_taxed    hg_objects_alt_obj_norm_taxed @default(dbgenerated())
  obj_onoff         hg_objects_alt_obj_onoff      @default(dbgenerated())
  obj_ordered       hg_objects_alt_obj_ordered    @default(dbgenerated())
  obj_origin_de     String
  obj_origin_en     String
  obj_price         Float
  obj_price_raw     Float
  obj_s             Int                           @default(0)
  obj_select        hg_objects_alt_obj_select     @default(dbgenerated())
  obj_select_big    hg_objects_alt_obj_select_big @default(dbgenerated())
  obj_show_top      hg_objects_alt_obj_show_top   @default(dbgenerated())
  obj_vg_taxed      hg_objects_alt_obj_vg_taxed   @default(dbgenerated())
  obj_weight        String

  @@index([obj_onoff], name: "obj_onoff")
}

model hg_objects_copy {
  obj_add           Int                            @default(0)
  obj_artist_add    String
  obj_artist_id     Int                            @default(0)
  obj_artno         String                         @default("0")
  obj_auc           Int                            @default(0)
  obj_c             Int
  obj_changed       DateTime                       @default(dbgenerated())
  obj_cms_user      Int                            @default(0)
  obj_comment_de    String
  obj_comment_en    String
  obj_d             Int                            @default(0)
  obj_date_de       String
  obj_date_en       String
  obj_desc_de       String
  obj_desc_en       String
  obj_dimension     String
  obj_d_copy        Int
  obj_end_date      DateTime                       @default(dbgenerated())
  obj_head_de       String
  obj_head_en       String
  obj_id            Int                            @default(autoincrement()) @id
  obj_img           String
  obj_marks         String
  obj_material_de   String
  obj_material_en   String?
  obj_newend_date   DateTime                       @default(dbgenerated())
  obj_newstart_date DateTime                       @default(dbgenerated())
  obj_norm_taxed    hg_objects_copy_obj_norm_taxed @default(dbgenerated())
  obj_onoff         hg_objects_copy_obj_onoff      @default(dbgenerated())
  obj_ordered       hg_objects_copy_obj_ordered    @default(dbgenerated())
  obj_origin_de     String
  obj_origin_en     String
  obj_price         Float
  obj_price_raw     Float
  obj_s             Int
  obj_select        hg_objects_copy_obj_select     @default(dbgenerated())
  obj_select_big    hg_objects_copy_obj_select_big @default(dbgenerated())
  obj_show_top      hg_objects_copy_obj_show_top   @default(dbgenerated())
  obj_vg_taxed      hg_objects_copy_obj_vg_taxed   @default(dbgenerated())
  obj_weight        String

  @@index([obj_head_de], name: "obj_head_de")
  @@index([obj_head_en], name: "obj_head_en")
  @@index([obj_onoff], name: "obj_onoff")
}

model hg_objects_dump {
  dump_id            Int                             @default(autoincrement()) @id
  obj_add            Int                             @default(0)
  obj_artist_add     String
  obj_artist_id      Int                             @default(0)
  obj_artno          String                          @default("0")
  obj_auc            Int                             @default(0)
  obj_auction_link   String
  obj_auction_title  String
  obj_c              Int
  obj_changed        DateTime                        @default(dbgenerated())
  obj_cms_user       Int                             @default(0)
  obj_comment_de     String
  obj_comment_en     String
  obj_d              Int                             @default(0)
  obj_date_de        String
  obj_date_en        String
  obj_depth          Float
  obj_desc_de        String
  obj_desc_en        String
  obj_diameter       Float
  obj_dimension      String
  obj_d_copy         Int
  obj_end_date       DateTime                        @default(dbgenerated())
  obj_head_de        String
  obj_head_en        String
  obj_height         Float
  obj_id             Int
  obj_img            String
  obj_marks          String
  obj_material_de    String
  obj_material_en    String?
  obj_newend_date    DateTime                        @default(dbgenerated())
  obj_newstart_date  DateTime                        @default(dbgenerated())
  obj_norm_taxed     hg_objects_dump_obj_norm_taxed  @default(dbgenerated())
  obj_onoff          hg_objects_dump_obj_onoff       @default(dbgenerated())
  obj_ordered        hg_objects_dump_obj_ordered     @default(dbgenerated())
  obj_origin_de      String
  obj_origin_en      String
  obj_price          Float
  obj_price_raw      Float
  obj_s              Int
  obj_select         hg_objects_dump_obj_select      @default(dbgenerated())
  obj_select_show    hg_objects_dump_obj_select_show @default(dbgenerated())
  obj_sheight        Float
  obj_show_top       hg_objects_dump_obj_show_top    @default(dbgenerated())
  obj_sort_dep       Int                             @default(0)
  obj_sort_highlight Int                             @default(0)
  obj_sort_select    Int                             @default(0)
  obj_vg_taxed       hg_objects_dump_obj_vg_taxed    @default(dbgenerated())
  obj_weight         String
  obj_width          Float
}

model hg_objects_org {
  obj_add           Int                           @default(0)
  obj_artist_add    String
  obj_artist_id     Int                           @default(0)
  obj_artno         String                        @default("0")
  obj_auc           Int                           @default(0)
  obj_changed       DateTime                      @default(dbgenerated())
  obj_cms_user      Int                           @default(0)
  obj_comment_de    String
  obj_comment_en    String
  obj_d             Int                           @default(0)
  obj_date_de       String
  obj_date_en       String
  obj_desc_de       String
  obj_desc_en       String
  obj_dimension     String
  obj_end_date      DateTime                      @default(dbgenerated())
  obj_head_de       String
  obj_head_en       String
  obj_id            Int                           @default(autoincrement()) @id
  obj_img           String
  obj_marks         String
  obj_material_de   String
  obj_material_en   String?
  obj_newend_date   DateTime                      @default(dbgenerated())
  obj_newstart_date DateTime                      @default(dbgenerated())
  obj_norm_taxed    hg_objects_org_obj_norm_taxed @default(dbgenerated())
  obj_onoff         hg_objects_org_obj_onoff      @default(dbgenerated())
  obj_ordered       hg_objects_org_obj_ordered    @default(dbgenerated())
  obj_origin_de     String
  obj_origin_en     String
  obj_price         Float
  obj_price_raw     Float
  obj_select        hg_objects_org_obj_select     @default(dbgenerated())
  obj_select_big    hg_objects_org_obj_select_big @default(dbgenerated())
  obj_show_top      hg_objects_org_obj_show_top   @default(dbgenerated())
  obj_vg_taxed      hg_objects_org_obj_vg_taxed   @default(dbgenerated())
  obj_weight        String

  @@index([obj_head_de], name: "obj_head_de")
  @@index([obj_head_en], name: "obj_head_en")
  @@index([obj_onoff], name: "obj_onoff")
}

model hg_objects_tmp {
  tmp_devid  Int @default(0)
  tmp_id     Int @default(autoincrement()) @id
  tmp_object Int @unique
  tmp_time   Int
  tmp_user   Int
}

model hg_orders {
  order_account_id  Int                  @default(0)
  order_address     String
  order_add_date    DateTime             @default(now())
  order_cms_user    Int                  @default(0)
  order_cookie      String               @default("")
  order_deliv_date  DateTime
  order_dev_address String
  order_id          Int                  @default(autoincrement()) @id
  order_ip          String               @default("0")
  order_no          Int
  order_object_id   Int                  @default(0)
  order_session     String               @default("0")
  order_sold        hg_orders_order_sold @default(dbgenerated())
  order_storno_date DateTime
}

model hg_sessions {
  session_id        String  @default("") @id
  session_ip        String  @default("0")
  session_logged_in Boolean @default(false)
  session_page      String  @default("0")
  session_start     Int     @default(0)
  session_time      Int     @default(0)
  session_user_id   Int     @default(0)
}

model hg_teaser {
  teaser_active      hg_teaser_teaser_active
  teaser_change_date DateTime                @default(now())
  teaser_cms_user    Int                     @default(0)
  teaser_config      String
  teaser_html        String
  teaser_id          Int                     @default(autoincrement()) @id
  teaser_name        String
}

model hg_user {
  cc_expdate_month      String                   @default("")
  cc_expdate_year       String                   @default("")
  // This type is currently not supported.
  // cc_length          binary
  // This type is currently not supported.
  // cc_number          binary
  cc_transnumber        String                   @default("")
  // This type is currently not supported.
  // cc_typ             binary
  user_active           hg_user_user_active      @default(dbgenerated())
  user_actkey           String?
  user_add              String?
  user_address_change   Int                      @default(0)
  user_add_date         Int                      @default(0)
  user_aged_proofed     Int                      @default(0)
  user_area_code        String?
  user_bank_account     String?
  user_bank_change      Int                      @default(0)
  user_bank_iban        String?
  user_bank_name        String?
  user_bank_swift       String?
  user_bank_tracing_no  String?
  user_bank_user_name   String?
  user_birthday         DateTime?                @default(dbgenerated())
  user_city             String?
  user_classification   String?
  user_cms_user         Int                      @default(0)
  user_company          String?
  user_country          String?
  user_country_abr      String?
  user_delivery_address Int                      @default(0)
  user_email            String?
  user_email2           String                   @default("")
  user_fax              String?
  user_firstname        String?
  user_high_bidder      hg_user_user_high_bidder @default(dbgenerated())
  user_id               Int                      @default(autoincrement()) @id
  user_int_info         String?
  user_language         hg_user_user_language    @default(de)
  user_lastname         String?
  user_lastvisit        Int?
  user_last_buy         Int                      @default(0)
  user_last_change      DateTime                 @default(now())
  user_last_login       Int                      @default(0)
  user_level            String?
  user_newsletter       String                   @default("")
  // This type is currently not supported.
  // user_password      binary?
  user_payment_level    Int?
  user_payment_pref     String?
  user_position         String                   @default("")
  user_profession       String?
  user_session_page     Int?
  user_session_time     Int?
  user_street           String?
  user_tax              String                   @default("")
  user_tel1             String?
  user_tel1_art         String?
  user_tel2             String?
  user_tel2_art         String?
  user_tel3             String?
  user_tel3_art         String?
  user_title            String?
  user_to               String?
  user_to_txt           String?
  user_www              String?                  @default("")

  @@index([user_lastname], name: "user_lastname")
}

model hg_user_tmp {
  user_add              Int                       @default(0)
  user_area_code        String?
  user_city             String?
  user_company          String?
  user_country          String?
  user_country_abr      String?
  user_delivery_address Int                       @default(0)
  user_email            String?
  user_fax              String?
  user_firstname        String?
  user_id               Int                       @default(autoincrement()) @id
  user_language         hg_user_tmp_user_language @default(de)
  user_lastname         String?
  user_street           String?
  user_tel1             String?
  user_tel2             String?
  user_title            String?
  user_to               String?
  user_to_txt           String?

  @@index([user_lastname], name: "user_lastname")
}

model hg_vg_art {
  vg_art_change_date DateTime @default(now())
  vg_art_cms_user    Int
  vg_art_id          Int      @default(0) @unique
  vg_art_max         Float    @default(0)
  vg_art_min         Float    @default(0)
  vg_art_name        String   @default("")
  vg_art_rate        Float    @default(0)
}

enum hg_artists_art_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_group_cms_group_hidden {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_group_cms_group_read {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_group_cms_group_read_limited {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_group_cms_group_write {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_group_cms_group_write_limited {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_cms_user_cms_group_id {
  // 1 @map("1")
  // 2 @map("2")
  // 3 @map("3")
  // 4 @map("4")
  // 5 @map("5")
  // 6 @map("6")
}

enum hg_cms_user_cms_user_contact {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_departments_dep_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_departments_alt_dep_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_departments_copy1_dep_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_departments_org_dep_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_events_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_fairs_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_norm_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_ordered {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_select {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_select_show {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_show_top {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_obj_vg_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_norm_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_ordered {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_select {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_select_big {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_show_top {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_alt_obj_vg_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_norm_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_ordered {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_select {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_select_big {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_show_top {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_copy_obj_vg_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_norm_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_ordered {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_select {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_select_show {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_show_top {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_dump_obj_vg_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_norm_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_onoff {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_ordered {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_select {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_select_big {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_show_top {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_objects_org_obj_vg_taxed {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_orders_order_sold {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_teaser_teaser_active {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_user_user_active {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_user_user_high_bidder {
  // 0 @map("0")
  // 1 @map("1")
}

enum hg_user_user_language {
  de
  en
  fr
  it
  ru
}

enum hg_user_tmp_user_language {
  de
  en
  fr
  it
  ru
}
```

**Comment by passionkind** [comment] 2020-06-05 12:45
sadly cannot share a reproduction repo here as the database contains customer data. All I did was creating the connector and setting up the repo and generation as described in the documentation

**Comment by passionkind** [comment] 2020-06-05 12:46
it's a mysql database (v 5.7.30-1) that I want to get rid of and spin up an api endpoint to ETL the data into another system

**Comment by passionkind** [comment] 2020-06-08 10:53
@pantharshit00 I fixed my issue. 

1. I removed those tables that had a binary column (didn't need them), which seems to not be supported yet by prisma
2. I converted all columns of enum type that hat numeric values into integer types, as prisma warns that enums must not start with a digit
3. I added primary keys to those tables that did not yet have a primary key
4. I queried for all columns that were either of type `date` or `timestamp` and checked if there was either the value `0000-00-00` for date or `0000-00-00 00:00:00` for timestamp. If so, replace it with `1980-01-01` or `1980-01-01 00:00:00` accordingly. I also tried allowing `null` and setting to `null` but prisma still panics as doesn't handle `null` value as undefined. 

Question: which value must a `date` or `timestamp` column have to be treated as undefined by prisma? That would be my preferred solution compared to setting it to the 80s.

Problem with the `date` and `timestamp` parsing seems to be that there was a different handling introduced somewhere around mysql 5.7 that does not allow `0000-00-00` or `0000-00-00 00:00:00` any longer as default values for `date` and `timestamp`. I would be able to work with sql statements if I'd set `--sql-mode=''` (or through a config file). But then prisma would still error as it cannot parse those _pseudo null_ values.

**Comment by pantharshit00** [comment] 2020-07-03 07:33
I think we treat the unix epoch as the starting point. @tomhoule or @pimeys will have more insight here.

**Comment by oleoneto** [comment] 2020-11-12 17:57
Not really a solution to the issue, more of a hack. You can skip the problematic column(s) in your select statement either by omission or by explicitly setting it to `false`:
```
prisma.users.findMany({
      select: {
        username: true,
        firstName: true,
        lastName: true,
        nullableOrSometimeInvalidField: false
      },
      where: {
        username: 'git',
      },
    }
```

**Comment by pantharshit00** [comment] 2021-01-13 19:32
@oleoneto If you are running into same issue, please open a new issue at https://github.com/prisma/prisma. We are going to achieve this repository soon. 

Since original issue was kind of fixed and we never got a reproduction here, I am going to close this.

**Closed by pantharshit00** 2021-01-13 19:32 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: basic reporting issue
