### ISSUE TITLE
All included 1:1 relations return null

### ISSUE THREAD

**Issue by andres-valdes** [prisma/prisma-client-js#477] opened 2020-02-09 19:57 UTC
Hi, I’m trying to query for a relation created with a nested create, but the returned model is null.

This is what it looks like `const user = await prisma.users.findOne({ where: { username }, include: { admin } });`

user is `{ ..., admin: null }`

In the database though, my relationships are all there. Am I using this wrong?

**Comment by andres-valdes** [comment] 2020-02-10 21:46
Fixed by using `@id @default(cuid())` instead of `@id @default(uuid())`

**Comment by pantharshit00** [comment] 2020-02-11 11:45
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #434

**Closed by pantharshit00** 2020-02-11 11:45 UTC
