### ISSUE TITLE
PrismaClientKnownRequestError. Null constraint violation on the fields: (`type_id`)

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/prisma-client-js#666] opened 2020-04-23 20:25 UTC
## Bug description

When I run the code below I get this error:

```
> ts-node ./script.ts

PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/Users/vadim/Projects/starter/script.ts:15:23

  11   }
  12 });
  13 
  14 // create a new user with local profile
→ 15 await prisma.user.create(Null constraint violation on the fields: (`type_id`)
    at PrismaClientFetcher.request (/Users/vadim/Projects/starter/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:640:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2011',
  meta: { constraint: [ 'type_id' ] }
}
```

## How to reproduce

schema.prisma
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String    @default(cuid()) @id
  login     String    @unique
  createdAt DateTime  @default(now()) @map("created_at")
  updatedAt DateTime  @map("updated_at") @updatedAt
  profiles  Profile[] @relation("_User_Profile")

  @@map("users")
}

model ProfileType {
  id          String    @default(cuid()) @id
  name        String    @unique
  description String?
  createdAt   DateTime  @default(now()) @map("created_at")
  updatedAt   DateTime  @map("updated_at") @updatedAt
  profiles    Profile[] @relation("_ProfileType_Profile")

  @@map("profile_types")
}

model Profile {
  id        String      @default(cuid()) @id
  typeId    String      @map("type_id")
  userId    String      @map("user_id")
  profileId String
  createdAt DateTime    @default(now()) @map("created_at")
  updatedAt DateTime    @map("updated_at") @updatedAt
  type      ProfileType @relation("_ProfileType_Profile", fields: [typeId], references: [id])
  user      User        @relation("_User_Profile", fields: [userId], references: [id])

  @@map("profiles")
  @@unique([typeId, profileId], name: "profileUnique")
}
```

script.ts
```
import { PrismaClient } from '@prisma/client'


async function main() {
  const prisma = new PrismaClient();
  try {
    // create a new profile type
    await prisma.profileType.create({
      data: {
        name: 'local'
      }
    });

    // create a new user with local profile
    await prisma.user.create({
      data: {
        login: 'user1',
        profiles: {
          create: {
            profileId: 'profile1',
            type: {
              connect: {
                name: 'local'
              }
            }
          }
        }
      }
    });
  } finally {
    await prisma.disconnect();
  }
}

main()
  .catch((err) => {
    console.error(err);
  });
```

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Prisma version: 2.0.0-beta.3
- Node.js version: 12.16.2

**Comment by pantharshit00** [comment] 2020-04-24 11:11
I can confirm this issue, for some reason, typeId is not being included in the `INSERT` query produced by the query engine.
![image](https://user-images.githubusercontent.com/22195362/80206502-10749880-864a-11ea-92c2-a964171b8031.png)


The version used for testing `2.0.0-alpha.1135` and `2.0.0-beta.3`

**Comment by pantharshit00** [comment] 2020-04-24 11:42
Fixed in `2.0.0-alpha.1136` via https://github.com/prisma/prisma-engines/commit/30c72503f68f53bb848c6f0b9a20bb95620be3de

Please test it out using `npm install @prisma/cli@alpha && npx prisma generate`

**Comment by RoyBkker** [comment] 2020-05-16 17:06
I have the same issue in a mutation where i want to connect to an id. 

schema: 
`
model Menu {
  id        Int          @default(autoincrement()) @id
  name      String
  company   Company      @relation(fields: [companyId], references: [id])
  companyId Int
  isActive  Boolean
  items     ItemOnMenu[]
}
`

AND 

`model ItemOnMenu {
  id          Int           @default(autoincrement()) @id
  item        Item          @relation(fields: [itemId], references: [id])
  itemId      Int
  ItemOnOrder ItemOnOrder[]
  course      String
  SoldOut     Boolean       @default(false)
  price       Float
  Menu        Menu          @relation(fields: [menuId], references: [id])
  menuId      Int
}`


My query is : 

`mutation createNewItemOnMenu(
  $item: String!
  $course: String!
  $price: Float!
  $priceEx: Float
  $btw: Float

) {
  createOneItemOnMenu(
    data: {
      item: { create: { name: $item } }
      course: $course
      price: $price
      priceEx: $priceEx
      btw: $btw
      Menu: {connect:{id: 60}}

    }
  ) {
    id
    item {
      name
    }
  }
}
`

Errors: 

`        "message": "\n\u001b[31mInvalid \u001b[1m`prisma.itemOnMenu.create()`\u001b[22m invocation in\u001b[39m\n\u001b[31m\u001b[4m/Users/roy/Workspace/horeca/backend/node_modules/nexus-prisma/dist/builder.js:180:97\u001b[24m\u001b[39m\n\n\u001b[2m  \u001b[90m176 \u001b[39m        \u001b[38;2;107;139;140m}\u001b[39m\u001b[38;2;107;139;140m,\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m177 \u001b[39m        locallyComputedInputs\u001b[38;2;107;139;140m:\u001b[39m publisherConfig\u001b[38;2;107;139;140m.\u001b[39mlocallyComputedInputs\u001b[38;2;107;139;140m,\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m178 \u001b[39m    \u001b[38;2;107;139;140m}\u001b[39m\u001b[38;2;107;139;140m)\u001b[39m\u001b[38;2;107;139;140m;\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m179 \u001b[39m\u001b[38;2;107;139;140m}\u001b[39m\u001b[22m\n\u001b[31m\u001b[1m→\u001b[22m\u001b[39m \u001b[2m\u001b[90m180 \u001b[39m\u001b[36mreturn\u001b[39m photon\u001b[38;2;107;139;140m[\u001b[39mmappedField\u001b[38;2;107;139;140m.\u001b[39mphotonAccessor\u001b[38;2;107;139;140m]\u001b[39m\u001b[38;2;107;139;140m[\u001b[39mmappedField\u001b[38;2;107;139;140m.\u001b[39moperation\u001b[38;2;107;139;140m]\u001b[39m\u001b[38;2;107;139;140m(\u001b[39margs\u001b[38;2;107;139;140m)\u001b[39m\u001b[22m\n\nNull constraint violation on the fields: (`id`)",`

**Comment by pantharshit00** [comment] 2020-05-16 21:13
@RoyBkker Please open a new issue with proper reproduction, Thanks!

I am also closing this one due to inactivity from the OP as we have already fixed the issue described here.

**Closed by pantharshit00** 2020-05-16 21:13 UTC
Labels: bug/2-confirmed, kind/regression
