### ISSUE TITLE
Empty array for "disconnect" leads to error

### ISSUE THREAD

**Issue by eWert-Online** [prisma/prisma-client-js#377] opened 2020-01-03 17:03 UTC
I am getting an error in Photon when trying to execute the following update: 

**Update:**
```
ctx.photon.projects.update({
  where: {
    id,
  },
  data: {
    title,
    members: {
      connect: [],
      disconnect:[],
    },
  },
});
```

**Error:**
```
InterpretationError("Error for binding '3': RecordsNotConnected { 
  relation_name: "ProjectMembers", 
  parent_name: "Project", 
  child_name: "User" 
}
```

The problem is the `disconnect: []`. Even though an empty array is working with `connect` it doesn't work for `disconnect`.

When I am changing it to `disconnect: undefined`, it is working.

Is this behaviour intendet?

**Comment by pantharshit00** [comment] 2020-03-19 09:50
@eWert-Online Hey, I marked this a confirmed bug but I didn't write an answer to your question here, sorry about that.

This is not an intended behaviour as you should be able to remove all disconnections. That is why I marked this as a confirmed bug,

**Comment by timsuchanek** [comment] 2020-11-25 11:55
This issue has already been fixed a while ago. If you still face it, let us know and we reopen it.

**Closed by timsuchanek** 2020-11-25 11:55 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action
