### ISSUE TITLE
AWS LAMBDA - Invalid `photon.() EROFS: read-only file system, chmod '/var/task/.../query-engine-rhel-openssl-1.0.x'

### ISSUE THREAD

**Issue by simonobe** [prisma/prisma-client-js#445] opened 2020-01-27 15:57 UTC
I am trying to use photon within my aws lambda functions. I am bundling the generated photon package within my node_modules. In my lambda code, I am initializing my Photon client using this function, in order to determine database during runtime:
```typescript
import { Photon } from '@prisma/photon';

export const getPhoton = (prismaDbUrl: string): Photon =>
  new Photon({
    datasources: {
      db: prismaDbUrl
    }
  });
```
However I receive an error when I try to query database using photon. Below is result of my lambda function
```
{
  "errorType": "Error",
  "errorMessage": "\nInvalid `photon.()` invocation in /var/task/node_modules/@prisma/photon/index.js:2159:44\n\n\n\nEROFS: read-only file system, chmod '/var/task/node_modules/@prisma/photon/runtime/query-engine-rhel-openssl-1.0.x'",
  "trace": [
    "Error: ",
    "Invalid `photon.()` invocation in /var/task/node_modules/@prisma/photon/index.js:2159:44",
    "",
    "",
    "",
    "EROFS: read-only file system, chmod '/var/task/node_modules/@prisma/photon/runtime/query-engine-rhel-openssl-1.0.x'",
    "    at PhotonFetcher.<anonymous> (/var/task/node_modules/@prisma/photon/index.js:63:31)",
    "    at Generator.throw (<anonymous>)",
    "    at rejected (/var/task/node_modules/@prisma/photon/index.js:6:65)"
  ]
}
```
It is not possible to run chmod within aws lambda (except in /tmp). The real question however is: **Why does photon need to run chmod in the first place?**
I have inspected the generated photon package a bit, but I still cannot figure out, why does photon need to run `chmod` on the query engine, or how to solve this problem. 
### Prisma2 version: 
2.0.0-preview019
### Photon version:
2.0.0-preview019

Note: I am unable to upgrade to the newest version, since I am also using nexus-prisma plugin

**Comment by pantharshit00** [comment] 2020-01-28 17:34
Related issue: https://github.com/prisma/prisma2/issues/1170

Just to make sure can you please confirm that you are not deploying to lambda via zeit.co and it is a direct deployment.

**Comment by simonobe** [comment] 2020-01-28 17:46
> Related issue: [prisma/prisma2#1170](https://github.com/prisma/prisma2/issues/1170)
> 
> Just to make sure can you please confirm that you are not deploying to lambda via zeit.co and it is a direct deployment.

Yep direct deployment. I am using serverless framework to deploy

**Comment by pantharshit00** [comment] 2020-01-30 13:51
@simonobe Can you please share you serverless.yml file 🙏 ?

**Comment by pantharshit00** [comment] 2020-01-30 13:52
Related: https://github.com/prisma/prisma2/issues/1383

**Comment by simonobe** [comment] 2020-02-03 08:08
> @simonobe Can you please share your serverless.yml file 🙏 ?

sorry did not see this comment before. I can share you some parts, but probably not all of it. Can you please tell me, which part of serverless config you would like to see? Moreover, I do not see how `serverless.yml` is of any relevance. I can tell you how we bundle our code, as that seems more relevant to me.
We are using webpack to bundle our code. 
However each time we rebuild with webpack, we are also rebuilding node externals. That means that after webpack builds our package (but before we zip it), we reinitialize the photon package (without 'native' binary target, since this would only bloat the package - btw the package is over 100MB, can something be done to reduce that?). 

In order to execute reinitialization of the photon package, we use our custom serverless plugin to hook into the process of package building. 

Nevertheless, if we look at the error, it is clear to see where the problem is. AWS Lambda environment does not allow to execute `chmod` command, which alters /var/task directory, which is exactly what PhotonFetcher seems to be doing. Can you please help me understand, why does `chmod` needs to be executed in the first place?

**Comment by pantharshit00** [comment] 2020-02-03 11:11
Yeah, I asked for it because I wanted to know if there are any build steps as you have mentioned.

Now can you please share the generator section of your schema. I want to see what you have in your binaryTargets property, either it is specified or not

**Comment by simonobe** [comment] 2020-02-03 11:42
> Yeah, I asked for it because I wanted to know if there are any build steps as you have mentioned.
> 
> Now can you please share the generator section of your schema. I want to see what you have in your binaryTargets property, either it is specified or not

this is the generator from schema I use
```prisma
generator photon {
  provider      = "photonjs"
  binaryTargets = [ "rhel-openssl-1.0.x"]
  output = "build/serverless/service/node_modules/@prisma/photon"
}
```

**Comment by simonobe** [comment] 2020-02-06 11:24
@pantharshit00  were you able to go through the issue?
generally speaking are there any people who are succesfuly using photon on AWS?

**Comment by janpio** [comment] 2020-02-10 15:01
This is being caused by building locally with `output` on Windows, then uploading to run on a Linux environment: https://github.com/prisma/prisma-client-js/issues/476

**Comment by pantharshit00** [comment] 2020-02-11 11:44
Maybe we can close this in favour of #476 as we have identified the problem there. 

cc @janpio

**Comment by janpio** [comment] 2020-02-11 16:04
Done, and linked to this issue as "more information".

**Closed** 2020-02-11 16:03 UTC
Labels: bug/0-needs-info, kind/bug, topic: windows
