### ISSUE TITLE
Allow @prisma/client to accept null values

### ISSUE THREAD

**Issue by MikaStark** [prisma/prisma-client-js#712] opened 2020-06-03 09:46 UTC
Hi everyone !
First of all, thanks a lot for your amazing work on Prisma. I want to point a little issue on Typescript, when you try to use prisma client with Graphql-yoga and @nexus/schema resolvers args may be null (it seems :/) and so, when you try pass that args directly to prisma client the linter throw a type error.

Here an example from my Query definition

```typescript
t.field('sitesCount', {
  type: 'Int',
  args: {
    where: 'SiteWhereInput',
  },
  resolve: (parent, { where }, { prisma }) => {
    return prisma.site.count({ where }); // <--- Cannot assign type 'null' to type 'SiteWhereInput | undefined'
  },
});
```
So could be possible to @prisma/client to handle null values ? (just like undefined values)

Here is my package dependencies :

```json
"dependencies": {
  "@nexus/schema": "^0.13.1",
  "@prisma/client": "^2.0.0-beta.7",
  "bcryptjs": "2.4.3",
  "graphql": "^14.6.0",
  "graphql-shield": "^5.7.3",
  "graphql-yoga": "^1.18.3",
  "jsonwebtoken": "^8.5.1",
  "nexus-prisma": "^0.13.0",
  "request": "^2.88.2",
  "request-promise": "^4.2.5"
},
"devDependencies": {
  "@prisma/cli": "^2.0.0-beta.7",
  "@types/bcryptjs": "^2.4.2",
  "@types/jsonwebtoken": "^8.5.0",
  "@types/request-promise": "^4.1.45",
  "@typescript-eslint/eslint-plugin": "^3.1.0",
  "@typescript-eslint/parser": "^3.1.0",
  "eslint": "^7.1.0",
  "eslint-config-prettier": "^6.11.0",
  "eslint-plugin-prettier": "^3.1.3",
  "prettier": "^2.0.5",
  "ts-node": "^8.10.2",
  "ts-node-dev": "^1.0.0-pre.44",
  "typescript": "^3.9.3"
},
```

**Comment by MikaStark** [comment] 2020-06-03 14:39
Thanks for the answer but the workaround seems to not work because of string filter (`cannot associate 'null' to type 'string | StringFilter | undefined`). The issue is the same as before but in deeper level and it may happen again with other params.

For now, I will use a `as any` workaround.

**Comment by timsuchanek** [comment] 2020-11-11 10:34
We are intentionally not accepting `null` as it has a different semantic meaning than `undefined`.
`undefined` means, that a value is not present, `null` means for Prisma Client, that a value should be set to an explicit `null`.
As this API works as intended, I'm closing this.
You can read more about it here: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined

**Closed by timsuchanek** 2020-11-11 10:34 UTC
Labels: kind/feature

**Comment by MikaStark** [comment] 2020-11-11 11:02
As this is not fully compatible with crud middleware (it is but with ugly as any workaround). I think it would be a good idea to set *strictNullCkecks* to *false* in tsconfig file.
