### ISSUE TITLE
PrismaClient Panic Bug with using multi-field ID ('@@id')

### ISSUE THREAD

**Issue by wwlee94** [prisma/prisma-client-js#710] opened 2020-06-01 04:05 UTC
## Bug description

<img width="853" alt="스크린샷 2020-05-31 오후 7 43 34" src="https://user-images.githubusercontent.com/38131683/83374522-d34cb480-a406-11ea-9c9f-f4338a7e9eab.png">

## How to reproduce

1. Request for testing prisma query by using `postman`

`prisma query`
```javascript
const res = await this.prisma.userItem.findOne({
  where: {
    itemId_userId: {
      itemId: id.userId,
      userId: currentUser.userId
    }
  }
});
return res
```
2. But, An error occured `Prisma Panic`
3. So, I'am using `findMany` as an alternative.
```javascript
const res = await this.prisma.userItem.findMany({
        where: {
          userId: currentUser.userId,
          itemId: id.itemId,
        }
});
return res[0]
```

## Expected behavior

1) Should be able to get data correctly by using multi-field ID

## Prisma information

`prisma.schema` 
```prisma
model UserItem {
  itemId      Int       
  userId      Int       
  createdAt   DateTime  @default(now())
  item        Item      @relation(fields: [itemId], references: [itemId])
  user        User      @relation(fields: [userId], references: [userId])
  @@id([itemId, userId])
}
```
## Environment & setup

- OS: [Mac OS]
- Database: [MySQL]
- Prisma version:
@prisma/cli          : 2.0.0-beta.4
Current platform     : darwin
- Node.js version: [v12.16.1]

**Comment by pantharshit00** [comment] 2020-06-05 00:44
I am unable to reproduce this with `2.0.0-beta.8`:

![image](https://user-images.githubusercontent.com/22195362/83824305-bdcfd700-a6f3-11ea-92d6-8f2833949a18.png)

Can you please try this again with the latest version? Thanks!

**Comment by janpio** [comment] 2020-09-02 02:18
Hey @wwlee94 , could you have another look at this after @pantharshit00 could not reproduce this? With a newer Prisma version this should definitely not happen any more. If you can not reproduce this, we would like to close the issue (or you can do that for us).

**Closed** 2020-09-03 13:17 UTC
Labels: bug/0-needs-info, kind/bug, topic: composite keys
