### ISSUE TITLE
Yarn 2 and Prisma Client break

### ISSUE THREAD

**Issue by TheGrimSilence** [prisma/prisma-client-js#819] opened 2020-08-10 05:32 UTC
## Bug description

When using Yarn 2 with Prisma, `yarn prisma generate` creates `node_modules/.prisma/client` but Yarn 2 uses PnP which removes `node_modules` in favor of their own cache stored in `.yarn/cache`. Prisma Client however generated the new client inside of `node_modules`. TypeScript therefore cannot see the newly generated client and neither can Prisma. 

**Workaround**

You can set `yarn config set nodeLinker node-modules` to use the old `node_modules` system.

**Caveat**

This breaks the Yarn flow alongside the Zero-Install workflow, bringing back the bloated `node_modules` folder. This also means that Yarn 2 Workspaces cannot be used since Yarn resolves to a project-root `node_modules`, whereas Prisma throws the new client into a project-local `node_modules`. You end up with the following structure.

```
node_modules/
  - .prisma/
    - client/
      - index.js
      - index.d.ts
projects/
  - server/
    - node_modules/
      - .prisma/
        - client/
          - index.js
          - index.d.ts
          - package.json
          - schema.prisma
    - postgres/
    - prisma/
    - sources/
      - index.ts
    - package.json
.yarnrc.yml
.pnp.js
```

## Proposed fix

Taking from what another issue from last year had proposed regarding Photon, I think the best solution would be to use a project-local `.prisma/` so that it becomes compatible with both Yarn 2's PnP and Workspaces. Effectively allowing multiple workspaces in the same repository to use different clients and schemas. This would be a form of future-proofing a best-case-scenario.

## Environment & setup

- OS: Windows 10 (2004) -> WSL 2
- Database: PostgresQL
- Node.js version: latest
- Prisma version: latest

**Comment by matthewmueller** [comment] 2020-08-11 10:23
Duplicate of https://github.com/prisma/prisma/issues/1439

**Closed by matthewmueller** 2020-08-11 10:23 UTC
