### ISSUE TITLE
Multiple quick `count` requests result in `Invalid prisma.web_hooks.count invocation`

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma-client-js#670] opened 2020-04-27 14:23 UTC
## Bug description

After introspecting our Discourse database (credentials on 1Password), and running Studio, Studio crashes. I ran the faulty query in a separate script and that crashes too, so I might have found a Prisma Client issue.

## How to reproduce

1. Introspect our Discourse DB (credentials on 1Password)
2. Generate client, create a TS script with content:

<details>
  <summary>Expand</summary>
  
  ```typescript
    import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const main = async () => {
  await Promise.all([
    prisma.anonymous_users.count(),
    prisma.api_keys.count(),
    prisma.application_requests.count(),
    prisma.ar_internal_metadata.count(),
    prisma.backup_draft_posts.count(),
    prisma.backup_draft_topics.count(),
    prisma.backup_metadata.count(),
    prisma.badge_groupings.count(),
    prisma.badges.count(),
    prisma.badge_types.count(),
    prisma.bookmarks.count(),
    prisma.categories.count(),
    prisma.categories_web_hooks.count(),
    prisma.category_custom_fields.count(),
    prisma.category_featured_topics.count(),
    prisma.category_groups.count(),
    prisma.category_search_data.count(),
    prisma.category_tag_groups.count(),
    prisma.category_tags.count(),
    prisma.category_tag_stats.count(),
    prisma.category_users.count(),
    prisma.child_themes.count(),
    prisma.color_scheme_colors.count(),
    prisma.color_schemes.count(),
    prisma.custom_emojis.count(),
    prisma.developers.count(),
    prisma.directory_items.count(),
    prisma.drafts.count(),
    prisma.draft_sequences.count(),
    prisma.email_change_requests.count(),
    prisma.email_logs.count(),
    prisma.email_tokens.count(),
    prisma.embeddable_hosts.count(),
    prisma.github_user_infos.count(),
    prisma.given_daily_likes.count(),
    prisma.group_archived_messages.count(),
    prisma.group_custom_fields.count(),
    prisma.group_histories.count(),
    prisma.group_mentions.count(),
    prisma.group_requests.count(),
    prisma.groups.count(),
    prisma.groups_web_hooks.count(),
    prisma.group_users.count(),
    prisma.ignored_users.count(),
    prisma.incoming_domains.count(),
    prisma.incoming_emails.count(),
    prisma.incoming_links.count(),
    prisma.incoming_referers.count(),
    prisma.invited_groups.count(),
    prisma.invites.count(),
    prisma.javascript_caches.count(),
    prisma.message_bus.count(),
    prisma.muted_users.count(),
    prisma.notifications.count(),
    prisma.oauth2_user_infos.count(),
    prisma.onceoff_logs.count(),
    prisma.optimized_images.count(),
    prisma.permalinks.count(),
    prisma.plugin_store_rows.count(),
    prisma.poll_options.count(),
    prisma.polls.count(),
    prisma.poll_votes.count(),
    prisma.post_actions.count(),
    prisma.post_action_types.count(),
    prisma.post_custom_fields.count(),
    prisma.post_details.count(),
    prisma.post_replies.count(),
    prisma.post_reply_keys.count(),
    prisma.post_revisions.count(),
    prisma.posts.count(),
    prisma.post_search_data.count(),
    prisma.post_stats.count(),
    prisma.post_timings.count(),
    prisma.post_uploads.count(),
    prisma.published_pages.count(),
    prisma.push_subscriptions.count(),
    prisma.quoted_posts.count(),
    prisma.remote_themes.count(),
    prisma.reviewable_claimed_topics.count(),
    prisma.reviewable_histories.count(),
    prisma.reviewables.count(),
    prisma.reviewable_scores.count(),
    prisma.scheduler_stats.count(),
    prisma.schema_migration_details.count(),
    prisma.schema_migrations.count(),
    prisma.screened_emails.count(),
    prisma.screened_ip_addresses.count(),
    prisma.screened_urls.count(),
    prisma.search_logs.count(),
    prisma.shared_drafts.count(),
    prisma.single_sign_on_records.count(),
    prisma.site_settings.count(),
    prisma.skipped_email_logs.count(),
    prisma.stylesheet_cache.count(),
    prisma.tag_group_memberships.count(),
    prisma.tag_group_permissions.count(),
    prisma.tag_groups.count(),
    prisma.tags.count(),
    prisma.tag_search_data.count(),
    prisma.tags_web_hooks.count(),
    prisma.tag_users.count(),
    prisma.theme_fields.count(),
    prisma.theme_modifier_sets.count(),
    prisma.themes.count(),
    prisma.theme_settings.count(),
    prisma.theme_translation_overrides.count(),
    prisma.topic_allowed_groups.count(),
    prisma.topic_allowed_users.count(),
    prisma.topic_custom_fields.count(),
    prisma.topic_embeds.count(),
    prisma.topic_groups.count(),
    prisma.topic_invites.count(),
    prisma.topic_link_clicks.count(),
    prisma.topic_links.count(),
    prisma.topics.count(),
    prisma.topic_search_data.count(),
    prisma.topic_tags.count(),
    prisma.topic_timers.count(),
    prisma.topic_users.count(),
    prisma.topic_views.count(),
    prisma.top_topics.count(),
    prisma.translation_overrides.count(),
    prisma.unsubscribe_keys.count(),
    prisma.uploads.count(),
    prisma.user_actions.count(),
    prisma.user_api_keys.count(),
    prisma.user_archived_messages.count(),
    prisma.user_associated_accounts.count(),
    prisma.user_auth_token_logs.count(),
    prisma.user_auth_tokens.count(),
    prisma.user_avatars.count(),
    prisma.user_badges.count(),
    prisma.user_custom_fields.count(),
    prisma.user_emails.count(),
    prisma.user_exports.count(),
    prisma.user_field_options.count(),
    prisma.user_fields.count(),
    prisma.user_histories.count(),
    prisma.user_open_ids.count(),
    prisma.user_options.count(),
    prisma.user_profiles.count(),
    prisma.user_profile_views.count(),
    prisma.users.count(),
    prisma.user_search_data.count(),
    prisma.user_second_factors.count(),
    prisma.user_security_keys.count(),
    prisma.user_stats.count(),
    prisma.user_uploads.count(),
    prisma.user_visits.count(),
    prisma.user_warnings.count(),
    prisma.watched_words.count(),
    prisma.web_crawler_requests.count(),
    prisma.web_hook_events.count(),
    prisma.web_hook_event_types.count(),
    prisma.web_hook_event_types_hooks.count(),
    prisma.web_hooks.count(),
  ])
}

main()
  .catch(async (e) => {
    console.log(e)
  })
  .finally(async () => {
    await prisma.disconnect()
  })

  ```
</details>

3. Run script using `ts-node index.ts`.
4. You should see this error:
```
PrismaClientUnknownRequestError:
Invalid `prisma.web_hooks.count()` invocation in
/Users/siddhant/Code/Tests/experiments/index.ts:163:22

  159 prisma.web_crawler_requests.count(),
  160 prisma.web_hook_events.count(),
  161 prisma.web_hook_event_types.count(),
  162 prisma.web_hook_event_types_hooks.count(),
→ 163 prisma.web_hooks.count()

PANIC: Unable to resolve a primary identifier for model poll_votes.
    at PrismaClientFetcher.message (/Users/siddhant/Code/Tests/experiments/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:642:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error in Prisma Client:
PANIC: Unable to resolve a primary identifier for model poll_votes. in
libs/prisma-models/src/model.rs:94:30

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
```

If you try running the reported failing query individually (`prisma.web_hooks.count()`), then everything's fine, so I'm assuming this only occurs when there are a bunch of queries run at the same time (I might be wrong though)

Note that this exact query is what is sent out from Studio, which causes it to crash.

Running this with DEBUG=* spits out a bunch of errors (they're a bit too long to paste in here, but you should be able to see them yourself if this script crashes for you too)

Since these credentials are sensitive, I cannot create a reproduction repo, but I can send over an archive on Slack if needed.

## Expected behavior

No crash.

## Prisma information

Same as above

## Environment & setup

- OS: macOS
- Database: Postgres
- Prisma version: 
```
@prisma/cli          : 2.0.0-alpha.1142
Current platform     : darwin
Query Engine         : query-engine 7120ecb512fc5ebe187a8cfc7b5d650bb51f7271
Migration Engine     : migration-engine-cli 7120ecb512fc5ebe187a8cfc7b5d650bb51f7271
Introspection Engine : introspection-core 7120ecb512fc5ebe187a8cfc7b5d650bb51f7271
```
- Node.js version: v13.10.1

**Comment by pantharshit00** [comment] 2020-04-29 09:30
I am able to reproduce this issue: 
![image](https://user-images.githubusercontent.com/22195362/80581009-1d1e3580-8a2a-11ea-98c5-ce8605b4a7b8.png)

**Comment by madebysid** [comment] 2020-04-30 21:45
@mavilein I thought so too, but the problem is that this only happens when you send a bunch of queries together. If you query *only* the `poll_votes` table using `prisma.poll_votes.count()`, then everything's fine. So maybe this is something else?

FWIW, here's the `poll_votes` model:
```
model poll_votes {
  created_at     DateTime
  poll_id        Int?
  poll_option_id Int?
  updated_at     DateTime
  user_id        Int?
  polls          polls?        @relation(fields: [poll_id], references: [id])
  poll_options   poll_options? @relation(fields: [poll_option_id], references: [id])
  users          users?        @relation(fields: [user_id], references: [id])

  @@index([poll_id], name: "index_poll_votes_on_poll_id")
  @@index([poll_option_id], name: "index_poll_votes_on_poll_option_id")
  @@index([user_id], name: "index_poll_votes_on_user_id")
  @@unique([poll_id, poll_option_id, user_id], name: "index_poll_votes_on_poll_id_and_poll_option_id_and_user_id")
}
```

**Comment by dpetrick** [comment] 2020-05-04 17:20
This issue is pretty wild just looking at it, let's break it down:

1) The model `poll_votes` is not a valid Prisma model. The unique constraint is insufficient as a primary ID, as it can contain null values. Introspection should not allow the model to pass and the DM parser should probably raise a flag as well.

2) With the above out of the way, I was wondering how on earth the `prisma.poll_votes.count()` ever succeeded. Turns out it doesn't: A pure GQL query against the engine produces the expected result:
```
thread 'tokio-runtime-worker' panicked at 'Unable to resolve a primary identifier for model poll_votes.', libs/prisma-models/src/model.rs:94:30
```

The plot thickens. Can you please confirm that the underlying GQL query generated by the client is indeed of the shape (or close to): 
```graphql
query {
  aggregatepoll_votes {
    count
  }
}
```

**Comment by madebysid** [comment] 2020-05-05 11:55
@dpetrick So I tried running the `prisma.poll_votes.count()` query and it does fail in the way you expected:

```
PANIC: Unable to resolve a primary identifier for model poll_votes.
    at PrismaClientFetcher.message
```

The GraphQL query is also what you expect:
```graphql
 query {
   aggregatepoll_votes {
     count
   }
 }
```

Since I'm still able to reproduce this though, I think this might not be a query engine issue, but one with the JS client. Because I'm running all queries in a `Promise.all`, I think the line number reported in the original error is wrong. I think the `poll_votes` count query is the one that fails (expectedly), but the Client's error says that `prisma.web_hooks.count()` is the problematic one.

So to be clear, there might be two separate issues here:

1. Validation should fail at some point during Client generation / introspection
2. The line number reported in original error is probably wrong.

Would love it if someone can fact-check this though.

**Comment by madebysid** [comment] 2020-05-05 12:04
Just to verify my claims, I started commenting out some queries. If I get rid of `poll_votes`, `post_replies` and `topic_views` (they all share the same problem with the unique constraint as @dpetrick pointed out) from the `Promise.all` array, the script no longer seems to crash so I'm kinda convinced that the error message is wrong.

**Comment by mavilein** [comment] 2020-06-25 11:31
fixed in: https://github.com/prisma/prisma-engines/commit/2d9a7f4b25e09be395ebe8e9f1e44ae9678cdec6

**Closed by mavilein** 2020-06-25 11:31 UTC
Labels: bug/2-confirmed, kind/bug, process/next-milestone, team/engines, topic: broken query
