### ISSUE TITLE
Support for JSON/JSONB

### ISSUE THREAD

**Issue by newtack** [prisma/prisma-client-js#60] opened 2019-06-25 05:04 UTC
Does Prisma Client support these types? If not, what are the plans to support them going forward?

**Comment by matthewmueller** [comment] 2019-06-26 15:18
Hi @newtack! Yes, we definitely want to support these features in the near future.

**Comment by schickling** [comment] 2019-07-03 16:13
This is currently being specced out here: https://github.com/prisma/specs/issues/8

**Comment by AntoinedeChassey** [comment] 2020-01-21 09:12
Hi guys,
Has this feature been implemented?
Thanks.

**Comment by janpio** [comment] 2020-04-11 20:17
Closing this one as duplicate of https://github.com/prisma/prisma/issues/186 which has more rections <3

**Closed** 2020-04-11 20:17 UTC
Labels: kind/feature, team/engines, team/product, topic: types
