### ISSUE TITLE
Error: GraphQL error: DateTime cannot represent an invalid Unix timestamp

### ISSUE THREAD

**Issue by ryancwalsh** [prisma/prisma-client-js#682] opened 2020-05-06 18:34 UTC
## Bug description

I'm so new to RedwoodJs, GraphQL, Apollo, and Prisma that I'm not positive that I'm reporting this problem in the correct place, but I think so. Thanks for all of your impressive work. :-)

RedwoodJs seems to store timestamps as 13-digit integers (e.g. 1588608976714), which is presumably milliseconds.

But if I change from using `db.principle.findMany()` to using a *raw* query:

```
db.raw`SELECT p.id, p.title, p.description, p.createdAt, p.modifiedAt
    FROM principle p
   WHERE EXISTS (SELECT NULL
                   FROM _PrincipleToTag pt
                  WHERE pt.B IN (${tagIds.join(',')})
                    AND pt.A = p.id
               GROUP BY pt.A
                 HAVING COUNT(DISTINCT pt.B) = ${tagIds.length})`
```

I get this error:

`Error: GraphQL error: DateTime cannot represent an invalid Unix timestamp 1588538742876`

Am I doing something wrong?

I tried a `console.log` of the data returned by both `findMany` and the `raw` version.

`raw` shows results that have values like `createdAt: 1588538742876`, and `findMany`'s results include values like `createdAt: 2020-05-03T20:45:42.876Z`.

Thanks!

## How to reproduce

If what I've mentioned here so far isn't enough, I could work on sharing a repo (but I suspect I'm just confused about something basic).

## Expected behavior

I expected (maybe incorrectly?) that whatever feature has been translating 13-digit integer timestamps into `2020-05-03T20:45:42.876Z` format would be consistent between `raw` and `findMany`.

## Prisma information

If what I've mentioned here so far isn't enough, I could work on sharing a repo (but I suspect I'm just confused about something basic).

## Environment & setup

- OS: Windows 10
- Database: SQLite
- Prisma version: I guess Prisma 2 since I'm using RedwoodJs
- Node.js version: v12.12.0

**Comment by pantharshit00** [comment] 2020-05-16 21:33
Hi @ryancwalsh 

Sorry for a bit of a late response but can you please share your prisma schema so that I can try out that query. Thanks!

**Comment by ryancwalsh** [comment] 2020-05-16 23:08
@pantharshit00 Thanks for taking a look. The schema is here: https://stackoverflow.com/q/61583460/470749

**Comment by pantharshit00** [comment] 2020-05-19 17:21
Hi @ryancwalsh 

I am asking for your Prisma schema. In the linked stackoverflow post I can only find the SDL of your GraphQL server which is not something that I can use to bootstrap a database.

**Comment by ryancwalsh** [comment] 2020-05-19 18:04
@pantharshit00 Oh, sorry. I'll paste the `schema.prisma` here. Thanks for taking a look.

```
datasource DS {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGET")
}

model User {
  id         Int         @default(autoincrement()) @id
  principles Principle[]
  tags       Tag[]
  createdAt  DateTime    @default(now())
  modifiedAt DateTime    @default(now())
}

model Principle {
  id          Int      @default(autoincrement()) @id
  title       String
  description String?
  user        User     @relation(fields: [userId], references: [id])
  userId      Int
  tags        Tag[]    @relation(references: [id])
  createdAt   DateTime @default(now())
  modifiedAt  DateTime @default(now())
}

model Tag {
  id          Int         @default(autoincrement()) @id
  title       String
  description String?
  user        User        @relation(fields: [userId], references: [id])
  userId      Int
  principles  Principle[] @relation(references: [id])
  createdAt   DateTime    @default(now())
  modifiedAt  DateTime    @default(now())

  @@unique([userId, title], name: "unique_tag_title_per_user")
}
```

**Comment by pantharshit00** [comment] 2020-05-29 11:12
I am unable to reproduce this with version `2.0.0-alpha.1265`. Can you please also try again with alpha once

![image](https://user-images.githubusercontent.com/22195362/83253616-dfe4c900-a1ca-11ea-9df4-75143fbe15c9.png)


Here is the script that I tried the reproduction with:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient();
  let tagIds = [1];
  const data = await client.raw`SELECT p.id, p.title, p.description, p.createdAt, p.modifiedAt
    FROM principle p
   WHERE EXISTS (SELECT NULL
                   FROM _PrincipleToTag pt
                  WHERE pt.B IN (${tagIds.join(",")})
                    AND pt.A = p.id
               GROUP BY pt.A
                 HAVING COUNT(DISTINCT pt.B) = ${tagIds.length})`;
  console.log(data);

  client.disconnect();
}

main();
```

Database contents:
```sql 
-- -------------------------------------------------------------
-- TablePlus 3.5.3(314)
--
-- https://tableplus.com/
--
-- Database: dev.db
-- Generation Time: 2020-05-29 16:41:00.3630
-- -------------------------------------------------------------


DROP TABLE IF EXISTS "_Migration";
CREATE TABLE "_Migration" ("revision" INTEGER NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" DATE NOT NULL, "finished_at" DATE);

DROP TABLE IF EXISTS "_PrincipleToTag";
CREATE TABLE "_PrincipleToTag" (
"A" INTEGER NOT NULL  ,"B" INTEGER NOT NULL  ,FOREIGN KEY ("A") REFERENCES "Principle"("id") ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY ("B") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE);

DROP TABLE IF EXISTS "Principle";
CREATE TABLE "Principle" (
"createdAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,"description" TEXT   ,"id" INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,"modifiedAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,"title" TEXT NOT NULL  ,"userId" INTEGER NOT NULL  ,FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE);

DROP TABLE IF EXISTS "sqlite_sequence";
CREATE TABLE sqlite_sequence(name,seq);

DROP TABLE IF EXISTS "Tag";
CREATE TABLE "Tag" (
"createdAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,"description" TEXT   ,"id" INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,"modifiedAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,"title" TEXT NOT NULL  ,"userId" INTEGER NOT NULL  ,FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE);

DROP TABLE IF EXISTS "User";
CREATE TABLE "User" (
"createdAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,"id" INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,"modifiedAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP );

INSERT INTO "_Migration" ("revision", "name", "datamodel", "status", "applied", "rolled_back", "datamodel_steps", "database_migration", "errors", "started_at", "finished_at") VALUES
('1', '20200529162646', 'datasource DS {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id         Int         @default(autoincrement()) @id
  principles Principle[]
  tags       Tag[]
  createdAt  DateTime    @default(now())
  modifiedAt DateTime    @default(now())
}

model Principle {
  id          Int      @default(autoincrement()) @id
  title       String
  description String?
  user        User     @relation(fields: [userId], references: [id])
  userId      Int
  tags        Tag[]    @relation(references: [id])
  createdAt   DateTime @default(now())
  modifiedAt  DateTime @default(now())
}

model Tag {
  id          Int         @default(autoincrement()) @id
  title       String
  description String?
  user        User        @relation(fields: [userId], references: [id])
  userId      Int
  principles  Principle[] @relation(references: [id])
  createdAt   DateTime    @default(now())
  modifiedAt  DateTime    @default(now())

  @@unique([userId, title], name: "unique_tag_title_per_user")
}', 'MigrationSuccess', '13', '0', '[{"tag":"CreateSource","source":"DS"},{"tag":"CreateArgument","location":{"tag":"Source","source":"DS"},"argument":"provider","value":"\"sqlite\""},{"tag":"CreateArgument","location":{"tag":"Source","source":"DS"},"argument":"url","value":"env(\"DATABASE_URL\")"},{"tag":"CreateModel","model":"User"},{"tag":"CreateField","model":"User","field":"id","type":"Int","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"User","field":"id"},"directive":"default"},"argument":"","value":"autoincrement()"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"id"}},{"tag":"CreateField","model":"User","field":"principles","type":"Principle","arity":"List"},{"tag":"CreateField","model":"User","field":"tags","type":"Tag","arity":"List"},{"tag":"CreateField","model":"User","field":"createdAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"createdAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"User","field":"createdAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateField","model":"User","field":"modifiedAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"modifiedAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"User","field":"modifiedAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateModel","model":"Principle"},{"tag":"CreateField","model":"Principle","field":"id","type":"Int","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"id"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"id"},"directive":"default"},"argument":"","value":"autoincrement()"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"id"},"directive":"id"}},{"tag":"CreateField","model":"Principle","field":"title","type":"String","arity":"Required"},{"tag":"CreateField","model":"Principle","field":"description","type":"String","arity":"Optional"},{"tag":"CreateField","model":"Principle","field":"user","type":"User","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"user"},"directive":"relation"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"user"},"directive":"relation"},"argument":"fields","value":"[userId]"},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"user"},"directive":"relation"},"argument":"references","value":"[id]"},{"tag":"CreateField","model":"Principle","field":"userId","type":"Int","arity":"Required"},{"tag":"CreateField","model":"Principle","field":"tags","type":"Tag","arity":"List"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"tags"},"directive":"relation"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"tags"},"directive":"relation"},"argument":"references","value":"[id]"},{"tag":"CreateField","model":"Principle","field":"createdAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"createdAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"createdAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateField","model":"Principle","field":"modifiedAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Principle","field":"modifiedAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Principle","field":"modifiedAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateModel","model":"Tag"},{"tag":"CreateField","model":"Tag","field":"id","type":"Int","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"id"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"id"},"directive":"default"},"argument":"","value":"autoincrement()"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"id"},"directive":"id"}},{"tag":"CreateField","model":"Tag","field":"title","type":"String","arity":"Required"},{"tag":"CreateField","model":"Tag","field":"description","type":"String","arity":"Optional"},{"tag":"CreateField","model":"Tag","field":"user","type":"User","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"user"},"directive":"relation"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"user"},"directive":"relation"},"argument":"fields","value":"[userId]"},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"user"},"directive":"relation"},"argument":"references","value":"[id]"},{"tag":"CreateField","model":"Tag","field":"userId","type":"Int","arity":"Required"},{"tag":"CreateField","model":"Tag","field":"principles","type":"Principle","arity":"List"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"principles"},"directive":"relation"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"principles"},"directive":"relation"},"argument":"references","value":"[id]"},{"tag":"CreateField","model":"Tag","field":"createdAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"createdAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"createdAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateField","model":"Tag","field":"modifiedAt","type":"DateTime","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Tag","field":"modifiedAt"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Tag","field":"modifiedAt"},"directive":"default"},"argument":"","value":"now()"},{"tag":"CreateDirective","location":{"path":{"tag":"Model","model":"Tag","arguments":[{"name":"","value":"[userId, title]"},{"name":"name","value":"\"unique_tag_title_per_user\""}]},"directive":"unique"}}]', '{"before":{"tables":[{"name":"_Migration","columns":[{"name":"applied","tpe":{"dataType":"INTEGER","fullDataType":"INTEGER","family":"int","arity":"required"},"default":null,"autoIncrement":false},{"name":"database_migration","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"datamodel","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"datamodel_steps","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"errors","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"finished_at","tpe":{"dataType":"DATE","fullDataType":"DATE","family":"dateTime","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"name","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"revision","tpe":{"dataType":"INTEGER","fullDataType":"INTEGER","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"rolled_back","tpe":{"dataType":"INTEGER","fullDataType":"INTEGER","family":"int","arity":"required"},"default":null,"autoIncrement":false},{"name":"started_at","tpe":{"dataType":"DATE","fullDataType":"DATE","family":"dateTime","arity":"required"},"default":null,"autoIncrement":false},{"name":"status","tpe":{"dataType":"TEXT","fullDataType":"TEXT","family":"string","arity":"required"},"default":null,"autoIncrement":false}],"indices":[],"primaryKey":{"columns":["revision"],"sequence":null},"foreignKeys":[]}],"enums":[],"sequences":[]},"after":{"tables":[{"name":"User","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[]},{"name":"Principle","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]},{"name":"Tag","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"unique_tag_title_per_user","columns":["userId","title"],"tpe":"unique"}],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]},{"name":"_PrincipleToTag","columns":[{"name":"A","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false},{"name":"B","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"_PrincipleToTag_AB_unique","columns":["A","B"],"tpe":"unique"},{"name":"_PrincipleToTag_B_index","columns":["B"],"tpe":"normal"}],"primaryKey":null,"foreignKeys":[{"constraintName":null,"columns":["A"],"referencedTable":"Principle","referencedColumns":["id"],"onDeleteAction":"cascade"},{"constraintName":null,"columns":["B"],"referencedTable":"Tag","referencedColumns":["id"],"onDeleteAction":"cascade"}]}],"enums":[],"sequences":[]},"original_steps":[{"CreateTable":{"table":{"name":"User","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[]}}},{"CreateTable":{"table":{"name":"Principle","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateTable":{"table":{"name":"Tag","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"unique_tag_title_per_user","columns":["userId","title"],"tpe":"unique"}],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateTable":{"table":{"name":"_PrincipleToTag","columns":[{"name":"A","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false},{"name":"B","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"_PrincipleToTag_AB_unique","columns":["A","B"],"tpe":"unique"},{"name":"_PrincipleToTag_B_index","columns":["B"],"tpe":"normal"}],"primaryKey":null,"foreignKeys":[{"constraintName":null,"columns":["A"],"referencedTable":"Principle","referencedColumns":["id"],"onDeleteAction":"cascade"},{"constraintName":null,"columns":["B"],"referencedTable":"Tag","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateIndex":{"table":"Tag","index":{"name":"unique_tag_title_per_user","columns":["userId","title"],"tpe":"unique"}}},{"CreateIndex":{"table":"_PrincipleToTag","index":{"name":"_PrincipleToTag_AB_unique","columns":["A","B"],"tpe":"unique"}}},{"CreateIndex":{"table":"_PrincipleToTag","index":{"name":"_PrincipleToTag_B_index","columns":["B"],"tpe":"normal"}}},{"AddForeignKey":{"table":"Principle","foreign_key":{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"Tag","foreign_key":{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"_PrincipleToTag","foreign_key":{"constraintName":null,"columns":["A"],"referencedTable":"Principle","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"_PrincipleToTag","foreign_key":{"constraintName":null,"columns":["B"],"referencedTable":"Tag","referencedColumns":["id"],"onDeleteAction":"cascade"}}}],"corrected_steps":[{"RawSql":{"raw":"PRAGMA foreign_keys=OFF;"}},{"CreateTable":{"table":{"name":"User","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[]}}},{"CreateTable":{"table":{"name":"Principle","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateTable":{"table":{"name":"Tag","columns":[{"name":"createdAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"description","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"nullable"},"default":null,"autoIncrement":false},{"name":"id","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":true},{"name":"modifiedAt","tpe":{"dataType":"","fullDataType":"","family":"dateTime","arity":"required"},"default":"NOW","autoIncrement":false},{"name":"title","tpe":{"dataType":"","fullDataType":"","family":"string","arity":"required"},"default":null,"autoIncrement":false},{"name":"userId","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"unique_tag_title_per_user","columns":["userId","title"],"tpe":"unique"}],"primaryKey":{"columns":["id"],"sequence":null},"foreignKeys":[{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateTable":{"table":{"name":"_PrincipleToTag","columns":[{"name":"A","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false},{"name":"B","tpe":{"dataType":"","fullDataType":"","family":"int","arity":"required"},"default":null,"autoIncrement":false}],"indices":[{"name":"_PrincipleToTag_AB_unique","columns":["A","B"],"tpe":"unique"},{"name":"_PrincipleToTag_B_index","columns":["B"],"tpe":"normal"}],"primaryKey":null,"foreignKeys":[{"constraintName":null,"columns":["A"],"referencedTable":"Principle","referencedColumns":["id"],"onDeleteAction":"cascade"},{"constraintName":null,"columns":["B"],"referencedTable":"Tag","referencedColumns":["id"],"onDeleteAction":"cascade"}]}}},{"CreateIndex":{"table":"Tag","index":{"name":"unique_tag_title_per_user","columns":["userId","title"],"tpe":"unique"}}},{"CreateIndex":{"table":"_PrincipleToTag","index":{"name":"_PrincipleToTag_AB_unique","columns":["A","B"],"tpe":"unique"}}},{"CreateIndex":{"table":"_PrincipleToTag","index":{"name":"_PrincipleToTag_B_index","columns":["B"],"tpe":"normal"}}},{"AddForeignKey":{"table":"Principle","foreign_key":{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"Tag","foreign_key":{"constraintName":null,"columns":["userId"],"referencedTable":"User","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"_PrincipleToTag","foreign_key":{"constraintName":null,"columns":["A"],"referencedTable":"Principle","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"AddForeignKey":{"table":"_PrincipleToTag","foreign_key":{"constraintName":null,"columns":["B"],"referencedTable":"Tag","referencedColumns":["id"],"onDeleteAction":"cascade"}}},{"RawSql":{"raw":"PRAGMA \"quaint\".foreign_key_check;"}},{"RawSql":{"raw":"PRAGMA foreign_keys=ON;"}}],"rollback":[{"RawSql":{"raw":"PRAGMA foreign_keys=OFF;"}},{"DropTable":{"name":"User"}},{"DropTable":{"name":"Principle"}},{"DropTable":{"name":"Tag"}},{"DropTable":{"name":"_PrincipleToTag"}},{"RawSql":{"raw":"PRAGMA \"quaint\".foreign_key_check;"}},{"RawSql":{"raw":"PRAGMA foreign_keys=ON;"}}]}', '[]', '1590749810544', '1590749810561');

INSERT INTO "_PrincipleToTag" ("A", "B") VALUES
('1', '1');

INSERT INTO "Principle" ("createdAt", "description", "id", "modifiedAt", "title", "userId") VALUES
('1590750173019', NULL, '1', '1590750173019', 'principle', '1');

INSERT INTO "sqlite_sequence" ("name", "seq") VALUES
('Principle', '1'),
('Tag', '1'),
('User', '1');

INSERT INTO "Tag" ("createdAt", "description", "id", "modifiedAt", "title", "userId") VALUES
('1590750173019', NULL, '1', '1590750173019', 'test', '1');

INSERT INTO "User" ("createdAt", "id", "modifiedAt") VALUES
('1590750173019', '1', '1590750173019');

```

**Comment by ryancwalsh** [comment] 2020-07-04 14:21
@pantharshit00 I appreciate all of your effort on this and your patience with my lack of response until now. 

I had a moment to upgrade to 0.12.0 redwoodjs this morning, which in turn upgraded to `@prisma/client@^2.1.1`.

I then [noticed](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.8) that I needed to change my `.raw` queries to `.queryRaw`. So I did that.

Unfortunately I'm still getting "Error: GraphQL error: DateTime cannot represent an invalid Unix timestamp 1588538604797".

I have not tried creating a new project from scratch like you did in order to reproduce the problem. If you're comfortable that prisma-client-js does not have a bug, feel free to close this issue.

@cannikin provided me [a workaround here](https://github.com/redwoodjs/redwood/issues/513#issuecomment-625589424) which I think will be fine:
```
return records.map((principle) => {
    const createdAtDate = new Date(0)
    createdAtDate.setUTCSeconds(principle.createdAt / 1000)
    const modifiedAtDate = new Date(0)
    modifiedAtDate.setUTCSeconds(principle.modifiedAt / 1000)
    const momentsAsIso = {
      createdAt: createdAtDate.toISOString(),
      modifiedAt: modifiedAtDate.toISOString(),
    }
    console.log('momentsAsIso', momentsAsIso)
    return Object.assign(principle, momentsAsIso)
  })
```

Thank you so much for all of your hard work. :-)

**Comment by pantharshit00** [comment] 2020-07-14 15:00
Yes, it does look like you a case of JS timestamps being represented in ms while what we store in sqlite is in seconds. 

If you will use queryRaw here, we won't be able to do any conversions here so you will have to keep this mind.

So I am going to close this.

**Closed by pantharshit00** 2020-07-14 15:00 UTC
Labels: bug/0-needs-info, kind/bug, topic: raw, topic: redwoodjs
