### ISSUE TITLE
Allow access to raw value used as Foreign Key in a relation

### ISSUE THREAD

**Issue by robmurtagh** [prisma/prisma-client-js#333] opened 2019-09-26 11:14 UTC
The following is valid to Photon, but not to Lift:

```
model Foo {
  bar       Bar         @map("bar_uuid")
  barId     String      @map("bar_uuid")
}
```

If would be fantastic if either the above was allowed, or if `barId` could be autogenerated on the type `Foo`.

Making `barId` accessible significantly cleans the syntax for callers (and I think without `barId` the query engine may even implement joins or something similar under the covers).

For context because we are struggling with some Photon performance issues, we're using some manual workarounds. This backs out to us having many cases like `barId` in our schema but commenting and uncommenting the `barId` line depending on whether we're using `Photon`, or `Lift`.

**Comment by schickling** [comment] 2020-03-17 09:27
Closing this as a duplicate of #188. We're planning to look into this. Thanks a lot for bringing up this issue!

**Closed by schickling** 2020-03-17 09:27 UTC
Labels: kind/feature, process/product
