### ISSUE TITLE
Cannot query `findOne` with compound field

### ISSUE THREAD

**Issue by squirly** [prisma/prisma-client-js#674] opened 2020-05-01 20:49 UTC
## Bug description

When querying by a compound field, I am getting a panic in `prisma-engine`.

## How to reproduce

See below, will build minimal example based off of the provided schema when I am off work.

Error:
```
Invalid `prisma.cart.findOne()` invocation:

PANIC: called `Option::unwrap()` on a `None` value
```

Points to https://github.com/prisma/prisma-engines/blob/3cd2e8691906b5d6be11fe6e7e154f2a9928b6ff/query-engine/core/src/query_graph_builder/extractors/filters.rs#L279

## Expected behavior

Either fix the issue so that this works or give a clear error message with what the user has done wrong.

### Relevant prisma schema
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "../src/dbClient"
}

model Cart {
  @@map("cart")

  id         String    @id @default(cuid())
  createdAt  DateTime  @map("created_at") @default(now())
  updatedAt  DateTime  @map("updated_at") @updatedAt

  /// null to deactivate
  active                 Boolean?  @map("active")
  userId                 String    @map("user_id")
  consultantId    String         @map("consultant_id")

  @@unique([active, userId, consultantId])
}
```

### JS Call
```
const cart = await di.db.cart.findOne({
  where: {
    active_userId_consultantId: {
      active: true,
      userId: user.anonymousId,
      consultantId: consultant.id,
    },
  },
});
```

### Server Log
```
2020-05-01T20:20:37.039Z prisma-client Prisma Client call:
2020-05-01T20:20:37.039Z prisma-client prisma.cart.findOne({
  where: {
    active_userId_consultantId: {
      active: true,
      userId: '<userId>',
      consultantId: '<consultantID>'
    }
  }
})
2020-05-01T20:20:37.040Z prisma-client Generated request:
2020-05-01T20:20:37.040Z prisma-client query {
  findOneCart(where: {
    active_userId_consultantId: {
      active: true
      userId: "<userId>"
      consultantId: "<consultantId>"
    }
  }) {
    id
    <other fields here>
  }
}

2020-05-01T20:20:37.045Z engine stdout {
  timestamp: 'May 01 20:20:37.044',
  level: 'ERROR',
  target: 'query_engine',
  fields: {
    message: 'PANIC',
    reason: 'called `Option::unwrap()` on a `None` value',
    file: 'query-engine/core/src/query_graph_builder/extractors/filters.rs',
    line: 279,
    column: 35
  }
}
2020-05-01T20:20:37.055Z engine {
  error: Error: socket hang up
      at connResetException (internal/errors.js:604:14)
      at Socket.socketOnEnd (_http_client.js:460:23)
      at Socket.emit (events.js:323:22)
      at Socket.EventEmitter.emit (domain.js:482:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  }
}
2020-05-01T20:20:37.057Z printStack callsite Error
    at Object.s [as Cart] (/app/src/dbClient/runtime/index.js:1:82529)
    at Object.n.<computed> [as findOne] (/app/src/dbClient/runtime/index.js:1:84025)
    at cart (/app/src/graphql/resolvers/pws/resolvers.js:51:43)
    at field.resolve (/app/node_modules/graphql-extensions/dist/index.js:133:26)
    at resolveFieldValueOrError (/app/node_modules/graphql/execution/execute.js:467:18)
    at resolveField (/app/node_modules/graphql/execution/execute.js:434:16)
    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)
    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)
    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)
    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)
ERROR: 
Invalid `prisma.cart.findOne()` invocation:

PANIC: called `Option::unwrap()` on a `None` value {
  extra: { tokenId: '0072fcae-3681-48b3-bc1c-d524541a510b' },
  tags: {},
  user: { id: 'ck9doxent000o01s64qq6abas' }
}
```

## Environment & setup

- OS: Debian on Docker
- Database: PostgreSQL
- Prisma version: Introduced in `2.0.0-beta.3`, latest checked on `2.0.0-beta.4`
- Node.js version: 12.16.1

**Comment by icomad** [comment] 2020-05-02 12:08
I don't think the error is due to the field being compound but rather the fact that the field in the where clause is mapped, as in [Error on table update using a mapped field in where clause](https://github.com/prisma/prisma/issues/2329) and [Panic calling findOne with mapped unique key fields](https://github.com/prisma/prisma/issues/2353)

**Comment by pantharshit00** [comment] 2020-05-16 21:45
Sorry for the late response here. I can confirm this problem and it has been reported before here https://github.com/prisma/prisma/issues/2353 as pointed out by @icomad so I am going to close this as a duplicate.

**Closed by pantharshit00** 2020-05-16 21:45 UTC
