### ISSUE TITLE
Can't findOne, update, delete on composite primary keys

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-js#488] opened 2020-02-13 15:45 UTC
```sql
create table variables (
  name text not null,
  key text not null,
  value text not null,
  email text not null,
  primary key(name, key)
);
insert into variables (name, key, value, email) values ('a', 'b', 'c', 'd');
```

```ts
// typescript error
client.variables.findOne({ where: { variables_name_key_key: { key: 'b', name: 'a' } } })
client.variables.update({ where: { variables_name_key_key: { key: 'b', name: 'a' } } })
client.variables.delete({ where: { variables_name_key_key: { key: 'b', name: 'a' } } })
```

Related: https://github.com/prisma/prisma-client-js/issues/489

**Comment by janpio** [comment] 2020-02-14 16:54
Note: Reproduce again.

**Comment by pantharshit00** [comment] 2020-02-18 16:25
I can't reproduce this with `prisma2@2.0.0-alpha.797, binary version: f608db3b9e4f50f9a384356e532357b0a525969a`. Initially when I marked this as a confirmed bug I assumed that @matthewmueller referred to implementation that client will have `@@id`. Right now no such functionality is exposed via the client.

**Comment by janpio** [comment] 2020-03-19 00:33
Introspecting a Postgres DB that has the above SQL generates this schema:

```prisma
model variables {
  email String
  key   String
  name  String
  value String

  @@id([name, key])
}
```

Afterwards the following `index.ts` (I commented in and out the individual lines to run them one by one) works:

```ts
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient()

client.variables.create({ data: { name: 'a', key: 'b', email: 'mail@example.org', value: 'foo' } }).then(res => { console.log('create', res) })
client.variables.findOne({ where: { name_key: { key: 'b', name: 'a' } } }).then(res => { console.log('findOne', res) })
client.variables.update({ where: { name_key: { key: 'b', name: 'a' } }, data: { value: 'bar' } }).then(res => { console.log('update', res) })
client.variables.delete({ where: { name_key: { key: 'b', name: 'a' } } }).then(res => { console.log('delete', res) })
```

(prisma2@2.0.0-alpha.934)

Can you please confirm that this is the wanted behavior @matthewmueller?

**Closed by janpio** 2020-03-19 00:33 UTC
Labels: bug/0-needs-info, kind/bug, topic: AUMFIDARR

**Comment by dpankros** [comment] 2020-12-01 17:09
Can I request that composite keys be documented in the find/update/delete sections of the docs (or even a separate section that gives a _hint_ how it works)?  I was stuck on them for days and didn't think they worked properly because the schema was showing my where options as including something like `<key1>_<key2>`which didn't make sense to me and nothing I tried to supply there worked.  

Thanks to @janpio 's post, above, now I see how it works and I'm unstuck.  Documentation of this point would have saved a tremendous amount of time.

**Comment by nikolasburk** [comment] 2020-12-02 09:26
Hey @dpankros 👋 yes, I just created an issue in the `docs` repo to persist this, our docs team will look into this soon! 🙏
