### ISSUE TITLE
Bug: Aggregations API: "Type 'string' is not assignable to type 'never'"

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma-client-js#768] opened 2020-07-07 20:50 UTC
# Bug description

The Aggregations API is inconsistent when filtering records on related models. `id` in this case shouldn't be `never` but `string | StringFilter`.

<img width="583" alt="Screenshot 2020-07-07 at 22 41 08" src="https://user-images.githubusercontent.com/3816295/86840430-f8d27b00-c0a2-11ea-8070-16c033af1d41.png">

## How to reproduce

Have a schema consisting of a `Task` having a relation to a `Workspace` (both have an `id` field being a `cuid()` generated `String`) and aggregate like in the image above.

## Expected behavior

The `count` API currently consists of the expected behavior.

<img width="531" alt="Screenshot 2020-07-07 at 22 39 30" src="https://user-images.githubusercontent.com/3816295/86840212-c45ebf00-c0a2-11ea-92df-e5d6123e2c2e.png">

## Environment & setup

Using Nest.js. `PrismaService` (`this.prismaService`) extends the generated `PrismaClient`.

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.18.1
- Prisma version:

```
$ npx prisma -v
Environment variables loaded from current directory
@prisma/cli          : 2.2.0
Current platform     : darwin
Query Engine         : query-engine 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/.../node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/.../node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/.../node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /Users/.../node_modules/@prisma/cli/prisma-fmt-darwin)
```

**Comment by pantharshit00** [comment] 2020-07-10 11:25
This might be related to https://github.com/prisma/prisma/issues/2959 since there are no typing being generated for where.

**Comment by pantharshit00** [comment] 2021-01-13 19:41
I can confirm this is fixed in the latest version.

**Closed by pantharshit00** 2021-01-13 19:41 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/client, tech/typescript, topic: aggregateApi
