### ISSUE TITLE
PANIC: `NaiveDateTime + Duration` overflowed

### ISSUE THREAD

**Issue by defrex** [prisma/prisma-client-js#851] opened 2020-08-25 19:37 UTC
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.18.1           | 
| OS       | darwin             |
| Prisma   | 2.5.1              |

## Logs
```
prisma-client {
  engineConfig: {
    cwd: '/Users/defrex/Code/treasure/api/prisma',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/Users/defrex/Code/treasure/api/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/Users/defrex/Code/treasure/api/node_modules/@prisma/client',
      binaryTargets: [],
      previewFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.5.1',
    enableExperimental: [],
    useUds: undefined
  }
}
plusX Execution permissions of /Users/defrex/Code/treasure/api/node_modules/.prisma/client/query-engine-darwin are fine
prisma-client Client Version 2.5.1
prisma-client Engine Version c88925ce44a9b89b4351aec85ba6a28979d2658e
```

## Schema
Here is the model for the entity in question
```prisma
model Task {
  @@map(name: "task")

  id             Int             @default(autoincrement()) @id
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @default(now())
  amount         Int             @default(0)
  archivedAt     DateTime?
  childId        Int
  completedAt    DateTime?
  confirmedAt    DateTime?
  paidAt         DateTime?
  parentId       Int
  recurrenceId   Int?
  title          String
  validAt        DateTime?
  expiresAt      DateTime?
  child          User            @relation("task_childIdTouser", fields: [childId], references: [id])
  parent         User            @relation("task_parentIdTouser", fields: [parentId], references: [id])
  taskRecurrence TaskRecurrence? @relation(fields: [recurrenceId], references: [id])
}
```

## Query
Given that, this query triggered the crash
```typescript
await prisma.task.count({
  where: {
    childId: 2,
    paidAt: null,
    AND: [
      {
        OR: [
          { validAt: { lt: '2020-08-30T04:00:00.000Z' } },
          { validAt: { equals: null } },
        ],
      },
      {
        OR: [
          { expiresAt: { gt: '2020-08-25T19:35:22.066Z' } },
          { expiresAt: { equals: null } },
        ],
      },
    ],
    completedAt: {
      not: null,
    },
    confirmedAt: {
      not: null,
    },
  },
})
```

**Comment by defrex** [comment] 2020-08-25 20:06
Something strange is happening here. While I've queried this model successfully plenty of times, I can now repro with this simple query.
```typescript
await prisma.task.findMany({
  where: {
    childId: 2,
  },
})
```

**Comment by defrex** [comment] 2020-08-25 20:27
I was able to get to the bottom of this. 

I had a `tstzrange` field in the table. 

We migrated away from using that field type in order to enable Prisma (since you don't support it yet), but apparently something whack happened with my migration and the field was still sitting around in my local DB. Dropping the field resolved the issue.

**Comment by janpio** [comment] 2020-08-27 10:40
Interesting! Can you describe the situation a bit more so we could possibly recreate it? That would be super interesting, because even with that it should really not crash in the way it did for you.

**Comment by defrex** [comment] 2020-08-27 19:16
It should be fairly simple to repro.

1. Make a postgres task with a `tstzrange` field.
2. Add the table, but _not_ the `tstzrange` field, to `schema.prisma`.
3. Query the table via `PrismaClient`.
5. 💥

**Comment by pantharshit00** [comment] 2020-09-03 16:29
Hey @defrex 

I wasn't able to reproduce this with version `2.6.1`. The client was able to query the model after the `tstzrange` type was commented out.
![image](https://user-images.githubusercontent.com/22195362/92141880-ad351700-ee30-11ea-8365-1e9e24eef673.png)


The underlying database has the following data:
![image](https://user-images.githubusercontent.com/22195362/92141925-ba520600-ee30-11ea-85b5-63eb340e63c3.png)


Can you please try this again with the latest verison and please make sure that you run `prisma generate` after you upgrade, thanks!

**Comment by defrex** [comment] 2020-09-03 19:42
Sorry, I deleted the field and moved on so I can't repro very easily anymore. If you're not able to get it happening, maybe it's no longer an issue.

**Comment by pantharshit00** [comment] 2020-09-04 01:44
Sure, I am going to close this then. If anyone else is experiencing this, feel free to comment here.

**Closed** 2020-09-04 01:44 UTC
Labels: bug/0-needs-info, kind/bug
