### ISSUE TITLE
"Can't resolve 'child_process'" when using enums in Next.js

### ISSUE THREAD

**Issue by JuanM04** [prisma/prisma-client-js#737] opened 2020-06-19 15:54 UTC
## Bug description
When using an enum from `@prisma/client` in my TypeScript, logic, it throws an error

```
event - build page: /facturas
wait  - compiling...
error - ./node_modules/@prisma/client/runtime/index.js
Module not found: Can't resolve 'child_process' in '/home/juanm04/dev/projects/martinseery-facturas/node_modules/@prisma/client/runtime'
Could not find files for /facturas in .next/build-manifest.json
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/juanm04/dev/projects/martinseery-facturas/node_modules/@prisma/client/runtime'
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/Compilation.js:925:10
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/neo-async/async.js:2830:7
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/neo-async/async.js:6877:13
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/juanm04/dev/projects/martinseery-facturas/node_modules/@prisma/client/runtime'
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/Compilation.js:925:10
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/neo-async/async.js:2830:7
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/neo-async/async.js:6877:13
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/juanm04/dev/projects/martinseery-facturas/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/juanm04/dev/projects/martinseery-facturas/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
event - compiled successfully
```

## How to reproduce
1. Create a Next.js project (`yarn create next-app -e with-typescript`)
2. Add Prisma and a schema with enums
3. Generate the Prisma client
4. Import in, for example, `pages/index.ts` a enum from `@prisma/client` and use it
5. See error

## Expected behavior
Not to throw an error (?)

## Prisma information

```prisma
// schema.prisma
enum PaymentType {
  CHECK
  TRANS
  NC
  CASH
  BALAN
  OTHER
}
```

```typescript
// pages/index.ts
import { PaymentType } from '@prisma/client'

export default () => <h1>Paying with {PaymentType.TRANS}</h1>
```

## Environment & setup

- OS: Kubuntu 20.04
- Database: MariaDB 10.2
- Prisma version: 2.0.1
- Node.js version: 14.2.0

**Comment by Cretezy** [comment] 2020-06-27 00:56
I can reproduce this. It seems that `@prisma/client` gets run (which calls `require("child_process")` when importing to a Webpack environment without `child_process` (such as Next.js on the client side).

This is quite annoying, as I can't use Prisma enums on my client-side, forcing me to duplicate it or use a string. I can't think of a solution except separating all enums to a file such as `@prisma/client/values` when generating the client, which only contains the enum values.

**Comment by pantharshit00** [comment] 2020-07-03 10:04
This is expected. You are not allowed to use Prisma code outside of `getServerSideProps` or `getStaticProps` function.

If you will use any code imported from Prisma inside of your React component, next.js will try to bundle Prisma into the client bundle and it will fail because you can't bundle node js packages like `child_process`

I will close this as a duplicate of https://github.com/prisma/prisma/issues/1272

Also, you can do something like this. Return the data in the `getServerSideProps` or `getStaticProps` function and use it as a prop:
```ts
import Layout from "../components/Layout";
import { PrismaClient, PaymentType } from "@prisma/client";

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const data = await prisma.checkout.findMany();
  return {
    props: {
      data: data.map((x) => x.paymentStatus),
      paymentTypes: PaymentType,
    }, 
  };
}

const IndexPage = ({
  data,
  paymentTypes,
}: {
  data: PaymentType[];
  paymentTypes: typeof PaymentType;
}) => (
  <Layout title="Home | Next.js + TypeScript Example">
    {JSON.stringify(data)}
    {JSON.stringify(paymentTypes.CHECK)}
  </Layout>
);

export default IndexPage;
```

**Closed by pantharshit00** 2020-07-03 10:04 UTC

**Comment by Cretezy** [comment] 2020-07-03 14:13
@pantharshit00 I don't think you understand the issue here.

We are talking about enums. It should be something easily supported because all enums can be split off into a separate file which could be used on the client.

**Comment by JuanM04** [comment] 2020-07-03 14:23
I understand why it is not allowed, but `@prisma/client/values` should be a very good option

**Comment by pantharshit00** [comment] 2020-07-03 15:15
> We are talking about enums. It should be something easily supported because all enums can be split off into a separate file which could be used on the client.

Yes, that is covered by https://github.com/prisma/prisma/issues/1272.
