### ISSUE TITLE
Invalid `photon.()` invocation on ECONNREFUSED

### ISSUE THREAD

**Issue by seawatts** [prisma/prisma-client-js#424] opened 2020-01-19 23:39 UTC
The error that is emitted if the connection cannot be established is not clear unless you set `DEBUG=*`  

`engine connect ECONNREFUSED 127.0.0.1:57626`

**Comment by pantharshit00** [comment] 2020-01-22 18:26
Can you please share more details like a screenshot? Also, if you can provide a minimal reproduction for this, that would be great.

**Comment by JWambaugh** [comment] 2020-01-25 01:38
I am having the same issue. Happens after just a few queries now. #435 Regardless of the cause, there should be a more verbose error message when this happens.

**Comment by timsuchanek** [comment] 2020-11-11 12:28
Fixed in latest version.

**Closed by timsuchanek** 2020-11-11 12:28 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action
