### ISSUE TITLE
Prisma and node 12.19.0

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#907] opened 2020-10-07 13:18 UTC
## Bug description

Prisma (latest dev, 2.8.0, 2.8.1, 2.7.0 versions) with node 12.19.0 results in the following error: 

```
2020-10-07T12:57:03.018176+00:00 app[web.1]: node[4]: ../src/node_http_parser_impl.h:529:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
2020-10-07T12:57:03.023285+00:00 app[web.1]: 1: 0xa17c40 node::Abort() [node]
2020-10-07T12:57:03.024000+00:00 app[web.1]: 2: 0xa17cbe  [node]
2020-10-07T12:57:03.024670+00:00 app[web.1]: 3: 0xa3214a  [node]
2020-10-07T12:57:03.025326+00:00 app[web.1]: 4: 0xc019e9  [node]
2020-10-07T12:57:03.027280+00:00 app[web.1]: 5: 0xc037d7 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
```

## How to reproduce

1. `git clone https://github.com/divyenduz/prisma-client-js-907 p2-node-12`
1. `cd p2-node-12`
1. Setup node `12.19.0` in the environment
1. Add Postgres `DB_URL` to `prisma/.env` (ping Divy, if needed)
1. `node index.js`
1. Invoke the URL (`http://localhost:3000`), it should fail

The error mentioned above should be visible in the logs. 

## Expected behavior

Prisma and node `12.19.0` should work.

**Comment by pantharshit00** [comment] 2020-10-07 14:08
From my findings, looks like `12.x` node runtime of heroku is not working with prisma. It is most likely because some module in the dependency chain is using `process.binding` to use the http parser which node internally uses.

When I use `14.x` runtime it works which is the current node lts release. Also, I tried an older version of prisma `2.6` which also fails in heroku `12.x` so this is clearly not a regression in prisma.

**Comment by pantharshit00** [comment] 2020-10-07 14:43
Looks like node `12.19.0` broke something here. We are able to reproduce this locally with node version `v12.19.0` while it is working fine with node version `12.18.4`.

![image](https://user-images.githubusercontent.com/22195362/95346432-793e8d00-08d9-11eb-87a9-d7bea52e8d90.png)

We will need to report this to node.js I think.

**Comment by pantharshit00** [comment] 2020-10-07 15:12
Undici issue for this: https://github.com/nodejs/undici/issues/448

**Comment by Jolg42** [comment] 2020-10-08 08:01
Fixed in dev version `@prisma/cli@2.9.0-dev.55` in [this PR](https://github.com/prisma/prisma/pull/3872) (I recommend to only use latest tag from npm for production though).

If you want to use Prisma 2.8 and older you can pin your Node.js version to a different version of Node (Not 12.9.0)

**Comment by Jolg42** [comment] 2020-10-08 08:35
Current workaround until a fix is found and released in next Prisma release is to pin your Node.js version to a previous version of Node (<12.9.0).

**Comment by Jolg42** [comment] 2020-10-09 13:11
Undici 2.0.7 was released with the fix from this PR https://github.com/nodejs/undici/pull/449

I updated the update dependency with https://github.com/prisma/prisma/pull/3884

It's now in `2.9.0-dev.66` (We recommend to only use latest tag from npm for production, not dev).

Next step: confirm the fix @divyenduz

**Comment by Jolg42** [comment] 2020-10-10 13:24
Here is an example on how to pin a Node.js dependency for Netlify and Vercel, thanks to @thedavidprice https://github.com/redwoodjs/redwood/issues/1313#issuecomment-706443974

> ## Workaround
> 
> Pin the version of NodeJS used for Netlify and Vercel build in your `.nvmrc` file:
> 
> * Replace
> 
> 
> ```
> // .nvmrc
> 
> lts/*
> ```
> 
> * with
> 
> 
> ```
> // .nvmrc
> 
> v12.18.4
> ```

**Comment by Jolg42** [comment] 2020-10-12 12:13
The fix was confirmed with https://github.com/prisma/e2e-tests/pull/834

It will be part of the 2.9.0 release tomorrow 🚀

**Closed by Jolg42** 2020-10-12 12:13 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript
