### ISSUE TITLE
Date time only accepts ISO 8601 format

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#212] opened 2019-09-02 09:05 UTC
This topic ties into the feature - "custom scalar support".  

From a user: 

> In running the latest version, Photon accepts certain ISO 8601 formats in a DateTime field but not others. Specifically, using the example from the Prisma1 docs, the first three formats throw an error while the fourth does not. Anyone else getting this?

<img width="278" alt="Screen Shot 2019-08-31 at 12 33 24 PM" src="https://user-images.githubusercontent.com/746482/64103066-92d5e280-cd71-11e9-9c33-48ca315786c8.png">

**Comment by divyenduz** [comment] 2019-09-02 09:06
@pantharshit00 Please create a reproduction and list what error is actually thrown 🙌

**Comment by pantharshit00** [comment] 2019-09-02 15:19
Looks like the photon runtime is rejecting the values rather than the query engine:
![image](https://user-images.githubusercontent.com/22195362/64123757-db69bc00-cdc2-11e9-9ab7-8de6383696d3.png)


Reproduction: https://github.com/harshit-test-org/prisma-photon-212

**Comment by pantharshit00** [comment] 2020-04-21 08:00
Closing in favour of #658

**Closed by pantharshit00** 2020-04-21 08:00 UTC
Labels: kind/feature, process/candidate, topic: types
