### ISSUE TITLE
[prisma-client-js] allow to findOne by index

### ISSUE THREAD

**Issue by iamkevinwolf** [prisma/prisma-client-js#501] opened 2020-02-18 21:09 UTC
Hi! I am working on a multi-tenant app which has the following schema:

```prisma
model Team {
  id          String       @id @default(cuid())
  createdAt   DateTime     @default(now())
  updatedAt   DateTime     @updatedAt
  slug        String       @unique
  projects    Project[]
}

model Project {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  team      Team
  slug      String

  @@index([slug])
}
```

And I want to be able to search a `Project`, where `slug` is `xxx` and `team.slug` is `yyy`, but currently `prisma.model.findOne` only allows me to query by unique fields.

A temporary solution I'm using is to `findAll` where `slug` is `xxx` and `team.slug` is `yyy` and returning the zero-index of the returned array, but it seems weird.

Maybe I'm, missing something regarding indexes or single field selections 😂

**Comment by pantharshit00** [comment] 2020-02-20 13:08
This is currently by design. `findOne` guarantees to return a single return and if you search by a non-unique field, the is no guarantee that there is a single match. If you want to make it available in findOne you will need to make the index unique.

But we are considering the following API in future:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/22195362/74935956-38a80700-540f-11ea-9086-8812776e37a6.png">


Keep in mind this is just a proposal and it can change. You can have a look here: https://github.com/prisma/specs/issues/356


Also, closing this as a duplicate of https://github.com/prisma/prisma2/issues/379

**Closed by pantharshit00** 2020-02-20 13:08 UTC
