### ISSUE TITLE
Some(WrongType ... Type(Uuid)) error

### ISSUE THREAD

**Issue by maticzav** [prisma/prisma-client-js#512] opened 2020-02-20 19:59 UTC
Hey 👋 ,

I am trying to create an instance in the database and also provide an id field data.

_model:_
```prisma
model locations {
  id        String   @id
  latitude  Float
  longitude Float
  tweets    tweets[]
}
```

_error:_
```
prisma-client Requests: +111ms
  prisma-client [
  prisma-client   'mutation {\n' +
  prisma-client     '  createOnelocations(data: {\n' +
  prisma-client     '    id: "f70c6744-c2cb-5a28-b4c6-5aa0680dac0c"\n' +
  prisma-client     '    latitude: 211635869109.4528\n' +
  prisma-client     '    longitude: -352645828260.6592\n' +
  prisma-client     '  }) {\n' +
  prisma-client     '    id\n' +
  prisma-client     '    latitude\n' +
  prisma-client     '    longitude\n' +
  prisma-client     '  }\n' +
  prisma-client     '}'
  prisma-client ] +0ms
  prisma-client Results: +593ms
  prisma-client [
  prisma-client   PrismaClientUnknownRequestError: Error occurred during query execution:
  prisma-client   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(WrongType { postgres: Type(Uuid), rust: "alloc::borrow::Cow<str>" }) }) })
  prisma-client       at NodeEngine.graphQLToJSError (/Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:16029)
  prisma-client       at /Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:14963
  prisma-client       at Array.map (<anonymous>)
  prisma-client       at /Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:14930
  prisma-client       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma-client       at Dataloader.loader (/Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/index.js:55:23)
  prisma-client ] +0ms
  prisma-client Error: Error occurred during query execution:
  prisma-client ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(WrongType { postgres: Type(Uuid), rust: "alloc::borrow::Cow<str>" }) }) })
  prisma-client     at NodeEngine.graphQLToJSError (/Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:16029)
  prisma-client     at /Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:14963
  prisma-client     at Array.map (<anonymous>)
  prisma-client     at /Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/runtime/index.js:1:14930
  prisma-client     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma-client     at Dataloader.loader (/Users/maticzavadlal/Code/work/prisma/prisma-test-utils-automation/dbs/basic-twitter/node_modules/prisma-client/index.js:55:23) +3ms
```

**Comment by janpio** [comment] 2020-02-20 21:00
What code are you executing exactly?

**Comment by janpio** [comment] 2020-02-20 21:26
Could not reproduce: https://github.com/janpio/repro512
What are you doing differently?

**Comment by pantharshit00** [comment] 2020-02-21 07:07
@maticzav If you share the SQL dump of the database, that would be useful for triaging this.

**Comment by maticzav** [comment] 2020-02-21 08:08
@janpio try running `src/test.ts` in `prisma-test-utils-automation`. I also set up a debugging environment there.

To reproduce: pull, install dependencies and `yarn ts-node src/test.ts`

**Comment by janpio** [comment] 2020-02-21 18:36
@pantharshit00 Matic refers to https://github.com/prisma/prisma-test-utils-automation here, so if you have the time you could do what he suggested for me.

**Comment by maticzav** [comment] 2020-02-24 12:40
@pantharshit00 any progress with this one? I can't do much without your help here. 🙂

**Comment by janpio** [comment] 2020-02-24 14:32
@maticzav Could you please look into https://github.com/prisma/prisma-client-js/issues/512#issuecomment-589326658 and see where your code differs? Having a minimal reproduction is always much easier than "look into my giant project to figure it out" as I am sure you know.

**Comment by maticzav** [comment] 2020-02-24 15:06
@janpio I prepared a one-file reproduction with a debugger enabled. I am not sure how much further I can go with making reproduction more approachable. The difference with your case is in the production of `id` value. As described above and as I've asked in the Slack thread the problem I am having is with the id verification.

**Comment by pantharshit00** [comment] 2020-02-24 15:21
I am unable to boot the script :/,
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/75162073-ee8e9080-5742-11ea-9294-37abe9a8cd6b.png">

**Comment by pantharshit00** [comment] 2020-02-24 15:47
This is related to https://github.com/prisma/prisma2/issues/479

Right now the implementation of `@id @default(uuid())` in postgres marks the database field as a text(See https://github.com/prisma/migrate/issues/114). The query engine uses an internal implementation of the UUID type. So when you introspect a UUID, the introspection engine maps it to a String, but the query engine does not understand the postgres UUID type so it panics. We ignored this in the past we are waiting on native database type support as mentioned in #47


So either you can change the database type from `uuid` to string or you will need to wait till we release support for postgres uuid in the query engine here.

**Comment by pantharshit00** [comment] 2020-02-24 15:48
We can close this as a duplicate but I don't know as this issue concerns an internal project.

**Comment by janpio** [comment] 2020-02-24 17:48
@maticzav Workaround: Do not use/support UUID types for now.

**Comment by janpio** [comment] 2020-02-24 17:50
Let's keep this around @pantharshit00, as it shows the exact outcome in Prisma Client. Also might be tackled outside of context of other native database types work.

**Comment by maticzav** [comment] 2020-02-24 17:59
@janpio @pantharshit00 this is an introspection result - how can I determine which schemas use `uuid` and which don't?

**Comment by pantharshit00** [comment] 2020-02-24 18:02
> this is an introspection result - how can I determine which schemas use uuid and which don't?

You can use a GUI like https://tableplus.io to see the postgres schema. It is a bit of manual work though.

**Comment by janpio** [comment] 2020-02-24 19:21
You can not really, and these schemas failing is exactly what we want to find out with `test-utils` so I would say this is fine for now. Make it work with other schemas that do not have this (e.g. MySQL)

**Comment by timsuchanek** [comment] 2020-11-11 13:07
This is fixed in the latest version.

**Closed by timsuchanek** 2020-11-11 13:07 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, topic: types
