### ISSUE TITLE
JSON: Error occurred during query validation & transformation

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma-client-js#867] opened 2020-09-02 19:41 UTC
## Bug description

Attempt to `upsert` user with the following `json` data:
```json
{"code":445165,"sent":1}
```

```
code: 'P2009',
  meta: {
    query_validation_error: 'Error occurred during query validation & transformation:\n' +
      'Mutation (object)\n' +
      '  ↳ upsertOneUser (field)\n' +
      '    ↳ update (argument)\n' +
      '      ↳ UserUpdateInput (object)\n' +
      '        ↳ auth (field)\n' +
      '          ↳ Value types mismatch. Have: String("{\\"code\\":445165\\"sent\\":1}"), want: Object((Weak))',
    query_position: '.Mutation.upsertOneUser.update.UserUpdateInput.auth'
```

#### Schema
```prisma
model User {
  auth JSON?
  mobile String
}
```

#### File
```js
auth = {
  // Random 6-digit auth code
  code: Math.floor(Math.random() * 900000) + 100000,
  sent: 1
}

user = await prisma.user.upsert({
  where: { mobile },
  update: { auth },
  create: {
    auth
  }
})
```

## Expected behavior

Don’t expect an error since we’re using PostgreSQL.

What’s strange, too, is that if you look closely at the error message, it shows the `auth` object having been `JSON.stringify`-ied, which doesn’t happen in our code (we previously did, but then removed it, and the error message remained the same.

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: `v12.6.0`
- Prisma version: `2.7.0-dev.2`

**Comment by pantharshit00** [comment] 2020-09-02 20:42
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/3497

A patch is planned for this, please be patient

**Closed by pantharshit00** 2020-09-02 20:42 UTC
