### ISSUE TITLE
Prisma Client removed on adding a new package: Error: @prisma/client did not initialize yet

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#390] opened 2020-01-08 16:53 UTC
This behavior can be observed in both `npm` and `yarn`, setup a Photon project and run any query with photon to ensure that it exists. 

Now add any dependency in `yarn`, `npm` and re-execute photon query. I reproduced this with `yarn add dotenv` or `npm install dotenv`. 

It doesn't matter if `dotenv` is already install or is a new package. I could reproduce this reliably. 

You would run into (error paraphrased): 

`npm`: `import { Photon } from '@prisma/photon'` no found. 
`yarn`: `Photon is not initialized yet. Please run prisma2 generate again`

I used the following versions: 

```
divyendusingh [prisma]$ yarn --version
1.21.1
divyendusingh [prisma]$ npm --version
6.10.2
```

**Comment by timsuchanek** [comment] 2020-01-17 15:36
I can't reproduce this with `npm@6.13.4` and `yarn@1.21.1`.

**Comment by divyenduz** [comment] 2020-01-17 15:42
I could reproduce this once today. But not anymore afterwards. I would love to keep this in the next sprint as I think it is important and try to find a reproduction.

**Comment by divyenduz** [comment] 2020-01-17 18:06
Tim has a reproduction of a different error of similar nature now. I will look for a related reproduction of the actual error "Photon is not initialized yet. Please run prisma2 generate again" but Tim can already start on the other bit of it.

**Comment by divyenduz** [comment] 2020-01-20 13:10
`"Photon is not initialized yet. Please run prisma2 generate again"` this is also observable on Heroku. Might be related, will create a separate issue, if needed.

**Comment by timsuchanek** [comment] 2020-01-20 14:25
I created a reproduction **attempt** in https://github.com/timsuchanek/photonjs-390. But just an attempt. Unassigning myself until we have a reliable reproduction.

**Comment by pantharshit00** [comment] 2020-01-23 18:29
I am also unfortunately unable to reproduce this.

**Comment by divyenduz** [comment] 2020-01-29 15:21
I am also unable to reproduce this with a local package like in Tim's repo. I tried that and its file variant (referring to prisma-client by its folder).

**Comment by janpio** [comment] 2020-01-30 16:33
Note: Update issue title and description to new output.

**Comment by divyenduz** [comment] 2020-01-30 16:35
Internal note: Action item: "Change the facade message to link back to this issue"

**Comment by embiem** [comment] 2020-01-31 23:52
I encountered this issue after updating from preview 19 to 20.3

Happened locally, but also on the ZEIT now deployment. Could only fix it by adding the `"postinstall": "prisma2 generate"` script. AFAIK this should not be necessary and was one of the reasons for the @photon/client "fake" package, right?

**Comment by timsuchanek** [comment] 2020-02-04 13:15
Thanks for letting us know @embiem. You're right, that the main reason to introduce `@prisma/client` was indeed to not need a postinstall hook anymore.
However, because of https://github.com/yarnpkg/yarn/issues/7762 this is still a problem in Now.
We have a "fix" in place, which installs a postinstall hook with "prisma2 generate" to the application if you deploy to Now, however, it seems like that "fix" is not working in your case. Two questions:
1. Can you try it with the latest version preview 21?
2. If it still happens, can you give us an overview about your folder structure, mostly if it's a mono repo and where you have the `prisma/schema.prisma` file and where you have the `package.json`.

Thanks!

**Comment by embiem** [comment] 2020-02-06 06:30
I removed the postinstall script & updated to preview 21. Now, it works locally and also when deploying to ZEIT's now. Thank you!

My folder structure looked like this (no monorepo):
```
prisma
	migrations
	schema.prisma
package.json
```

**Comment by krzkaczor** [comment] 2020-04-20 20:04
Just happened to me. In my project renamed `prisma` to `database` so my folder structure is custom.

I think it's obvious that it doesn't work without some kind of config file specifying where to find `schema.prisma` file. Can it be configured this way? For now I just added custom postinstall hook:

```
"postinstall": "yarn prisma:generate",
"prisma:generate": "prisma generate --schema=./database/schema.prisma",
```

**Comment by krzkaczor** [comment] 2020-04-30 07:44
Oh, I just realized that it's possible to hit this bug due to a version mismatch:

1. monorepo with yarn workspaces
2. `package-a` has dependency on `@prisma/cli` and `@prisma/client` `2.0.0-beta.2`
3. `package-b` has dependency on `@prisma/cli` and `@prisma/client` `2.0.0-beta.3`

I was getting this error all the time for one of the packages.

**Comment by timsuchanek** [comment] 2020-04-30 11:28
Thanks for the info @krzkaczor!
Can you try this with the latest alpha in both packages?
We did recent fixes, which should alleviate this situation.

**Comment by timsuchanek** [comment] 2020-05-04 09:36
We're closing this for now, as we can't reproduce this anymore.
In case it's not fixed for you, just let us know and we can reopen it!

**Comment by lukehamilton** [comment] 2020-05-10 23:20
@timsuchanek Can we reopen this issue as I'm getting it with `"@prisma/client": "^2.0.0-beta.4",` deploying to vercel / zeit

```
020-05-10T23:19:12.070Z	undefined	ERROR	Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
    at new PrismaClient (/var/task/backend/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/var/task/backend/src/index.js:563:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/___now_launcher.js:21:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _tryRequire (/var/runtime/UserFunction.js:75:12)
    at _loadUserApp (/var/runtime/UserFunction.js:95:12)
    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)
    at Object.<anonymous> (/var/runtime/index.js:45:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
RequestId: bfa7224f-573f-45f7-90e1-e9133d5e85c9 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by pantharshit00** [comment] 2020-05-11 09:24
@lukehamilton Can you please a small reproduction? Thanks!

**Comment by lukehamilton** [comment] 2020-05-11 22:21
@pantharshit00 Here is the app: https://github.com/lukehamilton/lyra-labs

I created a new app and that worked with beta4. I can't get beta4 to work in the above repo.

**Comment by jjjuk** [comment] 2020-05-12 18:20
@lukehamilton Might you show an example of server with prisma 2.0.0-beta.2 that works on Vecel?

**Comment by lukehamilton** [comment] 2020-05-13 02:02
@jjjuk Here is an example that works on Vercel with beta4. 

https://github.com/lukehamilton/prisma-beta4-reproduction

Hope it helps.

**Comment by jjjuk** [comment] 2020-05-14 01:54
@lukehamilton thank you! But does it work with SQLite?

**Comment by lukehamilton** [comment] 2020-05-14 02:18
@jjjuk I'm not sure how to run it with SQLite on Vercel. I have an Postgres database running on Amazon that I'm using.

To use SQLite change the connector. I think you can do something like this...

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
```

**Comment by timsuchanek** [comment] 2020-05-14 08:45
Thanks for the reproduction @lukehamilton! We'll look into it.
Regarding SQLite and Vercel: As Vercel uses Lambda and Lambda does not allow writing to the app dir, but only to the `/tmp` dir, you need to copy or move your sqlite db on bootup time of your app to `/tmp`, then it works.
I created a hacky example here, how one could do that:
https://github.com/timsuchanek/next-prisma-now-sqlite

But using Postgres is for sure the recommended way :)

**Comment by jjjuk** [comment] 2020-05-15 03:17
@timsuchanek Thank you so much!

**Comment by 2color** [comment] 2020-05-25 13:41
I just tried to deploy the [Prisma Vercel example](https://github.com/prisma/prisma-examples/tree/now-vercel-rename/deployment-platforms/vercel) to Vercel and I'm seeing the same error. This worked up until recently, so I think it might be related to a change on Vercel's end.

**Comment by Jolg42** [comment] 2020-05-25 14:33
Indeed I can reproduce on Vercel with Daniel's example

```
[GET] /api/posts
16:32:36:59
Status:-1
Duration:178.88ms
Memory Used:15 MB
ID:tn878-1590417156107-ea98747663ef
User Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0
2020-05-25T14:32:37.607Z	undefined	ERROR	Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.    at new PrismaClient (/var/task/node_modules/.prisma/client/index.js:3:11)    at Object.<anonymous> (/var/task/api/getPosts.js:2:16)    at Module._compile (internal/modules/cjs/loader.js:1156:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)    at Module.load (internal/modules/cjs/loader.js:1000:32)    at Function.Module._load (internal/modules/cjs/loader.js:899:14)    at Module.require (internal/modules/cjs/loader.js:1042:19)    at require (internal/modules/cjs/helpers.js:77:18)    at Object.<anonymous> (/var/task/___now_launcher.js:22:18)    at Module._compile (internal/modules/cjs/loader.js:1156:30)RequestId: bb2de587-31b4-422c-9f6b-bd91932fac4d Error: Runtime exited with error: exit status 1Runtime.ExitError
```

**Comment by janpio** [comment] 2020-05-25 15:05
e2e tests should have caught this, or we need to improve the e2e tests.

**Comment by divyenduz** [comment] 2020-05-25 15:44
I am able to reproduce with the `prisma-examples` code but not with E2E code. My hunch is that the examples code uses `/api` from vercel and they might be deploying that differently from the node build method which E2E tests use. 

@pantharshit00 or someone else, can you please confirm if this is also your observation? 

To improve E2E tests, we might want to add another example for Vercel that uses the `/api` way of deployment, I can do that once this is confirmed.

**Comment by pantharshit00** [comment] 2020-05-25 16:37
I can also reproduce this with prisma-examples example: 
![image](https://user-images.githubusercontent.com/22195362/82830272-df9ab400-9ed2-11ea-85b2-b60cb7799794.png)


I can't wrap my head around how the e2e code is even deploying: https://github.com/prisma/e2e-tests/blob/master/platforms/vercel/index.js

It is not an serverless function, maybe vercel is shimming some behavior for compatibility.

**Comment by pantharshit00** [comment] 2020-05-25 16:56
The express example work! https://vercel-prisma-test-ptm2g0krt.now.sh/

Did vercel merge `@now/node` and `@now/node-server` into one? Anyways we need to test for serverless target in vercel

**Comment by timsuchanek** [comment] 2020-06-04 08:56
Vercel is fixed again!

**Closed by timsuchanek** 2020-06-04 08:56 UTC
Labels: bug/1-repro-available, kind/bug, team/typescript

**Comment by seanking11** [comment] 2020-06-05 21:37
I am getting this same error when trying to deploy my functions to Firebase, even with the latest `2.0.0-beta.8`. All of my functions use Prisma and I get the following error for each function that I try to deploy.

From the Firebase functions console:
```
Detailed stack trace: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

**Current Workaround**
The only way I've been able to deploy successfully is if I delete all of my functions and then deploy when nothing is already deployed. This seems to work as it cleanly installs & generates the Prisma client. If there is already code deployed, any subsequent changes will not work.

**Versions**
`"@prisma/cli": "^2.0.0-beta.8"`
`"@prisma/client": "^2.0.0-beta.8"`
`"firebase-functions": "^3.6.1"`
`node - 10.16.3`
`npm - 6.9.0`

**Folder Structure**
I saw above that this could cause issues if you have a monorepo with different versions. My repo has both frontend and backend apps in it, however, `@prisma/cli` & `@prisma/client` are only installed in the backend portion `functions`. Here's my folder structure though in case that's helpful. When receiving the error above, I was in the `functions` folder attempting to deploy.

```
my-app
  |_ functions (backend)
    |_ src
    |_ node_modules
    |_ prisma
      |_ schema.prisma
      |_ .env
      |_ migrations
    |_ package.json
    |_ index.js (functions trying to get deployed, pulling code from `src`)
    |_ .nvmrc (10.16.3) (firebase functions don't support node 12 yet)
  |_ src
    |_ ... frontend code (Vue)
  |_ dist
  |_ package.json
  |_ .nvmrc (12.6.0)
```

I've also tried adding the following to my `functions/package.json` (as suggested above) to force firebase to re-generate the prisma client after installing, however, I've had no luck. 

```
// package.json scripts
"postinstall": "npm run prisma:generate",
"prisma:generate": "npx prisma generate"
```

My current workaround works as the app isn't live, however, when I go to production soon that would require taking down our services for every code change, something I would really want to avoid. Please let me know if there's any other info I can provide to help debug this. Thanks Prisma team!

**Comment by janpio** [comment] 2020-06-05 22:33
Can you please open a new issue @seanking11? We should investigate this properly, much easier in its own issue. Thanks.

**Comment by seanking11** [comment] 2020-06-05 23:31
@janpio I was opening up a new issue for this and rubber-ducked my way into finding the solution. The issue was that I had `@prisma/cli` listed as a `devDependency` and it seems like firebase does not install those. Therefore, when deploying, it would install all my dependencies (not prisma/cli) and then run the initial `prisma generate`, leaving me with the error I had outlined above.

I moved `@prisma/cli` to a normal `dependency` and tried deploying and it worked!

I was getting the following error and attempted the fix as outlined, but given what I mentioned above, that fix wouldn't work in Firebase's situation as it suggests adding as a dev dependency.
```
In order to use "@prisma/client", please install @prisma/cli. You can install it with "npm add -D @prisma/cli".
```

This seems to be pretty specific to my situation with Firebase, however, it might be helpful to note in the [setup](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client#1-prerequisites) that services like Firebase might require the cli to be listed as a normal dependency.

Thanks for the quick response and for building an awesome product!

**Comment by janpio** [comment] 2020-06-06 15:07
Awesome. We definitely want to debug or even fix this - so could you just copy your both comments here into a new issue anyway? Thanks.

**Comment by Zhomart** [comment] 2020-06-18 03:56
There is https://github.com/prisma/prisma/discussions/2106 similar discussion going. I had similar issue, but it was my own fault adding `**/node_modules/**` to `ignore` field in `firebase.json`.

**Comment by Jolg42** [comment] 2020-06-18 08:32
@janpio I created this issue for the Firebase problem https://github.com/prisma/prisma-client-js/issues/732

**Comment by deadcoder0904** [comment] 2020-07-08 10:47
I got this error `Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.` when I updated Prisma to v2.2.0

**Comment by janpio** [comment] 2020-07-08 11:21
Can you open a new issue pls @deadcoder0904? Thanks.

**Comment by deadcoder0904** [comment] 2020-07-08 11:40
I think I opened in wrong repo 🤦‍♂️ https://github.com/prisma/prisma/issues/2963

**Comment by janpio** [comment] 2020-07-08 14:12
All good. Thanks.

**Comment by nargetdev** [comment] 2020-07-29 08:40
@deadcoder0904 same here - exactly when I upgraded to "@prisma/client": "2.2.0"  (which was necessary to fix a different bug within prisma up from 2.1.0)

**Comment by deadcoder0904** [comment] 2020-07-29 11:05
@nargetdev did you solve it? if not, here's the [solution](https://github.com/prisma/prisma/issues/2963#issuecomment-656482963) :)

**Comment by MichaelGorski** [comment] 2020-09-07 10:24
I am getting this error. Couldn't find any workarounds yet. 

<img width="1346" alt="Bildschirmfoto 2020-09-07 um 12 23 40" src="https://user-images.githubusercontent.com/8994411/92377793-00df8300-f105-11ea-894a-b13be50723bd.png">

My dependencies
```
  "dependencies": {
    "@prisma/client": "^2.6.2",
    "apollo-server": "^2.17.0",
    "body-parser": "^1.19.0",
    "connect": "^3.7.0",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "faker": "^5.1.0",
    "firebase-admin": "^9.1.1",
    "nexus": "^0.26.1",
    "nexus-plugin-prisma": "^0.18.1",
    "uuid": "^8.3.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/node": "^7.10.5",
    "@babel/preset-env": "^7.11.0",
    "@prisma/cli": "^2.6.2",
    "@types/node": "^14.6.4",
    "cross-env": "^7.0.2",
    "nodemon": "^2.0.4",
    "ts-node": "^9.0.0",
    "ts-node-dev": "^1.0.0-pre.62",
    "typescript": "^4.0.2"
  },
```

**Comment by sreuter** [comment] 2020-09-07 11:05
@MichaelGorski You should remove your @prisma/cli and @prisma/client dependencies from your package.json and delete your node_modules (and yarn.lock if you use yarn) and install things fresh again.

That being said, I'm getting the same error right now, even tho I don't have those in my package.json.

**Comment by MichaelGorski** [comment] 2020-09-07 11:09
**Solved it**
Somehow it my dependencies were bugged and reinstalled @prisma/client as a dependencie like @prisma/cli

**My Solution:**
Remove all related dependencies, delete node_modules. Install it clear. Remove all related files from your project. 
Add nexus, run nexus dev. You should get a warning with empty Graphql etc.. Then move all the files back to api/graphql, add nexus-plugin-prisma, run nexus dev and it should work again.

@sreuter Did you try my solution? It worked for me

**Comment by sreuter** [comment] 2020-09-07 12:18
Thanks @MichaelGorski.. For me it was something else in case somebody still has problems: 

I had to remove `output   = "./generated/client"` from my `schema.prisma` (which was a left over from using the client directly before nexus), so `npx prisma generate` actually creates the client in the right location.

**Comment by talentlessguy** [comment] 2020-09-26 20:11
Happens with pnpm 5.6 and node 14.8

```
 Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again
```

even though the client is already generated

doesn't work with yarn 1.22.5 either

even tho the client exists:

```
➜ ls node_modules/@prisma/client
 generator-build   node_modules   runtime
 index.d.ts        package.json   scripts
 index.js          README.md     
```

**Comment by pantharshit00** [comment] 2020-09-28 11:12
@talentlessguy Client is not generated at that location now, please check `node_modules/.prisma`

**Comment by talentlessguy** [comment] 2020-09-28 12:07
@pantharshit00 there's this:

```
➜ ls node_modules/.prisma/client
 index.d.ts   index.js   package.json   query-engine-debian-openssl-1.1.x   schema.prisma
```

**Comment by jdevng** [comment] 2020-11-01 21:28
My environment is setup with a prisma2 directory and an apollo2 directory. The prisma directory is setup connected to MySQL. Commands invoked from the CLI write and read to/from the database.

I am attempting to load Prisma Client for use in Apollo2. I am in the Apollo directory, and add the dependency for prisma client using the following:

    npm install "@prisma/client" --save-dev

I added the following code to my index.js for Apollo:

    import { PrismaClient } from '@prisma/client';
    const prisma = new PrismaClient();

I get the following error:

    Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

No idea what this means, I wouldn't assume a dependency would need to be 'initialized', but I assume it's trying to build code from my schema. So I run

    % npx prisma generate --schema ../prisma/hello-prisma/prisma/schema.prisma

which points to my prisma schema I had setup previously, I'm assuming this is used to generate the client code. It completes without error. 

When invoking apollo, I get the same generate error. So I run the following:

    % prisma generate
     ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?

How do I set this up so that Apollo can load in the PrismaClient?

**Comment by Jolg42** [comment] 2020-11-02 08:24
Hi @jdevng!

Your output here
```
% prisma generate
 ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?
```
looks like Prisma 1 output, to avoid this you could run npx like this `npx @prisma/cli generate` or install it globally `npm i -g @prisma/cli`

**Comment by srikanthkyatham** [comment] 2020-11-24 10:16
> Hi @jdevng!
> 
> Your output here
> 
> ```
> % prisma generate
>  ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?
> ```
> 
> looks like Prisma 1 output, to avoid this you could run npx like this `npx @prisma/cli generate` or install it globally `npm i -g @prisma/cli`
If the above advise would have mentioned in the output, it would be more helpful.

**Comment by Jolg42** [comment] 2020-11-24 10:20
@srikanthkyatham It's something we want to improve indeed! 😃

**Comment by samrith-s** [comment] 2021-01-02 21:03
Hey. I am trying to deploy my lambda function which used Prisma 2. I was directed to this issue with from the error.

I currently do:
```
prisma generate
```

And then package everything.

In my package, I have a `node_modules` folder. Which has all of the prisma stuff:
![image](https://user-images.githubusercontent.com/9032162/103466491-01e89000-4d46-11eb-90dd-46adc0e969c5.png)

Is something missing? Coz I get this error when trying to run my lambda:
![image](https://user-images.githubusercontent.com/9032162/103466511-23497c00-4d46-11eb-97c0-b2d825b6f0cd.png)

**Comment by Jolg42** [comment] 2021-01-06 10:43
Context for @samrith-s comment's https://github.com/prisma/prisma-client-js/issues/390#issuecomment-753529630
Minimal reproduction https://github.com/samrith-s/nestjs-prisma-serverless-error
https://prisma.slack.com/archives/CKQTGR6T0/p1609623950269000

**Comment by samrith-s** [comment] 2021-01-06 18:15
I had a chat with @ryands17 and he advised me to include `@prisma/cli` to the build. Now my package size rose from 7MB to 59MB! Is there any way to reduce this? Coz this is eating up on my deployment time massively.

**Comment by Jolg42** [comment] 2021-01-07 11:33
@samrith-s in your case you could remove the `@prisma/cli` and generate the Prisma Client in a custom folder that you include when doing the deployment.
See https://www.prisma.io/docs/concepts/components/prisma-client/generating-prisma-client#specifying-a-custom-output-path
Does that work for you?

**Comment by samrith-s** [comment] 2021-01-10 03:06
@Jolg42 yeah I tried that. But I still need to manually pack the rhel-open-ssl binary with lambda which isn't done at all in the example. 

I have so much boilerplate code just to make the query engine available to Prisma, have no idea how it works in the SLS Lambda example here: https://www.prisma.io/docs/guides/deployment/deploying-to-aws-lambda

**Comment by Jolg42** [comment] 2021-01-11 10:32
@samrith-s Could you maybe create a new issue about that with your boilerplate code?

**Comment by NickSchmitt** [comment] 2021-01-13 04:54
Got to step 3 in the Prisma Quick Start tutorial and could not run `npm run dev`. Instead, I got 

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
```
Upon running prisma generate I receive `zsh: command not found: prisma`

**Comment by Jolg42** [comment] 2021-01-13 15:58
Note: discussion from previous comment is there https://github.com/prisma/prisma/discussions/4978
