### ISSUE TITLE
"TypeError: Cannot read property '0' of undefined" on typo in `where` in query

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#611] opened 2020-03-29 23:55 UTC
```sql
CREATE TABLE "public"."AlmostTheLastUser" (
  id SERIAL PRIMARY KEY,
  name TEXT
);

CREATE TABLE "public"."AlmostTheLastPost" (
  id SERIAL PRIMARY KEY,
  title TEXT,
  "authorId" INTEGER,
  CONSTRAINT author FOREIGN KEY ("authorId") REFERENCES "public"."AlmostTheLastUser" (id) ON DELETE SET NULL
);
```

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model AlmostTheLastPost {
  authorId          Int?
  id                Int                @default(autoincrement()) @id
  title             String?
  AlmostTheLastUser AlmostTheLastUser? @relation(fields: [authorId], references: [id])
}

model AlmostTheLastUser {
  id                Int                 @default(autoincrement()) @id
  name              String?
  AlmostTheLastPost AlmostTheLastPost[]
}
```

```js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const userWithPost = await prisma.almostTheLastUser.create({
    data: {
      name: 'Alice',
      AlmostTheLastPost: {
        create: { title: 'Hello World' },
      },
    },
    include: {
      AlmostTheLastPost: true,
    },
  });

  const postBefore = await prisma.almostTheLastPost.findOne({
    where: { id: userWithPost.almostTheLastPost[0].id },
    include: { author: true },
  });

  console.log(
    `Before deleting the \`User\` record, the \`Post\` record looks as follows:\n${JSON.stringify(
      postBefore
    )}`
  );

  const deletedUser = await prisma.almostTheLastUser.delete({
    where: { id: userWithPost.id },
  });

  const postAfter = await prisma.almostTheLastPost.findOne({
    where: { id: postBefore.id },
    include: { author: true },
  });

  console.log(
    `After deleting the \`User\` record, the \`Post\` record looks as follows:\n${JSON.stringify(
      postAfter
    )}`
  );
}

main();
```
Note: `    where: { id: userWithPost.almostTheLastPost[0].id },` is intentionally wrong here, it should be `AlmostTheLastPost` per the schema.

leads to:

```
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql>node index4.js
(node:7136) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at main (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\index4.js:19:48)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:7136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Usually you get a nicer error message when you get something wrong in a query.

---

```
λ prisma2 -v
@prisma/cli          : 2.0.0-alpha.982
Current platform     : windows
Query Engine         : prisma 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\introspection-engine-windows.exe)
```

**Comment by pantharshit00** [comment] 2020-04-03 22:56
This is expected. I don't think we can do anything here. 

If 0 index of an array doesn't exist you will get that error mesasage in javascript.

Ideally you should check in your code for the existance of `almostTheLastPost[0]` before making the client call.

**Comment by timsuchanek** [comment] 2020-11-11 12:18
Closing this, as this is not a bug in Client.

**Closed by timsuchanek** 2020-11-11 12:18 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action, topic: dx
