### ISSUE TITLE
Wrong suggestions for relations

### ISSUE THREAD

**Issue by ManAnRuck** [prisma/prisma-client-js#220] opened 2019-09-09 13:01 UTC
prisma2 init selection:
1. Starter Kit
2. TypeScript
3. GraphQL API
4. SQLite

schema changes
```
model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
  userAddress UserAddress // added
}

// new
model Address {
  id     String @default(cuid()) @id
  street String
  userAddress UserAddress
}

//new
model UserAddress {
  id      String  @default(cuid()) @id
  user    User
  address Address
}
```

in `seed.ts` on creating an address with a new userAddress I get the wrong suggestion `UserAddressCreateWithoutUserInput` instead of `UserAddressCreateWithoutAddressInput`
for new User all is fine

<img width="935" alt="Bildschirmfoto 2019-09-09 um 14 51 02" src="https://user-images.githubusercontent.com/2183135/64532803-8671fc80-d312-11e9-93ae-a5e254581ba0.png">

<img width="925" alt="Bildschirmfoto 2019-09-09 um 14 50 54" src="https://user-images.githubusercontent.com/2183135/64532821-8d007400-d312-11e9-8d20-17f2d500e865.png">

**Comment by pantharshit00** [comment] 2019-09-13 11:06
I can confirm this. Wrong type completion directly implies wrong typings.


![image](https://user-images.githubusercontent.com/22195362/64858115-16ca7d00-d644-11e9-9d2e-ddd643b9e8c5.png)


Reproduction: https://github.com/harshit-test-org/prisma-photon-220

**Comment by timsuchanek** [comment] 2019-11-08 16:45
Internal Note: We're dropping this for now from the sprint, as more investigation is needed.

**Comment by divyenduz** [comment] 2020-01-09 13:39
@pantharshit00 the typing suggestion in your image does look correct right? On address field, the type is `UserAddressCreateWithoutAddressInput`?

**Comment by divyenduz** [comment] 2020-01-09 13:49
![image](https://user-images.githubusercontent.com/746482/72072918-2b1b3f80-32ef-11ea-8c83-aec134250c0e.png)

Based on the schema, I could complete the reproduction from Harshit as: 

![image](https://user-images.githubusercontent.com/746482/72072902-26568b80-32ef-11ea-90a9-d0c6e291a476.png)

It looks correct to me. I am closing this issue, if you disagree, please comment and ping me here with a small reproduction.

**Comment by pantharshit00** [comment] 2020-01-09 14:00
@divyenduz `address` shouldn't be available to us here, instead `user` should be available here, that is why typings are wrong.

**Comment by pantharshit00** [comment] 2020-01-09 14:03
If you try to execute the above code, it will error out:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/22195362/72073885-dbe90500-3316-11ea-98c7-cc6ff5ce060e.png">

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/22195362/72073852-c96ecb80-3316-11ea-98e2-697aba9c65bb.png">

**Comment by divyenduz** [comment] 2020-01-09 14:08
@pantharshit00 As explained in DM, can this be closed? The error you get is a constraint error, please see if it is a bug and create a new issue.

**Comment by pantharshit00** [comment] 2020-01-09 14:09
Yes, I am investigating the error. 

For @ManAnRuck , the above typing is indeed correct but looks misleading at first becuase it is named the same on both ends. I will recommend you to change `userAdress` name on one end to avoid confusion.

**Comment by pantharshit00** [comment] 2020-01-09 14:42
Other one does look like it doesn't happen when I change the user name. I still think this is an issue when both opposing fields are named the same.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/22195362/72076923-6122e880-331c-11ea-8c1d-18e8fff5bd14.png">

**Comment by divyenduz** [comment] 2020-01-17 16:17
Internal note: Divy follows up with Harshit and cleans it up

**Comment by pantharshit00** [comment] 2020-01-29 15:15
Closing in favour of https://github.com/prisma/prisma-client-js/issues/365. Looks like this issue is now fixed

**Closed by pantharshit00** 2020-01-29 15:15 UTC
Labels: bug/2-confirmed, kind/bug
