### ISSUE TITLE
Nested writes don't work on 3rd level with required relation

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-client-js#275] opened 2019-10-28 10:30 UTC
I have these models:

```prisma
model Item {
  id           String   @default(cuid()) @id
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  purchaseDate DateTime?
  name         String
  type         ItemType
  locatedIn    Room?
  price        Float?
}

model ItemType {
  id    String @default(cuid()) @id
  name  String @unique
  items Item[]
}

model Room {
  id          String  @default(cuid()) @id
  name        String  @unique
  items       Item[]
  floor       Floor?
  meetingRoom Boolean
}
```

I now want to create a new `Room` with new `Item`s which all need an `ItemType`. However, the nested write arguments are not available for the `type` field on created `Item`s:

```ts
photon.rooms.create({
  data: {
    items: {
      create: {
        type: {  // ... not available
                 // create/connect ... not available
        }
      }
    }
  }
})
```

![image](https://user-images.githubusercontent.com/4058327/67671465-4c1df680-f976-11e9-99b5-9523537174bd.png)

![image](https://user-images.githubusercontent.com/4058327/67671439-3f010780-f976-11e9-9211-94a2120610ab.png)

**Comment by ManAnRuck** [comment] 2019-11-08 01:41
is this the same like this?
https://github.com/prisma/photonjs/issues/220

**Comment by pantharshit00** [comment] 2019-11-08 09:09
Yes, this does look like a duplicate of #220

**Comment by divyenduz** [comment] 2019-12-09 11:13
Internal note: candidate from bug triaging meeting

**Comment by dpetrick** [comment] 2020-03-16 09:55
This is not reproducible on the engine level, I can write a GraphQL mutation directly against the query engine that allows for creating item types.

**Comment by dpetrick** [comment] 2020-03-16 15:28
To elaborate: 
- Needed to remove `floor Floor?` that snuck in :)
- This query works in the query engine:
```graphql
mutation {
  createOneRoom(data:{
    name: "SomeRoom"
    meetingRoom: true
    items: {
      create:{
        name: "SomeItem"
        type:{
          create:{
            name: "SomeType"
          }
        }
      }
    }
  }) {
    id
  }
}
```

**Comment by janpio** [comment] 2020-03-16 18:14
I adapted the reproduction above to alpha 917:

1. `prisma2 init`
2. Edit `datasource.url` to `"file:dev.db"`
3. Append schema:
	```
	model Item {
	  id           String   @default(cuid()) @id
	  createdAt    DateTime @default(now())
	  updatedAt    DateTime @updatedAt
	  purchaseDate DateTime?
	  name         String
	  type         ItemType
	  locatedIn    Room?
	  price        Float?
	}
	
	model ItemType {
	  id    String @default(cuid()) @id
	  name  String @unique
	  items Item[]
	}
	
	model Room {
	  id          String  @default(cuid()) @id
	  name        String  @unique
	  items       Item[]
	  meetingRoom Boolean
	}
	```
4. `prisma2 migrate save --experimental` and `prisma2 migrate up --experimental`
5. Create `index.js` with content:
	```
	const { PrismaClient } = require('@prisma/client')
	
	const prisma = new PrismaClient()
	
	prisma.Room.create({
	    data: {
	        items: {
	            create: {
	                
	            }
	        }
	    }
	})
	```

This leads to these suggestions:

![image](https://user-images.githubusercontent.com/183673/76787961-52443080-67ba-11ea-9fb1-e92d290eccc8.png)

Is this the expected behavior @nikolasburk and this bug can be closed?

**Comment by nikolasburk** [comment] 2020-03-19 09:11
Looks good to me, thanks a lot 🙏

**Closed** 2020-03-19 09:11 UTC
Labels: bug/2-confirmed, kind/bug
