### ISSUE TITLE
Prisma Query Engine GraphQL error: 'PANIC: Decimal is not a f64'

### ISSUE THREAD

**Issue by ru4sam326** [prisma/prisma-client-js#884] opened 2020-09-17 12:03 UTC
Hi Prisma Team! My Prisma Client just crashed when the number size is bigfloat. This is the report:

Defined some properties like below, Able to save some number like '1000000000000000000000000000.0000' but while retrieving getting parse error and client is getting crashed with 'PANIC: Decimal is not a f64'

{
    amount_incl_tax Float?
    amount_excl_tax Float?
}

## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v14.8.0            | 
| OS       | linux-musl         |
| Prisma   | 2.5.0              |

## Logs
```
2BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bis_latest%2525253DFALSE%2525252C%25252Bis_effective%2525253DFALSE%25252BWHERE%25252Bref%2525253D%25252527C_20-21_00014%25252527%25252529%2525250Aprisma-client%25252BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bstatus%2525253D%25252527Approved%25252527%2525252C%25252Bis_latest%2525253DTRUE%2525252C%25252Bis_effective%2525253Dis_active%25252BWHERE%25252Bid%2525253D%25252527ckf5c3e4d53120sodh3ewtwpd%25252527%25252529%2525250Aprisma-client%25252BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bis_latest%2525253DFALSE%2525252C%25252Bis_effective%2525253DFALSE%25252BWHERE%25252Bref%2525253D%25252527C_20-21_00015%25252527%25252529%2525250Aprisma-client%25252BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bstatus%2525253D%25252527Approved%25252527%2525252C%25252Bis_latest%2525253DTRUE%2525252C%25252Bis_effective%2525253Dis_active%25252BWHERE%25252Bid%2525253D%25252527ckf5f0ypk100590sod35q7e9tu%25252527%25252529%2525250Aprisma-client%25252BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bis_latest%2525253DFALSE%2525252C%25252Bis_effective%2525253DFALSE%25252BWHERE%25252Bref%2525253D%25252527C_20-21_00016%25252527%25252529%2525250Aprisma-client%25252BPrisma%25252BClient%25252Bcall%2525253A%2525250Aprisma-client%25252Bprisma.executeRaw%25252528UPDATE%25252Bpublic.%25252522CntrContract%25252522%25252B%25252BSET%25252Bstatus%2525253D%25252527Approved%25252527%2525252C%25252Bis_latest%2525253DTRUE%2525252C%25252Bis_effective%2525253Dis_active%25252BWHERE%25252Bid%2525253D%25252527ckf6o7ia4146980sod9muyu8ce%25252527%25252529%2525250A%25252560%25252560%25252560%252526title%25253DPANIC%2525253A%25252BDecimal%25252Bis%25252Bnot%25252Ba%25252Bf64.%252526template%25253Dbug_report.md%25250A%25250AIf%252Byou%252Bwant%252Bthe%252BPrisma%252Bteam%252Bto%252Blook%252Binto%252Bit%25252C%252Bplease%252Bopen%252Bthe%252Blink%252Babove%252B%2525F0%25259F%252599%25258F%25250A%25250A%252B%252B%252B%252Bat%252BNodeEngine.handleRequestError%252B%252528%25252Fapp%25252Fnode_modules%25252F%252540prisma%25252Fclient%25252Fruntime%25252Findex.js%25253A1%25253A123522%252529%25250A%252B%252B%252B%252Bat%252B%25252Fapp%25252Fnode_modules%25252F%252540prisma%25252Fclient%25252Fruntime%25252Findex.js%25253A1%25253A138781%25250A%252B%252B%252B%252Bat%252BrunMicrotasks%252B%252528%25253Canonymous%25253E%252529%25250A%252B%252B%252B%252Bat%252BprocessTicksAndRejections%252B%252528internal%25252Fprocess%25252Ftask_queues.js%25253A93%25253A5%252529%25250AplusX%252BExecution%252Bpermissions%252Bof%252

**Comment by pantharshit00** [comment] 2020-09-18 11:47
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by ru4sam326** [comment] 2020-09-19 05:38
> Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

Please find the updated details, let us know if more details are required.

**Comment by pantharshit00** [comment] 2021-01-01 21:25
@ru4sam326 Sorry for the late reply here

I am unable to reproduce this in latest version 2.13.1 

I remember we refactored the logic for that part a bit so this might be already fixed. Please try again with the latest version.

**Comment by timsuchanek** [comment] 2021-01-05 14:22
I assume this is fixed now. If that is not the case, please let us know @ru4sam326 and we will reopen this.

**Closed by timsuchanek** 2021-01-05 14:22 UTC
Labels: bug/0-needs-info, kind/bug, topic: basic reporting issue
