### ISSUE TITLE
Prisma Query Engine has a panic - AWS Lambda + Aurora Serverless

### ISSUE THREAD

**Issue by mrsimply** [prisma/prisma-client-js#791] opened 2020-07-20 12:45 UTC
Hi Prisma Team, 

I'm using Prisma together with Apollo Server Lambda and Aurora Serverless Postgres.
At first glance, everything seems to run smooth and work as expected. Prisma Client fires and resolves queries as requested.

**BUT after about 1 min of inactivity (the Lambda is still warm and Aurora Serverless is alive) I receive the following error:**

```
Error:
Invalid `prisma.user.findOne()` invocation in
/var/task/resolvers/Query.js:29:34

Unknown error in Prisma Client
This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

**Logging to stdout I find the following additional information.**

```
engine {
  error: SocketError: other side closed
  at Socket.<anonymous> (/opt/nodejs/node_modules/prisma-client/runtime/index.js:1:81651)
  at Socket.emit (events.js:322:22)
  at endReadableNT (_stream_readable.js:1187:12)
  at processTicksAndRejections (internal/process/task_queues.js:84:21) {
   code: 'UND_ERR_SOCKET'
  }
}
```

Any ideas, what is wrong here? After receiving the error and firing the next request, everything works as expected again, until I pause another minute. Thank you all in advance. Prisma is great by the way, you're awesome!

**Essential Code:**

```js
// Apollo Server and Lambda Handler 
import { ApolloServer, makeExecutableSchema } from 'apollo-server-lambda';
import { importSchema } from 'graphql-import';
import { PrismaClient } from 'prisma-client';
import { resolvers } from 'resolvers';

const typeDefs = importSchema('schema/schema.graphql');
const schema = makeExecutableSchema({ typeDefs, resolvers });
const prisma = new PrismaClient();
const context = () => ({ prisma });

const server = new ApolloServer({
  schema,
  context,
  playground: { endpoint: '/prod' },
  engine: { sendReportsImmediately: true },
  tracing: false,
  debug: true,
});

const apolloHandler = server.createHandler({
  cors: {
    origin: '*',
    credentials: true,
  },
});

exports.handler = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;
  return apolloHandler(event, context, callback);
};
```

```js
// From my resolvers
export const getUser = async (_parent, { id }, { prisma }, _info) => {
  const where = { id };
  const user = await prisma.user.findOne({ where });
  return user;
};
```

**Some more background:**

- Running Lambda@Edge
- Aurora Serverless Postgres 10.7
- Lambda and Aurora share common VPC with 2x isolated Subnets
- Prisma lives in a Lambda Layer (incorporating it into the Lambda itself has no effect on the error)

**Please see Prisma log report below:**

My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.16.3           | 
| OS       | rhel-openssl-1.0.x |
| Prisma   | 2.2.2              |

## Logs
```
2020-07-20T12:09:55.273Z prisma-client {
  engineConfig: {
    cwd: '/opt/nodejs/node_modules/prisma-client',
    debug: false,
    datamodelPath: '/opt/nodejs/node_modules/prisma-client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/path_to_custom_prisma_client_folder/prisma-client',
      binaryTargets: [Array],
      experimentalFeatures: [Array],
      config: {},
      isCustomOutput: true
    },
    showColors: false,
    logLevel: 'error',
    logQueries: false,
    flags: [],
    clientVersion: '2.2.2',
    enableExperimental: [ 'aggregations' ]
  }
}
2020-07-20T12:09:55.527Z prisma-client Prisma Client call:
2020-07-20T12:09:55.547Z prisma-client prisma.user.findOne({
  where: {
    id: 'f713c7cd-d35d-4b46-820e-5e0ed147895f'
  }
})
2020-07-20T12:09:55.547Z prisma-client Generated request:
2020-07-20T12:09:55.547Z prisma-client query {
  findOneUser(where: {
    id: "f713c7cd-d35d-4b46-820e-5e0ed147895f"
  }) {
    id
    createdAt
    email
    password
  }
}

2020-07-20T12:09:55.686Z plusX Execution permissions of /opt/nodejs/node_modules/prisma-client/query-engine-rhel-openssl-1.0.x are fine
2020-07-20T12:09:57.568Z prisma-client Client Version 2.2.2
2020-07-20T12:09:57.586Z prisma-client Engine Version a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4
2020-07-20T12:10:40.169Z prisma-client Prisma Client call:
2020-07-20T12:10:40.186Z prisma-client prisma.user.findOne({
  where: {
    id: 'f713c7cd-d35d-4b46-820e-5e0ed147895f'
  }
})
2020-07-20T12:10:40.186Z prisma-client Generated request:
2020-07-20T12:10:40.186Z prisma-client query {
  findOneUser(where: {
    id: "f713c7cd-d35d-4b46-820e-5e0ed147895f"
  }) {
    id
    createdAt
    email
    password
  }
}

2020-07-20T12:12:49.367Z prisma-client Prisma Client call:
2020-07-20T12:12:49.386Z prisma-client prisma.user.findOne({
  where: {
    id: 'f713c7cd-d35d-4b46-820e-5e0ed147895f'
  }
})
2020-07-20T12:12:49.386Z prisma-client Generated request:
2020-07-20T12:12:49.386Z prisma-client query {
  findOneUser(where: {
    id: "f713c7cd-d35d-4b46-820e-5e0ed147895f"
  }) {
    id
    createdAt
    email
    password
  }
}

```

**Comment by mrsimply** [comment] 2020-07-22 05:49
No luck after upgrading to Prisma `2.3.0` and re-generating the client. Still the same.

**Comment by pantharshit00** [comment] 2020-07-22 12:45
Closing as a duplicate of #789

**Closed by pantharshit00** 2020-07-22 12:45 UTC
Labels: bug/0-needs-info, kind/bug, topic: aws lambda, topic: deployment-platform
