### ISSUE TITLE
Update graphics to use schema.prisma instead of datamodel.mdl

### ISSUE THREAD

**Issue by 2color** [prisma/prisma-client-js#464] opened 2020-02-04 14:53 UTC
## What

Currently the graphics use `datamodel.mdl`, e.g. 
<img width="751" alt="Screenshot 2020-02-04 at 15 51 58" src="https://user-images.githubusercontent.com/1992255/73755537-7269e400-4766-11ea-8bb7-420b4a5b0135.png">

They should be updated to `schema.prisma`

**Comment by janpio** [comment] 2020-02-04 17:58
Duplicate of https://github.com/prisma/prisma-client-js/issues/447

**Closed by janpio** 2020-02-04 17:58 UTC
Labels: process/candidate
