### ISSUE TITLE
Null foreign keys in where produce wrong result set

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-js#487] opened 2020-02-13 15:43 UTC
```sql
create table teams (
  id serial primary key not null,
  token integer unique not null,
  name text not null
);
create table users (
  id serial primary key not null,
  email text not null unique,
  team_id int references teams (id)
);
insert into teams ("token", "name") values (1, 'a');
insert into users ("email", team_id) values ('a', NULL);
insert into users ("email", "team_id") values ('b', 1);
```

```ts
client.users.findMany({ where: { team_id: null } })
```

Returns the **wrong** results, should return 1, returns both results.

**Comment by pantharshit00** [comment] 2020-02-14 14:00
I can confirm this bug.

Datamodel
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://xxxxx:xxxx@localhost:5432/matt-1?schema=public"
}

model teams {
  id      Int     @id
  name    String
  token   Int     @unique
  userses users[] @relation(references: [team_id])
}

model users {
  email   String @unique
  id      Int    @id
  team_id teams?
}
```

Result of the query:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/22195362/74537349-eb83eb00-4f5f-11ea-9e84-9adc0f88455e.png">

Version used: `prisma2@2.0.0-alpha.781, binary version: a1a562d6f7093ae4ac17ebe3c8d2b387b2ed0598`

**Comment by mavilein** [comment] 2020-02-17 11:04
@dpetrick : Is that an instance of the `null` vs. `undefined` problmem?

**Comment by mavilein** [comment] 2020-02-17 12:08
@pantharshit00 : Your schema looks a bit weird to me. The `references` on the many side should not be possible. When i introspect this db i get:

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:prisma@localhost:5432/postgres?schema=public"
}

model teams {
  id    Int     @id
  name  String
  token Int     @unique
  users users[]
}

model users {
  email   String @unique
  id      Int    @id
  team_id teams?
}
```

**Comment by pantharshit00** [comment] 2020-02-18 17:26
Looks like this issue was specific to `prisma2@2.0.0-alpha.781` and no longer can be reproducable on `preview022`
<img width="780" alt="Screenshot 2020-02-18 at 10 51 24 PM" src="https://user-images.githubusercontent.com/22195362/74761124-7f77ee80-52a1-11ea-9213-cfdd7a2c2e69.png">

I am also no longer able to reproduce:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/22195362/74761316-d54c9680-52a1-11ea-96ac-e1c9091b02eb.png">


I am going to close this now. @matthewmueller can you please also try this with the latest preview.

**Closed by pantharshit00** 2020-02-18 17:26 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate
