### ISSUE TITLE
TypeError: Cannot read property '_clientVersion' of undefined at $connect 2.9.0

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-client-js#926] opened 2020-11-02 09:53 UTC
## Bug description

Reported by @flybayer
```
I just started getting this error today :thinking_face: Any ideas why? I’ve wiped node_modules, etc. Prisma cli & client on 2.9.0
(node:29137) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_clientVersion' of undefined
    at $connect (/Users/b/c/ahts/homeschool-boss/node_modules/@prisma/client/runtime/index.js:201:14906)

Everything still works, even though this error keeps getting printed
```

Note: It should currently not affect any functionality.

**Comment by pantharshit00** [comment] 2020-11-03 14:26
@Jolg42 do you have any reproduction path? I have zero idea how can I reproduce this. I tried a clean install and everything looks fine.

**Comment by Jolg42** [comment] 2020-11-03 14:33
@pantharshit00 I just noticed that a lot of people upvoted this issue 👀 

Unfortunately I do not have a reproduction.

Only thing we have is an internal discussion here https://prisma-company.slack.com/archives/CEYCG2MCN/p1603721719254000

And I asked @flybayer to reproduce with latest 2.10.1 but `I can’t test in 2.10.1 because of https://github.com/prisma/prisma/issues/4098`

If anyone has reproduced with version 2.10 please let us know if you have a reproduction / what kind of environment you have 😃

**Comment by flybayer** [comment] 2020-11-03 18:28
Update: appears to be caused by some code in blitz: https://github.com/blitz-js/legacy-framework/issues/625

**Comment by flybayer** [comment] 2020-11-06 02:16
Was indeed caused by Blitz. You can close this.

**Closed** 2020-11-06 08:49 UTC
Labels: bug/0-needs-info, kind/bug, team/typescript
