### ISSUE TITLE
Reading `Float` returns a different value than the one on the database

### ISSUE THREAD

**Issue by snake575** [prisma/prisma-client-js#761] opened 2020-07-02 18:01 UTC
Hi, I encountered a problem that may be related to #537 and #555

This time the `Float` is created correctly on the database but returns a different value to the client

I did some testing and this occurs on `prisma >= 2.1.0`

### Environment & setup

- OS: `Debian 11 (WSL)`
- Database: `Postgres 12.2`
- Prisma version: `2.1.3`
- Node.js version: `v12.17.0`

### How to reproduce

**Repro**: [snake575/prisma-float-error](https://github.com/snake575/prisma-float-error)

Prisma schema:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Transaction {
  id       Int    @id @default(autoincrement())
  amount   Float
  currency String
}
```

Mutation:
```ts
const transaction = await prisma.transaction.create({
  data: {
    amount: 0.3,
    currency: 'BTC',
  },
})
console.log({ transaction })
```

Returns wrong amount:
```js
{ transaction: { id: 1, amount: 0.30000000000000004, currency: 'BTC' } }
```

### Expected behavior

This was the behavior up until `prisma 2.0.1`:
```js
{ transaction: { id: 1, amount: 0.3, currency: 'BTC' } }
```

**Comment by pantharshit00** [comment] 2020-07-03 13:37
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2903

**Closed by pantharshit00** 2020-07-03 13:37 UTC
