### ISSUE TITLE
tslint: Invalid 'await' of a non-Promise value

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/prisma-client-js#157] opened 2019-07-29 11:54 UTC
I see the following error when using photon:

```
Invalid 'await' of a non-Promise value. (await-promise)
```

![Screenshot 2019-07-29 at 13 47 39](https://user-images.githubusercontent.com/1537724/62046252-c8822b80-b207-11e9-9fbb-b751aa9e78c5.png)

However, if I specify `include` property, there is no error.

![Screenshot 2019-07-29 at 13 52 02](https://user-images.githubusercontent.com/1537724/62046387-1008b780-b208-11e9-9856-17141c7e6bf5.png)

This happens to every method, so I suppose there's something wrong with generated types.

Here're the generated types for this method.

```ts
findOne<T extends FindOneBatchArgs>(
    args: Subset<T, FindOneBatchArgs>
  ): T extends FindOneBatchArgsRequired
    ? 'Please either choose `select` or `include`'
    : T extends FindOneBatchSelectArgs
    ? Promise<BatchGetSelectPayload<ExtractFindOneBatchSelectArgs<T>>>
    : T extends FindOneBatchIncludeArgs
    ? Promise<BatchGetIncludePayload<ExtractFindOneBatchIncludeArgs<T>>>
    : BatchClient<Batch>
```

**Comment by timsuchanek** [comment] 2019-07-29 13:19
Thanks @sameoldmadness for reporting! Which version of TypeScript are you using?
How does your data model for this part look like?

**Comment by sameoldmadness** [comment] 2019-07-29 22:27
I've created a repo that illustrates the issue. It's basically `prisma2 init` with configured tslint.

Seems like it's an expected behaviour of [`await-promise` rule](https://palantir.github.io/tslint/rules/await-promise/):

> Note that this rule doesn’t check for type assignability or compatibility; it just checks type reference names.

So it can be fixed with the following adjustment to `tslint` config:

```json
{
    "rules": {
        "await-promise": [true, "BatchClient"]
    }
}
```

Which is tedious because this should be done for each model.

It can be fixed on `photonjs` side as well: `BatchClient<Batch>` should be replaced with `BatchClient<Batch> & Promise<Batch>`. 

Not sure if it's worth it though since [tslint is going to be deprecated soon](https://github.com/palantir/tslint/issues/4534).

**Comment by janpio** [comment] 2019-09-02 15:35
Can you please confirm the reproduction here @pantharshit00? Thanks.

**Comment by pantharshit00** [comment] 2019-09-03 13:09
![image](https://user-images.githubusercontent.com/22195362/64175941-06631700-ce7a-11e9-848f-5d91c151cc6a.png)

I can confirm this but it is up to @timsuchanek to determine if this is just a linter nitpick or an actual issue.

**Comment by pantharshit00** [comment] 2019-09-03 13:09
Marking this as a bug for now

**Comment by divyenduz** [comment] 2020-01-09 13:33
I changed this from being a bug to a docs issue. Photon returns a promise like object but not an actual Promise, this needs to be documented as suggested in the rules documentation: https://palantir.github.io/tslint/rules/await-promise/

**Comment by nikolasburk** [comment] 2020-02-17 12:29
It's currently unclear to me what exactly we should document here. I don't really want to add specific docs for TSLint since it's [deprecated](https://github.com/palantir/tslint/issues/4534).

Is there an equivalent setting for ESLint? (I was looking for it but didn't find anything that looked identical)? @sameoldmadness would love to get your input on how/where you think the documentation could be improved here 🙂

**Comment by Jolg42** [comment] 2020-02-19 10:46
@nikolasburk  I think the replacement for TSLint is https://github.com/typescript-eslint/typescript-eslint

**Comment by Jolg42** [comment] 2020-02-19 10:49
The conflicting rule from TSLint is also used in ESLint TypeScript apparently https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md

**Comment by Jolg42** [comment] 2020-02-19 11:59
Potential solutions:
- (Recommended) Upgrade to TypeScript ESLint (the `await-thenable` rule is compatible with our code)
- Disable `await-promise` rule for TSLint
- Add `/* tslint:disable:await-promise */` (Disables the listed rules for the rest of the file)
- Add `// tslint:disable-next-line:await-promise (Disables the listed rules for the next line)

**Closed** 2020-02-19 12:07 UTC
Labels: kind/docs

**Comment by janpio** [comment] 2020-02-19 12:41
What was done here to solve/close this?

**Comment by Jolg42** [comment] 2020-02-19 12:55
@janpio Nothing :) TSLint is officially deprecated, upgrading to TypeScript ESLint fixes it.
