### ISSUE TITLE
Allow where clause in count method

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma-client-js#407] opened 2020-01-14 14:20 UTC
Hi. While Photon provides a count method, it does not support a where clause currently. For a real world scenario, you won't count all records in the model but you will match it against a condition.

For eg. count all the employees of an organization where organization is the condition

While this is now being done by findMany, that is definitely not the solution. Would be great to have a where for count. This is kind of critical to have.

**Comment by pantharshit00** [comment] 2020-01-22 17:07
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #252

**Closed by pantharshit00** 2020-01-22 17:07 UTC
