### ISSUE TITLE
How to use on Raspberry Pi 

### ISSUE THREAD

**Issue by Suniron** [prisma/prisma-client-js#460] opened 2020-02-01 23:48 UTC
Hi,

How can i use Prisma 2 and its client on a Raspberry pi 3b+ ?

Thanks 😊

**Comment by pantharshit00** [comment] 2020-02-03 10:47
Hi,

Thanks for reporting this! It has already been reported by you before, so I am going to close this as a duplicate ofhttps://github.com/prisma/prisma2/issues/1505

**Closed by pantharshit00** 2020-02-03 10:47 UTC
