### ISSUE TITLE
Prisma's query engine does not restart after crashing

### ISSUE THREAD

**Issue by wSedlacek** [prisma/prisma-client-js#678] opened 2020-05-04 23:00 UTC
## Bug description

Prisma's query engine does not restart after crashing.
In my case the query engine appears to be crashing when running out of memory (which is to be expected with how large my dataset is) however after it crashes all query's respond with `invalid prisma.findMany() invocation` or whatever method is called.

Since I am exposing this API via GraphQL I am not in control over how complex the queries may be.
I am working on adding a cost calculator to avoid calls like this, but they still may happen or too many people may make large queries that alone wouldn't overflow my RAM but together might.
The real problem for me is how Prisma reacts to crashing, not that it crashes.

## How to reproduce
In my case I have a database of 10k cards, 2k sets of cards.
Each card is in about 10 sets and each set has about 50 cards.
So if query is made for all the cards, all the sets of those cards and all the cards in those sets it ends up with about 5 million card rows which exceeds the 4GB of RAM I am running on my server thus crashing the query engine.
All future request to the API return an error of `invalid prisma.findMany() invocation` until the API is restarted manually as it only crashes the query engine but not the entire API.

## Expected behavior
I would expect that the query engine to be restarted on the next request after crashing instead of returning `invalid prisma.findMany() invocation`.
Alternatively I would expect it to crash the entire application so it can be automatically restarted.
It is the fact that the API lives while the query engine is dead failing all calls that is the real problem for me.

## Prisma information
```prisma
model Card {
  id               String              @default(cuid()) @id
  sets             Set[]               @relation(references: [id])
  prints           CardPrint[]
  <about 20 other keys>
}

model Set {
  id            String             @id
  pageName      String             @unique
  cards         Card[]
  cardPrints    CardPrint[]
  <about 20 other keys>
}
```

## Environment & setup

- OS: Ubuntu 20.04 (under Node Docker image)
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.4
- Node.js version: 14.1.0

## Similar issues
- #435

**Comment by Sytten** [comment] 2020-05-05 00:05
Duplicate of https://github.com/prisma/prisma/issues/2366 and https://github.com/prisma/prisma/issues/2100

**Comment by wSedlacek** [comment] 2020-05-05 04:57
Thank you for finding issue #2100 for me. I was looking in this repo for issues so didn't come across that one. Is the core prisma repo the proper repo to file issues for Prisma 2 in?

**Closed** 2020-05-05 05:03 UTC

**Comment by Sytten** [comment] 2020-05-05 13:30
@wSedlacek Yeah the client moved back into the prisma repo a while back, so the other repo is not super useful.

**Comment by janpio** [comment] 2020-05-06 11:54
> @wSedlacek Yeah the client moved back into the prisma repo a while back, so the other repo is not super useful.

This is not correct @Sytten. Prisma Client (JS) specific issues still belong in this repository. The Engines behaving in unexpected ways can be caused both by the Client or Prisma itself - and in this case it is Prisma.

That being said: Just open the issue in one of the repos, and we will make sure that it ends up in the place where it makes most sense to us for our internal organisation. No need for you to worry, so `prisma/prisma` is always a good location.
