### ISSUE TITLE
Improve sqlite error messages

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#731] opened 2020-06-11 10:40 UTC
Also the sqlite error messages are not the best, they are not colorized and it's either kind of hidden or doesn't tell you what went wrong in details.

First one
<img width="808" alt="Screen Shot 2020-04-24 at 15 19 24" src="https://user-images.githubusercontent.com/1328733/80221817-1d8f8880-8646-11ea-8b10-11a6fb087ca7.png">

Second one
<img width="734" alt="Screen Shot 2020-04-24 at 15 59 16" src="https://user-images.githubusercontent.com/1328733/80221846-27b18700-8646-11ea-8d59-e967b213d367.png">

_Originally posted by @Jolg42 in https://github.com/prisma/prisma/issues/2295#issuecomment-619036556_

**Comment by timsuchanek** [comment] 2020-06-19 10:03
As of now I can't reproduce. @Jolg42 would be great, if you could post a reproduction repo.

**Comment by Jolg42** [comment] 2020-06-22 10:18
[repro-scalar-error-message-Tim.zip](https://github.com/prisma/prisma-client-js/files/4812611/repro-scalar-error-message-Tim.zip)

And then do
```
yarn
ts-node index.ts
```

Running `ts-node index.ts` created the `prisma/dev.db` SQLite file but completely empty and this error appears.

```
Creating user
(node:66810) UnhandledPromiseRejectionWarning: Error: 
Invalid `client.user.create()` invocation in
/Users/j42/Dev/repro/repro-scalar-error-message/index.ts:10:40

   6 const email = [object Object],[object Object],[object Object];
   7 
   8 async function main() {
   9   console.log("Creating user");
→ 10   const createUser = await client.user.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: dev.User"))) })
```

**Comment by timsuchanek** [comment] 2020-06-25 12:41
GitHub should have closed this, but yeah.
Thanks for the context, it's fixed now!
The problem was our code highlighter, we also now have a proper unit test for the stack printer.
It's available in `dev`.

**Closed by timsuchanek** 2020-06-25 12:41 UTC
Labels: bug/2-confirmed, kind/bug, process/next-milestone, team/typescript
