### ISSUE TITLE
Error in query graph construction

### ISSUE THREAD

**Issue by ManAnRuck** [prisma/prisma-client-js#568] opened 2020-03-08 18:27 UTC
I get the following error when I try to upsert an item.
```
Error: 
Invalid `prisma.organizations.upsert()` invocation in
/Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:79:26

Error in query graph construction: InputError("The `set` argument was not provided for field `post` on `Organization`")
    at PrismaClientFetcher.request (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/index.js:90:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

<img width="1081" alt="Bildschirmfoto 2020-03-08 um 19 17 17" src="https://user-images.githubusercontent.com/2183135/76168584-77f58800-6171-11ea-84f8-b033fd380768.png">

it's just an array of strings.
and the code intelligence shows me only the set property

<img width="253" alt="Bildschirmfoto 2020-03-08 um 19 24 56" src="https://user-images.githubusercontent.com/2183135/76168745-c22b3900-6172-11ea-8302-00c3f74e5cee.png">

```ts
        const organizationPrepared = {
          ...organization,
          body: undefined,
          'STERNBERG:gruppierung': undefined,
          'STERNBERG:sortierung': undefined,
          membership: undefined,
          meeting: undefined,
          location: undefined,
          keyword: undefined,
          subOrganizationOf: undefined,
          post: {
            set: organization.post,
          },
        };
        return prisma.organization
          .upsert({
            create: organizationPrepared,
            update: organizationPrepared,
            where: { id: organizationPrepared.id },
          })
          .catch(console.log);
      });
```
https://github.com/ManAnRuck/oparl-prisma/blob/42d77996b01049070c497bb847e1c4d8a7e0ca32/src/import/index.ts#L33-L35

```
model Organization {
    id                String        @id
    type              String
    // Body Body
    name              String?
    // membership Membership[]
    // meeting Meeting[]
    // consultation any
    shortName         String?
    post              String[]
    subOrganizationOf Organization?
    organizationType  String?
    classification    String?
    startDate         String?
    endDate           String?
    website           String?
    // # location any
    // externalBody Body
    license           String?
    keyword           String[]
    created           String?
    modified          String?
    web               String?
    deleted           Boolean?
}
```

https://github.com/ManAnRuck/oparl-prisma/blob/42d77996b01049070c497bb847e1c4d8a7e0ca32/prisma/schema.prisma#L10-L34

repo (branch: `issue/set-error`): https://github.com/ManAnRuck/oparl-prisma/tree/issue/set-error

**Comment by ManAnRuck** [comment] 2020-03-13 12:59
@pantharshit00 thank you for checking :)

I now update the Prisma packages and get the same issue :'(

<img width="291" alt="Bildschirmfoto 2020-03-13 um 13 59 32" src="https://user-images.githubusercontent.com/2183135/76622992-e2704480-6532-11ea-94dc-86adb09cf580.png">

**Comment by pantharshit00** [comment] 2020-03-22 20:21
Sorry for the delay here @ManAnRuck 

I tried this again and was still unsuccessful in reproducing this problem.

Can you please try the current alpha version(`npm install -g prisma2@alpha`) and see if that fixes this issue for you?

If this is still persistent, please paste enable debug out by executing `export DEBUG=*`.After that run your script to reproduce the problem. That can help us the cause of this exception.

**Comment by ManAnRuck** [comment] 2020-03-24 19:52
still not works :/

<details><summary>Versions</summary>

```
├─ @prisma/client@2.0.0-alpha.957
├─ @types/aws-lambda@8.10.13
├─ @types/body-parser@1.19.0
├─ @types/connect@3.4.33
├─ @types/cors@2.8.6
├─ @types/express-serve-static-core@4.17.2
├─ @types/express@4.17.3
├─ @types/graphql-deduplicator@2.0.0
├─ @types/graphql@14.5.0
├─ @types/mime@2.0.1
├─ @types/node@12.12.29
├─ @types/range-parser@1.2.3
├─ @types/serve-static@1.13.3
├─ @types/strip-bom@3.0.0
├─ @types/strip-json-comments@0.0.30
├─ @types/ws@7.2.3
├─ @types/zen-observable@0.5.4
├─ @wry/equality@0.1.9
├─ accepts@1.3.7
├─ apollo-cache-control@0.1.1
├─ apollo-link@1.2.13
├─ apollo-server-core@1.4.0
├─ apollo-server-express@1.4.0
├─ apollo-server-lambda@1.3.6
├─ apollo-server-module-graphiql@1.4.0
├─ apollo-tracing@0.1.4
├─ apollo-upload-server@7.1.0
├─ apollo-utilities@1.3.3
├─ arg@4.1.3
├─ array-find-index@1.0.2
├─ array-flatten@1.1.1
├─ async-limiter@1.0.1
├─ axios-cache-adapter@2.5.0
├─ axios-rate-limit@1.2.1
├─ axios@0.19.2
├─ backo2@1.0.2
├─ balanced-match@1.0.0
├─ body-parser-graphql@1.1.0
├─ body-parser@1.19.0
├─ brace-expansion@1.1.11
├─ buffer-from@1.1.1
├─ busboy@0.2.14
├─ bytes@3.1.0
├─ cache-control-esm@1.0.0
├─ camelcase-keys@2.1.0
├─ camelcase@5.3.1
├─ concat-map@0.0.1
├─ content-disposition@0.5.3
├─ content-type@1.0.4
├─ cookie-signature@1.0.6
├─ cookie@0.4.0
├─ core-js@2.6.11
├─ core-util-is@1.0.2
├─ cors@2.8.5
├─ currently-unhandled@0.4.1
├─ dateformat@1.0.12
├─ debounce@1.2.0
├─ debug@2.6.9
├─ decamelize@1.2.0
├─ denque@1.4.1
├─ depd@1.1.2
├─ deprecated-decorator@0.1.6
├─ destroy@1.0.4
├─ dicer@0.2.5
├─ diff@4.0.2
├─ dynamic-dedupe@0.3.0
├─ ee-first@1.1.1
├─ encodeurl@1.0.2
├─ error-ex@1.3.2
├─ escape-html@1.0.3
├─ etag@1.8.1
├─ eventemitter3@3.1.2
├─ express@4.17.1
├─ fast-json-stable-stringify@2.1.0
├─ filewatcher@3.0.1
├─ finalhandler@1.1.2
├─ find-up@1.1.2
├─ follow-redirects@1.5.10
├─ forwarded@0.1.2
├─ fresh@0.5.2
├─ fs-capacitor@1.0.1
├─ fs-extra@8.1.0
├─ fs.realpath@1.0.0
├─ get-stdin@4.0.1
├─ glob@7.1.6
├─ graceful-fs@4.2.3
├─ graphql-deduplicator@2.0.5
├─ graphql-extensions@0.0.10
├─ graphql-import@0.7.1
├─ graphql-middleware@4.0.1
├─ graphql-playground-html@1.6.12
├─ graphql-playground-middleware-express@1.7.11
├─ graphql-playground-middleware-lambda@1.7.12
├─ graphql-subscriptions@0.5.8
├─ graphql-tools@4.0.7
├─ graphql-upload@8.1.0
├─ graphql-yoga@1.18.3
├─ graphql@14.6.0
├─ growly@1.3.0
├─ hosted-git-info@2.8.8
├─ http-errors@1.7.3
├─ iconv-lite@0.4.24
├─ indent-string@2.1.0
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ ipaddr.js@1.9.1
├─ is-arrayish@0.2.1
├─ is-finite@1.1.0
├─ is-utf8@0.2.1
├─ is-wsl@1.1.0
├─ isarray@0.0.1
├─ isexe@2.0.0
├─ iterall@1.3.0
├─ jsonfile@4.0.0
├─ load-json-file@1.1.0
├─ lodash@4.17.15
├─ loud-rejection@1.6.0
├─ make-error@1.3.6
├─ map-obj@1.0.1
├─ media-typer@0.3.0
├─ meow@3.7.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.43.0
├─ mime-types@2.1.26
├─ mime@1.6.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mkdirp@0.5.1
├─ ms@2.0.0
├─ negotiator@0.6.2
├─ nexus-prisma@0.11.1
├─ nexus@0.12.0-rc.14
├─ node-notifier@5.4.3
├─ normalize-package-data@2.5.0
├─ object-assign@4.1.1
├─ object-path@0.11.4
├─ on-finished@2.3.0
├─ once@1.4.0
├─ oparl-sdk@0.0.1-alpha.1
├─ parse-json@2.2.0
├─ parseurl@1.3.3
├─ path-exists@2.1.0
├─ path-is-absolute@1.0.1
├─ path-parse@1.0.6
├─ path-to-regexp@0.1.7
├─ path-type@1.1.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ pluralize@8.0.0
├─ prisma2@2.0.0-alpha.957
├─ proxy-addr@2.0.6
├─ qs@6.7.0
├─ range-parser@1.2.1
├─ raw-body@2.4.0
├─ read-pkg-up@1.0.1
├─ read-pkg@1.1.0
├─ readable-stream@1.1.14
├─ redent@1.0.0
├─ redis-commands@1.5.0
├─ redis-errors@1.2.0
├─ redis-parser@3.0.0
├─ redis@3.0.2
├─ repeating@2.0.1
├─ resolve-from@4.0.0
├─ resolve@1.15.1
├─ rimraf@2.7.1
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ semver@5.7.1
├─ send@0.17.1
├─ serve-static@1.14.1
├─ setprototypeof@1.1.1
├─ shellwords@0.1.1
├─ signal-exit@3.0.2
├─ source-map-support@0.5.16
├─ source-map@0.6.1
├─ spdx-correct@3.1.0
├─ spdx-exceptions@2.2.0
├─ spdx-expression-parse@3.0.0
├─ spdx-license-ids@3.0.5
├─ statuses@1.5.0
├─ streamsearch@0.1.2
├─ string_decoder@0.10.31
├─ strip-bom@3.0.0
├─ strip-indent@1.0.1
├─ strip-json-comments@2.0.1
├─ subscriptions-transport-ws@0.9.16
├─ symbol-observable@1.2.0
├─ toidentifier@1.0.0
├─ tree-kill@1.2.2
├─ trim-newlines@1.0.0
├─ ts-invariant@0.4.4
├─ ts-node-dev@1.0.0-pre.44
├─ ts-node@8.8.1
├─ tsconfig@7.0.0
├─ tslib@1.11.1
├─ type-is@1.6.18
├─ typescript@3.8.3
├─ universalify@0.1.2
├─ unpipe@1.0.0
├─ utils-merge@1.0.1
├─ uuid@3.4.0
├─ validate-npm-package-license@3.0.4
├─ vary@1.1.2
├─ which@1.3.1
├─ wrappy@1.0.2
├─ ws@5.2.2
├─ xtend@4.0.2
├─ yn@3.1.1
├─ zen-observable-ts@0.8.20
└─ zen-observable@0.8.15
```
</details>

<details><summary>Debug</summary>

```
  prisma-client { engineConfig:
  prisma-client    { cwd: '/Users/manuelruck/Jobs/openData/oparlPrisma/prisma',
  prisma-client      debug: false,
  prisma-client      datamodelPath:
  prisma-client       '/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/schema.prisma',
  prisma-client      prismaPath: undefined,
  prisma-client      datasources: [],
  prisma-client      generator:
  prisma-client       { name: 'client',
  prisma-client         provider: 'prisma-client-js',
  prisma-client         output:
  prisma-client          '/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client',
  prisma-client         binaryTargets: [],
  prisma-client         config: {} },
  prisma-client      showColors: false,
  prisma-client      logLevel: undefined,
  prisma-client      logQueries: undefined,
  prisma-client      env: {},
  prisma-client      flags: [] } } +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/manuelruck/Jobs/openData/oparlPrisma/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +2ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +2ms
  express:router:layer new '/' +36ms
  express:router use '/' corsMiddleware +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +1ms
  express:router:layer new '/' +69ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  prisma-client { engineConfig:
  prisma-client    { cwd: '/Users/manuelruck/Jobs/openData/oparlPrisma/prisma',
  prisma-client      debug: false,
  prisma-client      datamodelPath:
  prisma-client       '/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/schema.prisma',
  prisma-client      prismaPath: undefined,
  prisma-client      datasources: [],
  prisma-client      generator:
  prisma-client       { name: 'client',
  prisma-client         provider: 'prisma-client-js',
  prisma-client         output:
  prisma-client          '/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client',
  prisma-client         binaryTargets: [],
  prisma-client         config: {} },
  prisma-client      showColors: false,
  prisma-client      logLevel: undefined,
  prisma-client      logQueries: undefined,
  prisma-client      env: {},
  prisma-client      flags: [] } } +524ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  getos { platform: 'darwin', libssl: undefined } +1ms
  follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/rim4883/webservice/oparl/v1.1/body/1',
  method: 'GET',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'User-Agent': 'axios/0.19.2' },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'sdnetrim.kdvz-frechen.de',
  port: null,
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Function],
        ClientRequest: [Function],
        IncomingMessage: [Function],
        OutgoingMessage: [Function],
        Server: [Function],
        ServerResponse: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request],
        maxHeaderSize: [Getter],
        globalAgent: [Getter/Setter] },
     'https:':
      { Agent: [Function],
        globalAgent: [Agent],
        Server: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] } } } +0ms
  follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/rim4883/webservice/oparl/v1.1/body/1/organization',
  method: 'GET',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'User-Agent': 'axios/0.19.2' },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'sdnetrim.kdvz-frechen.de',
  port: null,
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Function],
        ClientRequest: [Function],
        IncomingMessage: [Function],
        OutgoingMessage: [Function],
        Server: [Function],
        ServerResponse: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request],
        maxHeaderSize: [Getter],
        globalAgent: [Getter/Setter] },
     'https:':
      { Agent: [Function],
        globalAgent: [Agent],
        Server: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] } } } +265ms
  prisma-client Prisma Client call: +1s
  prisma-client prisma.organization.upsert({
  prisma-client   create: {
  prisma-client     id: 'https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1',
  prisma-client     type: 'https://schema.oparl.org/1.1/Organization',
  prisma-client     body: undefined,
  prisma-client     name: 'Bürgerservice und Interne Dienste',
  prisma-client     organizationType: 'Dienststellen',
  prisma-client     startDate: '2004-01-28',
  prisma-client     created: '2011-02-21T08:59:44+01:00',
  prisma-client     modified: '2015-04-14T00:00:00+02:00',
  prisma-client     'STERNBERG:gruppierung': undefined,
  prisma-client     'STERNBERG:sortierung': undefined,
  prisma-client     membership: undefined,
  prisma-client     meeting: undefined,
  prisma-client     location: undefined,
  prisma-client     keyword: undefined,
  prisma-client     subOrganizationOf: undefined,
  prisma-client     post: {
  prisma-client       set: undefined
  prisma-client     }
  prisma-client   },
  prisma-client   update: {
  prisma-client     id: 'https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1',
  prisma-client     type: 'https://schema.oparl.org/1.1/Organization',
  prisma-client     body: undefined,
  prisma-client     name: 'Bürgerservice und Interne Dienste',
  prisma-client     organizationType: 'Dienststellen',
  prisma-client     startDate: '2004-01-28',
  prisma-client     created: '2011-02-21T08:59:44+01:00',
  prisma-client     modified: '2015-04-14T00:00:00+02:00',
  prisma-client     'STERNBERG:gruppierung': undefined,
  prisma-client     'STERNBERG:sortierung': undefined,
  prisma-client     membership: undefined,
  prisma-client     meeting: undefined,
  prisma-client     location: undefined,
  prisma-client     keyword: undefined,
  prisma-client     subOrganizationOf: undefined,
  prisma-client     post: {
  prisma-client       set: undefined
  prisma-client     }
  prisma-client   },
  prisma-client   where: {
  prisma-client     id: 'https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1'
  prisma-client   }
  prisma-client }) +2ms
  prisma-client Generated request: +34ms
  prisma-client mutation {
  prisma-client   upsertOneOrganization(
  prisma-client     create: {
  prisma-client       id: "https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1"
  prisma-client       type: "https://schema.oparl.org/1.1/Organization"
  prisma-client       name: "Bürgerservice und Interne Dienste"
  prisma-client       organizationType: "Dienststellen"
  prisma-client       startDate: "2004-01-28"
  prisma-client       created: "2011-02-21T08:59:44+01:00"
  prisma-client       modified: "2015-04-14T00:00:00+02:00"
  prisma-client       post: {
  prisma-client 
  prisma-client       }
  prisma-client     }
  prisma-client     update: {
  prisma-client       id: "https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1"
  prisma-client       type: "https://schema.oparl.org/1.1/Organization"
  prisma-client       name: "Bürgerservice und Interne Dienste"
  prisma-client       organizationType: "Dienststellen"
  prisma-client       startDate: "2004-01-28"
  prisma-client       created: "2011-02-21T08:59:44+01:00"
  prisma-client       modified: "2015-04-14T00:00:00+02:00"
  prisma-client       post: {
  prisma-client 
  prisma-client       }
  prisma-client     }
  prisma-client     where: {
  prisma-client       id: "https://sdnetrim.kdvz-frechen.de/rim4883/webservice/oparl/v1.1/body/1/organization/3-1"
  prisma-client     }
  prisma-client   ) {
  prisma-client     id
  prisma-client     type
  prisma-client     name
  prisma-client     shortName
  prisma-client     post
  prisma-client     organizationType
  prisma-client     classification
  prisma-client     startDate
  prisma-client     endDate
  prisma-client     website
  prisma-client     license
  prisma-client     keyword
  prisma-client     created
  prisma-client     modified
  prisma-client     web
  prisma-client     deleted
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine { PRISMA_DML_PATH:
  engine    '/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '60110',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[]' } +0ms
  engine { cwd: '/Users/manuelruck/Jobs/openData/oparlPrisma/prisma' } +0ms
  plusX Execution permissions of /Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/runtime/query-engine-darwin are fine +0ms
  engine { flags: [ '--enable-raw-queries' ] } +2ms
  engine stderr Printing to stderr for debugging +51ms
  engine stderr Listening on 127.0.0.1:60110 +0ms
  engine stdout { timestamp: 'Mar 24 20:50:22.688',
  level: 'INFO',
  target: 'quaint::pooled',
  fields:
   { message: 'Starting a postgresql pool with 5 connections.' } } +15ms
  engine stdout { timestamp: 'Mar 24 20:50:22.702',
  level: 'INFO',
  target: 'prisma::server',
  fields:
   { message: 'Started http server on 127.0.0.1:60110',
     'log.target': 'prisma::server',
     'log.module_path': 'prisma::server',
     'log.file': 'query-engine/prisma/src/server.rs',
     'log.line': 109 } } +11ms
  engine { error:
  engine    Error: Error in query graph construction: InputError("The `set` argument was not provided for field `post` on `Organization`")
  engine        at NodeEngine.graphQLToJSError (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/runtime/index.js:1:18853)
  engine        at currentRequestPromise.then.e (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/runtime/index.js:1:16340)
  engine        at process._tickCallback (internal/process/next_tick.js:68:7) } +43ms
  printStack callsite Error
    at Object.s [as Organization] (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/runtime/index.js:1:48389)
    at Object.n.(anonymous function).n [as upsert] (/Users/manuelruck/Jobs/openData/oparlPrisma/node_modules/@prisma/client/runtime/index.js:1:50015)
    at /Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:79:26
    at step (/Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:44:23)
    at Object.next (/Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:25:53)
    at fulfilled (/Users/manuelruck/Jobs/openData/oparlPrisma/src/import/index.ts:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```
</details>

**Comment by ManAnRuck** [comment] 2020-03-25 08:22
it looks like it works when I set the `post` property with `post: { set: post ? post : [] },`

**Comment by pantharshit00** [comment] 2020-04-03 22:28
Thanks for the additional insight, now I can reproduce this now with a much simpler schema.

I think this might be reoccurrence of https://github.com/prisma/prisma-client-js/issues/422.

When pass undefined to a set operation, the following panic occurs:
![image](https://user-images.githubusercontent.com/22195362/78409579-aa3abe00-7627-11ea-98ca-7a5dfc5d14e1.png)

When pass null to the set operation, the following panic happens:
![image](https://user-images.githubusercontent.com/22195362/78409804-449b0180-7628-11ea-81e7-57cf464a3d5c.png)

Schema used:
```prisma
model User {
  id String @id @default(cuid())
  names String[]
}
```

Client call:
```ts
// replace null with undefined accordingly
  const reproCall = await db.user.upsert({
    create: {
      names: { set: undefined },
    },
    where: {
      id: "something",
    },
    update: {
      names: { set: undefined },
    },
  });
```

Version information:
```
@prisma/cli          : 2.0.0-alpha.1031
Current platform     : darwin
Query Engine         : prisma 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/harshit/code/reproductions/issue-568/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/harshit/code/reproductions/issue-568/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/harshit/code/reproductions/issue-568/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by tomhoule** [comment] 2020-04-17 07:47
I reproduced the same setup and input, and I can now confirm we return a known error with the message "Missing the required argument `set` for field `post` on `Organization`." and error code P2013. Since I think this is what we wanted, I will close this issue.

**Closed by tomhoule** 2020-04-17 07:47 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, team/typescript
