### ISSUE TITLE
It is possible to have empty values in database source url

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#318] opened 2019-12-03 14:19 UTC
Right now we are able to have empty values in the datasource url(either by hard coding or by environment variable) which cause a runtime error when we try to execute the client.

Schema:
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = ""
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}
```

Error: 
![image](https://user-images.githubusercontent.com/22195362/70058959-e91f1f80-1605-11ea-8775-ea90ddfbb116.png)

Refer: https://github.com/prisma/photonjs/issues/305#issuecomment-559559485

**Comment by janpio** [comment] 2019-12-03 19:00
What would correct or expected behaviour be in this case?

**Comment by steebchen** [comment] 2019-12-04 20:03
This probably should be disallowed, it should return a clear error that you have to specify a datasource URL. Related: https://github.com/prisma-labs/nexus-prisma/issues/546#issuecomment-561808751

**Comment by RafaelKr** [comment] 2019-12-04 20:54
Thank you @steebchen 

@janpio and @pantharshit00 please also have a look at this comment https://github.com/prisma-labs/nexus-prisma/issues/546#issuecomment-561834082

**Comment by pantharshit00** [comment] 2019-12-05 10:01
> This probably should be disallowed, it should return a clear error that you have to specify a datasource URL. Related: prisma-labs/nexus-prisma#546 (comment)

Either that should be the case or we could use the defaults for example `postgresql://localhost:5432/postgres?schema=public` is used by many clients as the default value.

**Comment by RafaelKr** [comment] 2019-12-05 10:19
> > This probably should be disallowed, it should return a clear error that you have to specify a datasource URL. Related: [prisma-labs/nexus-prisma#546](https://github.com/prisma-labs/nexus-prisma/issues/546) (comment)
> 
> Either that should be the case or we could use the defaults for example `postgresql://localhost:5432/postgres?schema=public` is used by many clients as the default value.

In my opinion this should be a hard error. Then you can't forget to set the connection string when switching environments.

**Comment by steebchen** [comment] 2019-12-19 17:07
@sorenbs You're assigned to make a product decision here. For me, it's clear that an empty value should be disallowed, especially because it will result in unclear errors. If we ever have default connection string values, we can re-open for discussion, but for now I think this should be disallowed.

**Comment by janpio** [comment] 2020-03-07 19:34
A decision has been made by @sorenbs: Just disallow it

**Comment by divyenduz** [comment] 2020-03-10 14:22
This has two aspects wrt the errors spec: 

Static empty value: this should be disallowed by the schema parser and would be covered via https://github.com/prisma/prisma-engines/blob/master/libs/user-facing-errors/src/common.rs#L180-L184

Depending on what the default error from schema parser is, we might want to handle this separately but I think SchemaParserError (P1012) should suffice. 

Dynamic empty value: this can be set via an environment variable, in this case schema parser and `prisma2 generate` command cannot know that the value is empty and the earliest point where the value is resolved is Prisma client's constructor. At that point it can fail with an error citing fulfillment of the specific env var (related issue https://github.com/prisma/specs/issues/369).

**Comment by divyenduz** [comment] 2020-03-12 14:13
![image](https://user-images.githubusercontent.com/746482/76530413-b3f25b00-6499-11ea-9650-1afd77f9145f.png)

![image](https://user-images.githubusercontent.com/746482/76530439-bd7bc300-6499-11ea-92ce-9b756c1158df.png)

![image](https://user-images.githubusercontent.com/746482/76530379-a937c600-6499-11ea-9d30-5dfdcd1d58f5.png)

**Comment by mavilein** [comment] 2020-04-16 21:28
Fixed in https://github.com/prisma/prisma-engines/pull/679

**Closed by mavilein** 2020-04-16 21:28 UTC
Labels: bug/2-confirmed, kind/bug, team/engines
