### ISSUE TITLE
Feature request: Generate `model` names for `MiddlewareParams`

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma-client-js#905] opened 2020-10-06 05:09 UTC
## Problem

The client generator generates a `MiddlewareParams` type whose keys are `model`, `action`, ... and so forth. `action` is from type `PrismaAction` and consists of several action types. `model` on the other hand is just a `string` and one must always know the exact names of models available in the schema.

## Suggested solution

Generate a `PrismaModel` type (or similar) consisting of the names of models available as `string`s and attach it to the `model` property of `MiddlewareParams`.

## Alternatives

Leave it as it is.

**Comment by pantharshit00** [comment] 2020-10-07 10:30
I think this is a duplicate of https://github.com/prisma/prisma/issues/3545

This actually being worked on so I expect it to land.

**Closed by pantharshit00** 2020-10-07 10:31 UTC
