### ISSUE TITLE
composite unique indexes appears to be ignoring relations

### ISSUE THREAD

**Issue by esistgut** [prisma/prisma-client-js#556] opened 2020-03-09 01:21 UTC
I created a minimal sample showing the problem: https://github.com/esistgut/prisma-issue/tree/composite-unique-relation

To test it:
1. `git clone -b composite-unique-relation https://github.com/esistgut/prisma-issue`
2. `npm install`
3. Run `npm run prismation` (This will run prisma2 migrate)
4. Open index.ts and execute the populate method in main
5. Run ts-node index.ts
6. Now execute the test method in main function
7. Run ts-node index.ts to reproduce.

As you can see the `test()` function can search with only
```
where: {
  owner_code: {code: 'samecode'}
}
```
this is the generated relevant part:
```
export type CodeCompoundUniqueInput = {
  code: string
}
```

shouldn't it require the `owner` for the `User` relation?

**Comment by pantharshit00** [comment] 2020-03-18 07:18
Hi,

This appears to be duplicate of https://github.com/prisma/prisma-client-js/issues/582 and I am unable to reproduce this in latest preview024. Please try again with that version.

So I am closing this as a duplicate of https://github.com/prisma/prisma-client-js/issues/582. Please comment there if you still encounter this.

**Closed by pantharshit00** 2020-03-18 07:18 UTC

**Comment by esistgut** [comment] 2020-03-18 11:19
I can confirm preview024 fixed this issue.
As this issue ended as a duplicate of a more recent one and didn't get much response before I can't help thinking something was wrong with my report. Please clarify so I wont risk polluting this tracker with reports without much value.

**Comment by pantharshit00** [comment] 2020-03-18 14:35
@esistgut Your report is completely fine :). It just happened that I clicked on the other one before and that was resolved. Keep reporting any problems that you encounter.
