### ISSUE TITLE
Error when using generated prisma client: const dmmf = JSON.parse(dmmfString)  SyntaxError: Unexpected token in JSON

### ISSUE THREAD

**Issue by Tostendo** [prisma/prisma-client-js#519] opened 2020-02-22 13:30 UTC
I have this schema:

```sql
CREATE TABLE IF NOT EXISTS organizations (
  id TEXT,
  name TEXT,
  profile JSONB,
  registered DATE,
  logo_image TEXT,
 verification_code SERIAL,
 verified BOOLEAN,
 PRIMARY KEY (id)
);
```

and get this model after running `prisma2 introspect` 

```prisma
model organizations {
  id                String    @id
  logo_image        String?
  name              String?
  profile           String?
  registered        DateTime?
  verification_code Int
  verified          Boolean?
}
```

after running `prisma2 generate`and I execute the following code:

```js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const x = await prisma.organizations.create({
    data: {
      id: "some_id",
      verification_code: 123345
    }
  });
  console.log(x);
}

main();
```

I get the following error:

```
const dmmf = JSON.parse(dmmfString)
                  ^
SyntaxError: Unexpected token 
 in JSON at position 6232
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (~/prisma/node_modules/@prisma/client/index.js:3989:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (~/prisma/index.js:1:26)
```

**Comment by janpio** [comment] 2020-02-22 14:34
I can confirm this fails, with `alpha.820` it is this error message::

```
C:\Users\Jan\Documents\throwaway\1083>node index.js
(node:17724) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.organizations.create()` invocation in
C:\Users\Jan\Documents\throwaway\1083\index.js:5:40

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(3), cause: Some(WrongType { postgres: Type(Jsonb), rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\1083\node_modules\@prisma\client\index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by xuxusheng** [comment] 2020-02-25 12:51
![image](https://user-images.githubusercontent.com/15248446/75249080-74c4d880-5810-11ea-9384-1081e747ad64.png)

**Comment by pantharshit00** [comment] 2020-02-25 15:51
@xuxusheng Can you please share your datamodel with us? Are you also using `Json` or `JSONB` types in your database?

**Comment by xuxusheng** [comment] 2020-02-26 03:37
I encountered this problem during the upgrade of prisma2.0.0-preview019 to 2.0.0-preview022，The database is automatically generated by Prisma。

```
model User {
  id        String     @default(cuid()) @id
  email     String     @unique
  name      String     @unique
  password  String
  isAdmin   Boolean    @default(false)
  posts     Post[]
  types     PostType[]
  tags      PostTag[]
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
}

model Post {
  id          String    @default(cuid()) @id
  title       String?
  content     String?
  author      User
  type        PostType?
  tags        PostTag[]
  publishedAt DateTime?
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
}

model PostType {
  id        String   @default(cuid()) @id
  name      String
  posts     Post[]
  user      User
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model PostTag {
  id        String   @default(cuid()) @id
  name      String
  posts     Post[]
  user      User
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

**Comment by pantharshit00** [comment] 2020-02-26 11:47
I am unable to reproduce this with the schema you have shared. Can you please share a minimal reproduction of your problem in a Git repository.

Also, maybe open a new issue, as your problem is unrelated to this issue.

**Comment by timsuchanek** [comment] 2020-04-07 09:58
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed by timsuchanek** 2020-04-07 09:58 UTC
Labels: bug/2-confirmed, kind/bug, topic: json, topic: types
