### ISSUE TITLE
Invalid include query results in unexpected output

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#608] opened 2020-03-29 15:03 UTC
This issue is related to https://github.com/prisma/prisma-client-js/issues/607

Schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model api_keys {
  allowed_ips   String[]
  created_at    DateTime
  created_by_id Int?
  hidden        Boolean  @default(false)
  id            Int      @default(autoincrement()) @id
  key           String
  updated_at    DateTime
  user_id       Int?     @unique

  @@index([key], name: "index_api_keys_on_key")
}
```

When running the following **invalid** query I'm getting some really weird terminal output before the helpful intended runtime error message is shown:

```ts
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

prisma.api_keys.findMany({ first: 1, include: { user: true } }).then(x => {
  console.log(x)
  prisma.disconnect()
})
```

![image](https://user-images.githubusercontent.com/1567498/77852451-1740f480-71df-11ea-8f60-8eaa0d862b41.png)

_scrolling_

![image](https://user-images.githubusercontent.com/1567498/77852460-1f992f80-71df-11ea-99e2-5cb0a53e6102.png)

_scrolling_

![image](https://user-images.githubusercontent.com/1567498/77852466-29229780-71df-11ea-9dd2-707cf0ed8371.png)

_scrolling_

![image](https://user-images.githubusercontent.com/1567498/77852472-2f187880-71df-11ea-8243-4117d981451e.png)

**Comment by janpio** [comment] 2020-03-29 16:31
Earlier issue with similar output problem: https://github.com/prisma/prisma-client-js/issues/533 (There are more that I can not find right now)

**Comment by timsuchanek** [comment] 2020-03-30 15:46
Thanks for reporting!
I had a look into it, but can't reproduce the ugly long stack trace right now.
Which version of `ts-node`, `typescript` and `node` are you running?
Are you running the script with `ts-node script.ts`?

**Comment by FinnFrotscher** [comment] 2020-04-01 01:05
+1

**Comment by timsuchanek** [comment] 2020-04-01 09:26
As mentioned in https://github.com/prisma/prisma-client-js/issues/533#issuecomment-607139681
this is now fixed in the latest alpha 🙂

**Closed by timsuchanek** 2020-04-01 09:26 UTC
Labels: bug/1-repro-available, kind/bug, process/candidate
