### ISSUE TITLE
Find by a null time doesn't work

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-js#486] opened 2020-02-13 15:41 UTC
```sql
create table events (
  id serial not null primary key,
  "time" timestamp with time zone
);
insert into events ("time") values (NULL);
insert into events ("time") values (NULL);
insert into events ("time") values (NULL);
```

```ts
client.events.findMany({ where: { time: null } })
```

Expect 3 fields, don't get any back.

**Comment by pantharshit00** [comment] 2020-02-14 14:07
I received a rust panic when I tried the above:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/22195362/74538019-394d2300-4f61-11ea-95f0-564d93a16e3d.png">


```
 const data = await client.events.findMany(Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(1), cause: Some(WrongType { postgres: Type(Timestamptz), rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/Users/harshit/code/reproductions/issue-matt-2/node_modules/@prisma/client/index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:8290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 const data = await client.events.findMany(Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(1), cause: Some(WrongType { postgres: Type(Timestamptz), rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/Users/harshit/code/reproductions/issue-matt-2/node_modules/@prisma/client/index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:8290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://xxxxx:xxxxxx@localhost:5432/matt-2?schema=public"
}

model events {
  id   Int       @id
  time DateTime?
}
```

Version: `prisma2@2.0.0-alpha.781, binary version: a1a562d6f7093ae4ac17ebe3c8d2b387b2ed0598`

**Comment by janpio** [comment] 2020-03-16 14:48
Can you please reconfirm this @pantharshit00? @tomhoule recently fixed some stuff related to timestamps, so maybe this returns a different error message now.

**Comment by dpetrick** [comment] 2020-03-17 14:19
Unable to reproduce on the query-engine level.

Datamodel:
```prisma
model Event {
  id   Int       @id
  time DateTime?
}
```

After firing a bunch of mutations with and without time set:
```graphql
mutation {
  createOneEvent(data: {
    id: 5
    time: "2020-03-17T13:32:09"
  }) {
    id
    time
  }
}
```

I am able to get only events with time: null as following:
```graphql
{
  findManyEvent(where: {
    time: null
  }) {
    id
    time
  }
}
```

**Comment by pantharshit00** [comment] 2020-03-17 18:15
Unable to reproduce as well in preview024. Closing

**Closed by pantharshit00** 2020-03-17 18:15 UTC
Labels: bug/2-confirmed, kind/bug, topic: types
